# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go_modules:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /client
    schedule:
      interval: weekly
    groups:
      go_modules:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /apigen
    schedule:
      interval: weekly
    groups:
      go_modules:
        patterns:
          - "*"
