// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calypr/syfon/client/conf (interfaces: ManagerInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_configure.go -package=mocks github.com/calypr/syfon/client/conf ManagerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	conf "github.com/calypr/syfon/client/conf"
	gomock "go.uber.org/mock/gomock"
)

// MockManagerInterface is a mock of ManagerInterface interface.
type MockManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockManagerInterfaceMockRecorder is the mock recorder for MockManagerInterface.
type MockManagerInterfaceMockRecorder struct {
	mock *MockManagerInterface
}

// NewMockManagerInterface creates a new mock instance.
func NewMockManagerInterface(ctrl *gomock.Controller) *MockManagerInterface {
	mock := &MockManagerInterface{ctrl: ctrl}
	mock.recorder = &MockManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagerInterface) EXPECT() *MockManagerInterfaceMockRecorder {
	return m.recorder
}

// EnsureExists mocks base method.
func (m *MockManagerInterface) EnsureExists() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureExists")
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureExists indicates an expected call of EnsureExists.
func (mr *MockManagerInterfaceMockRecorder) EnsureExists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureExists", reflect.TypeOf((*MockManagerInterface)(nil).EnsureExists))
}

// Import mocks base method.
func (m *MockManagerInterface) Import(filePath, fenceToken string) (*conf.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", filePath, fenceToken)
	ret0, _ := ret[0].(*conf.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockManagerInterfaceMockRecorder) Import(filePath, fenceToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockManagerInterface)(nil).Import), filePath, fenceToken)
}

// IsCredentialValid mocks base method.
func (m *MockManagerInterface) IsCredentialValid(arg0 *conf.Credential) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCredentialValid", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCredentialValid indicates an expected call of IsCredentialValid.
func (mr *MockManagerInterfaceMockRecorder) IsCredentialValid(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCredentialValid", reflect.TypeOf((*MockManagerInterface)(nil).IsCredentialValid), arg0)
}

// IsTokenValid mocks base method.
func (m *MockManagerInterface) IsTokenValid(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenValid", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenValid indicates an expected call of IsTokenValid.
func (mr *MockManagerInterfaceMockRecorder) IsTokenValid(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenValid", reflect.TypeOf((*MockManagerInterface)(nil).IsTokenValid), arg0)
}

// Load mocks base method.
func (m *MockManagerInterface) Load(profile string) (*conf.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", profile)
	ret0, _ := ret[0].(*conf.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockManagerInterfaceMockRecorder) Load(profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockManagerInterface)(nil).Load), profile)
}

// Save mocks base method.
func (m *MockManagerInterface) Save(cred *conf.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockManagerInterfaceMockRecorder) Save(cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockManagerInterface)(nil).Save), cred)
}
