version: 2

builds:
  - binary: syfon
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - >-
        CC={{- if eq .Os "linux" -}}
          {{- if eq .Arch "amd64"}}zig cc -target x86_64-linux-musl
          {{- else if eq .Arch "arm64"}}zig cc -target aarch64-linux-musl
          {{- end}}
        {{- else}}cc{{- end}}
    ldflags: >
      -X github.com/calypr/syfon/version.BuildDate={{.Date}}
      -X github.com/calypr/syfon/version.GitCommit={{.ShortCommit}}
      -X github.com/calypr/syfon/version.GitBranch={{.Branch}}
      -X github.com/calypr/syfon/version.GitUpstream={{.GitURL}}
      -X github.com/calypr/syfon/version.Version={{.Version}}

dist: build/release

release:
  draft: false
  prerelease: auto

checksum:
  name_template: "syfon-{{.Tag}}-checksums.txt"

archives:
  - formats:
      - tar.gz
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Tag}}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

# Add changelog generation
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
