codecov:
  require_ci_to_pass: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

coverage:
  precision: 2
  round: down
  range: "60...100"
<<<<<<< Updated upstream
=======
  ignore:
    - "/apigen/"
    - "/tests/endpoints/"
    - "/testutils/"
    - "/cmd/"
>>>>>>> Stashed changes
  status:
    project:
      default:
        target: auto
        threshold: 1%
      root:
        flags:
          - root
        target: auto
        threshold: 1%
      client:
        flags:
          - client
        target: auto
        threshold: 1%

flags:
  root:
    carryforward: true
  client:
    carryforward: true
  binary-endpoint:
    carryforward: true
