codecov:
  require_ci_to_pass: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

coverage:
  precision: 2
  round: down
  range: "60...100"
  ignore:
    - "apigen"
    - "tests"
    - "testutils"
    - "cmd/openapi-remove-examples"
  status:
    project:
      default:
        target: auto
        threshold: 1%
      root:
        flags:
          - root
        target: auto
        threshold: 1%
      client:
        flags:
          - client
        target: auto
        threshold: 1%

flags:
  root:
    carryforward: true
  client:
    carryforward: true
