site_name: drs-server
theme:
  name: readthedocs
  custom_dir: overrides
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Build: build.md
  - Configuration: configuration.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md
  - Development: development.md
  - Architecture: architecture.md
  - ADR: adr-internal-vs-ga4gh-drs.md
