/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apigen

import (
	"github.com/gin-gonic/gin"
)

type UploadRequestAPI struct {
}

// Post /ga4gh/drs/v1/upload-request
// Request upload methods for files 
func (api *UploadRequestAPI) PostUploadRequest(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

