/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apigen

type UploadRequestObject struct {

	// The name of the file to upload
	Name string `json:"name"`

	// Size of the file in bytes
	Size int64 `json:"size"`

	// MIME type of the file
	MimeType string `json:"mime_type"`

	// Array of checksums for file integrity verification
	Checksums []Checksum `json:"checksums"`

	// Optional description of the file
	Description string `json:"description,omitempty"`

	// Optional array of alternative names for the file
	Aliases []string `json:"aliases,omitempty"`
}
