/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BulkAccessMethodUpdateRequestUpdatesInner struct {

	// DRS object ID to update
	ObjectId string `json:"object_id"`

	// New access methods for this object
	AccessMethods []AccessMethod `json:"access_methods"`
}
