/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apigen

// ServiceOrganization - Organization providing the service
type ServiceOrganization struct {

	// Name of the organization responsible for the service
	Name string `json:"name"`

	// URL of the website of the organization (RFC 3986 format)
	Url string `json:"url"`
}
