/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UnresolvedInner struct {

	ErrorCode int32 `json:"error_code,omitempty"`

	ObjectIds []string `json:"object_ids,omitempty"`
}
