/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UploadRequest struct {

	// Array of upload requests for files
	Requests []UploadRequestObject `json:"requests"`

	// Optional array of GA4GH Passport JWTs for authorization
	Passports []string `json:"passports,omitempty"`
}
