/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apigen

// Error - An object that can optionally include information about the error.
type Error struct {

	// A detailed error message.
	Msg string `json:"msg,omitempty"`

	// The integer representing the HTTP status code (e.g. 200, 404).
	StatusCode int32 `json:"status_code,omitempty"`
}
