/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetBulkObjects200Response struct {

	Summary Summary `json:"summary,omitempty"`

	// Error codes for each unresolved drs objects.
	UnresolvedDrsObjects []UnresolvedInner `json:"unresolved_drs_objects,omitempty"`

	ResolvedDrsObject []DrsObject `json:"resolved_drs_object,omitempty"`
}
