/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RegisterObjects201Response struct {

	// Array of registered DRS objects in the same order as the candidates in the request
	Objects []DrsObject `json:"objects"`
}
