/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RegisterObjectsRequest struct {

	// Array of DRS object candidates to register (server will mint IDs and timestamps)
	Candidates []DrsObjectCandidate `json:"candidates"`

	// Optional array of GA4GH Passport JWTs for authorization
	Passports []string `json:"passports,omitempty"`
}
