/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apigen

// Summary - A summary of what was resolved.
type Summary struct {

	// Number of items requested.
	Requested int32 `json:"requested,omitempty"`

	// Number of objects resolved.
	Resolved int32 `json:"resolved,omitempty"`

	// Number of objects not resolved.
	Unresolved int32 `json:"unresolved,omitempty"`
}
