// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// ObjectsAPIController binds http requests to an api service and writes the service results to the http response
type ObjectsAPIController struct {
	service ObjectsAPIServicer
	errorHandler ErrorHandler
}

// ObjectsAPIOption for how the controller is set up.
type ObjectsAPIOption func(*ObjectsAPIController)

// WithObjectsAPIErrorHandler inject ErrorHandler into controller
func WithObjectsAPIErrorHandler(h ErrorHandler) ObjectsAPIOption {
	return func(c *ObjectsAPIController) {
		c.errorHandler = h
	}
}

// NewObjectsAPIController creates a default api controller
func NewObjectsAPIController(s ObjectsAPIServicer, opts ...ObjectsAPIOption) *ObjectsAPIController {
	controller := &ObjectsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ObjectsAPIController
func (c *ObjectsAPIController) Routes() Routes {
	return Routes{
		"GetObject": Route{
			"GetObject",
			strings.ToUpper("Get"),
			"/ga4gh/drs/v1/objects/{object_id}",
			c.GetObject,
		},
		"PostObject": Route{
			"PostObject",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/{object_id}",
			c.PostObject,
		},
		"OptionsObject": Route{
			"OptionsObject",
			strings.ToUpper("Options"),
			"/ga4gh/drs/v1/objects/{object_id}",
			c.OptionsObject,
		},
		"DeleteObject": Route{
			"DeleteObject",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/{object_id}/delete",
			c.DeleteObject,
		},
		"BulkDeleteObjects": Route{
			"BulkDeleteObjects",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/delete",
			c.BulkDeleteObjects,
		},
		"GetBulkObjects": Route{
			"GetBulkObjects",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects",
			c.GetBulkObjects,
		},
		"OptionsBulkObject": Route{
			"OptionsBulkObject",
			strings.ToUpper("Options"),
			"/ga4gh/drs/v1/objects",
			c.OptionsBulkObject,
		},
		"RegisterObjects": Route{
			"RegisterObjects",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/register",
			c.RegisterObjects,
		},
		"GetAccessURL": Route{
			"GetAccessURL",
			strings.ToUpper("Get"),
			"/ga4gh/drs/v1/objects/{object_id}/access/{access_id}",
			c.GetAccessURL,
		},
		"PostAccessURL": Route{
			"PostAccessURL",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/{object_id}/access/{access_id}",
			c.PostAccessURL,
		},
		"GetBulkAccessURL": Route{
			"GetBulkAccessURL",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/access",
			c.GetBulkAccessURL,
		},
		"UpdateObjectAccessMethods": Route{
			"UpdateObjectAccessMethods",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/{object_id}/access-methods",
			c.UpdateObjectAccessMethods,
		},
		"GetObjectsByChecksum": Route{
			"GetObjectsByChecksum",
			strings.ToUpper("Get"),
			"/ga4gh/drs/v1/objects/checksum/{checksum}",
			c.GetObjectsByChecksum,
		},
		"BulkUpdateAccessMethods": Route{
			"BulkUpdateAccessMethods",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/access-methods",
			c.BulkUpdateAccessMethods,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the ObjectsAPIController
func (c *ObjectsAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetObject",
			strings.ToUpper("Get"),
			"/ga4gh/drs/v1/objects/{object_id}",
			c.GetObject,
		},
		Route{
			"PostObject",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/{object_id}",
			c.PostObject,
		},
		Route{
			"OptionsObject",
			strings.ToUpper("Options"),
			"/ga4gh/drs/v1/objects/{object_id}",
			c.OptionsObject,
		},
		Route{
			"DeleteObject",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/{object_id}/delete",
			c.DeleteObject,
		},
		Route{
			"BulkDeleteObjects",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/delete",
			c.BulkDeleteObjects,
		},
		Route{
			"GetBulkObjects",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects",
			c.GetBulkObjects,
		},
		Route{
			"OptionsBulkObject",
			strings.ToUpper("Options"),
			"/ga4gh/drs/v1/objects",
			c.OptionsBulkObject,
		},
		Route{
			"RegisterObjects",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/register",
			c.RegisterObjects,
		},
		Route{
			"GetAccessURL",
			strings.ToUpper("Get"),
			"/ga4gh/drs/v1/objects/{object_id}/access/{access_id}",
			c.GetAccessURL,
		},
		Route{
			"PostAccessURL",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/{object_id}/access/{access_id}",
			c.PostAccessURL,
		},
		Route{
			"GetBulkAccessURL",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/access",
			c.GetBulkAccessURL,
		},
		Route{
			"UpdateObjectAccessMethods",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/{object_id}/access-methods",
			c.UpdateObjectAccessMethods,
		},
		Route{
			"GetObjectsByChecksum",
			strings.ToUpper("Get"),
			"/ga4gh/drs/v1/objects/checksum/{checksum}",
			c.GetObjectsByChecksum,
		},
		Route{
			"BulkUpdateAccessMethods",
			strings.ToUpper("Post"),
			"/ga4gh/drs/v1/objects/access-methods",
			c.BulkUpdateAccessMethods,
		},
	}
}



// GetObject - Get info about a DrsObject.
func (c *ObjectsAPIController) GetObject(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	objectIdParam := params["object_id"]
	if objectIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"object_id"}, nil)
		return
	}
	var expandParam bool
	if query.Has("expand") {
		param, err := parseBoolParameter(
			query.Get("expand"),
			WithParse[bool](parseBool),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "expand", Err: err}, nil)
			return
		}

		expandParam = param
	} else {
	}
	result, err := c.service.GetObject(r.Context(), objectIdParam, expandParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PostObject - Get info about a DrsObject through POST'ing a Passport.
func (c *ObjectsAPIController) PostObject(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	objectIdParam := params["object_id"]
	if objectIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"object_id"}, nil)
		return
	}
	var postObjectRequestParam PostObjectRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&postObjectRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPostObjectRequestRequired(postObjectRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertPostObjectRequestConstraints(postObjectRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.PostObject(r.Context(), objectIdParam, postObjectRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// OptionsObject - Get Authorization info about a DrsObject.
func (c *ObjectsAPIController) OptionsObject(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	objectIdParam := params["object_id"]
	if objectIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"object_id"}, nil)
		return
	}
	result, err := c.service.OptionsObject(r.Context(), objectIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteObject - Delete a DRS object (optional endpoint)
func (c *ObjectsAPIController) DeleteObject(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	objectIdParam := params["object_id"]
	if objectIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"object_id"}, nil)
		return
	}
	var bodyParam DeleteRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil && !errors.Is(err, io.EOF) {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertDeleteRequestRequired(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertDeleteRequestConstraints(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.DeleteObject(r.Context(), objectIdParam, bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// BulkDeleteObjects - Delete multiple DRS objects
func (c *ObjectsAPIController) BulkDeleteObjects(w http.ResponseWriter, r *http.Request) {
	var bodyParam BulkDeleteRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBulkDeleteRequestRequired(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBulkDeleteRequestConstraints(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.BulkDeleteObjects(r.Context(), bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetBulkObjects - Get info about multiple DrsObjects with an optional Passport(s).
func (c *ObjectsAPIController) GetBulkObjects(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var getBulkObjectsRequestParam GetBulkObjectsRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&getBulkObjectsRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertGetBulkObjectsRequestRequired(getBulkObjectsRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertGetBulkObjectsRequestConstraints(getBulkObjectsRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	var expandParam bool
	if query.Has("expand") {
		param, err := parseBoolParameter(
			query.Get("expand"),
			WithParse[bool](parseBool),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "expand", Err: err}, nil)
			return
		}

		expandParam = param
	} else {
	}
	result, err := c.service.GetBulkObjects(r.Context(), getBulkObjectsRequestParam, expandParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// OptionsBulkObject - Get Authorization info about multiple DrsObjects.
func (c *ObjectsAPIController) OptionsBulkObject(w http.ResponseWriter, r *http.Request) {
	var bulkObjectIdNoPassportParam BulkObjectIdNoPassport
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bulkObjectIdNoPassportParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBulkObjectIdNoPassportRequired(bulkObjectIdNoPassportParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBulkObjectIdNoPassportConstraints(bulkObjectIdNoPassportParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.OptionsBulkObject(r.Context(), bulkObjectIdNoPassportParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// RegisterObjects - Register DRS objects
func (c *ObjectsAPIController) RegisterObjects(w http.ResponseWriter, r *http.Request) {
	var bodyParam RegisterObjectsRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertRegisterObjectsRequestRequired(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertRegisterObjectsRequestConstraints(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.RegisterObjects(r.Context(), bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetAccessURL - Get a URL for fetching bytes
func (c *ObjectsAPIController) GetAccessURL(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	objectIdParam := params["object_id"]
	if objectIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"object_id"}, nil)
		return
	}
	accessIdParam := params["access_id"]
	if accessIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"access_id"}, nil)
		return
	}
	result, err := c.service.GetAccessURL(r.Context(), objectIdParam, accessIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PostAccessURL - Get a URL for fetching bytes through POST'ing a Passport
func (c *ObjectsAPIController) PostAccessURL(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	objectIdParam := params["object_id"]
	if objectIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"object_id"}, nil)
		return
	}
	accessIdParam := params["access_id"]
	if accessIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"access_id"}, nil)
		return
	}
	var postAccessUrlRequestParam PostAccessUrlRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&postAccessUrlRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPostAccessUrlRequestRequired(postAccessUrlRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertPostAccessUrlRequestConstraints(postAccessUrlRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.PostAccessURL(r.Context(), objectIdParam, accessIdParam, postAccessUrlRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetBulkAccessURL - Get URLs for fetching bytes from multiple objects with an optional Passport(s).
func (c *ObjectsAPIController) GetBulkAccessURL(w http.ResponseWriter, r *http.Request) {
	var bulkObjectAccessIdParam BulkObjectAccessId
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bulkObjectAccessIdParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBulkObjectAccessIdRequired(bulkObjectAccessIdParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBulkObjectAccessIdConstraints(bulkObjectAccessIdParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.GetBulkAccessURL(r.Context(), bulkObjectAccessIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateObjectAccessMethods - Update access methods for a DRS object
func (c *ObjectsAPIController) UpdateObjectAccessMethods(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	objectIdParam := params["object_id"]
	if objectIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"object_id"}, nil)
		return
	}
	var accessMethodUpdateRequestParam AccessMethodUpdateRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&accessMethodUpdateRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertAccessMethodUpdateRequestRequired(accessMethodUpdateRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertAccessMethodUpdateRequestConstraints(accessMethodUpdateRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateObjectAccessMethods(r.Context(), objectIdParam, accessMethodUpdateRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetObjectsByChecksum - Get DRS objects that are a match for the checksum.
func (c *ObjectsAPIController) GetObjectsByChecksum(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	checksumParam := params["checksum"]
	if checksumParam == "" {
		c.errorHandler(w, r, &RequiredError{"checksum"}, nil)
		return
	}
	result, err := c.service.GetObjectsByChecksum(r.Context(), checksumParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// BulkUpdateAccessMethods - Bulk update access methods for multiple DRS objects
func (c *ObjectsAPIController) BulkUpdateAccessMethods(w http.ResponseWriter, r *http.Request) {
	var bulkAccessMethodUpdateRequestParam BulkAccessMethodUpdateRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bulkAccessMethodUpdateRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertBulkAccessMethodUpdateRequestRequired(bulkAccessMethodUpdateRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertBulkAccessMethodUpdateRequestConstraints(bulkAccessMethodUpdateRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.BulkUpdateAccessMethods(r.Context(), bulkAccessMethodUpdateRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
