// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs

import (
	"context"
	"net/http"
	"errors"
)

// ObjectsAPIService is a service that implements the logic for the ObjectsAPIServicer
// This service should implement the business logic for every endpoint for the ObjectsAPI API.
// Include any external packages or services that will be required by this service.
type ObjectsAPIService struct {
}

// NewObjectsAPIService creates a default api service
func NewObjectsAPIService() *ObjectsAPIService {
	return &ObjectsAPIService{}
}

// GetObject - Get info about a DrsObject.
func (s *ObjectsAPIService) GetObject(ctx context.Context, objectId string, expand bool) (ImplResponse, error) {
	// TODO - update GetObject with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DrsObject{}) or use other options such as http.Ok ...
	// return Response(200, DrsObject{}), nil

	// TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	// return Response(202, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetObject method not implemented")
}

// PostObject - Get info about a DrsObject through POST&#39;ing a Passport.
func (s *ObjectsAPIService) PostObject(ctx context.Context, objectId string, postObjectRequest PostObjectRequest) (ImplResponse, error) {
	// TODO - update PostObject with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DrsObject{}) or use other options such as http.Ok ...
	// return Response(200, DrsObject{}), nil

	// TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	// return Response(202, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostObject method not implemented")
}

// OptionsObject - Get Authorization info about a DrsObject.
func (s *ObjectsAPIService) OptionsObject(ctx context.Context, objectId string) (ImplResponse, error) {
	// TODO - update OptionsObject with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Authorizations{}) or use other options such as http.Ok ...
	// return Response(200, Authorizations{}), nil

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OptionsObject method not implemented")
}

// GetBulkObjects - Get info about multiple DrsObjects with an optional Passport(s).
func (s *ObjectsAPIService) GetBulkObjects(ctx context.Context, getBulkObjectsRequest GetBulkObjectsRequest, expand bool) (ImplResponse, error) {
	// TODO - update GetBulkObjects with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetBulkObjects200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetBulkObjects200Response{}), nil

	// TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	// return Response(202, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(413, Error{}) or use other options such as http.Ok ...
	// return Response(413, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetBulkObjects method not implemented")
}

// OptionsBulkObject - Get Authorization info about multiple DrsObjects.
func (s *ObjectsAPIService) OptionsBulkObject(ctx context.Context) (ImplResponse, error) {
	// TODO - update OptionsBulkObject with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OptionsBulkObject200Response{}) or use other options such as http.Ok ...
	// return Response(200, OptionsBulkObject200Response{}), nil

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	// return Response(405, nil),nil

	// TODO: Uncomment the next line to return response Response(413, Error{}) or use other options such as http.Ok ...
	// return Response(413, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OptionsBulkObject method not implemented")
}

// GetAccessURL - Get a URL for fetching bytes
func (s *ObjectsAPIService) GetAccessURL(ctx context.Context, objectId string, accessId string) (ImplResponse, error) {
	// TODO - update GetAccessURL with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AccessUrl{}) or use other options such as http.Ok ...
	// return Response(200, AccessUrl{}), nil

	// TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	// return Response(202, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAccessURL method not implemented")
}

// PostAccessURL - Get a URL for fetching bytes through POST&#39;ing a Passport
func (s *ObjectsAPIService) PostAccessURL(ctx context.Context, objectId string, accessId string, postAccessUrlRequest PostAccessUrlRequest) (ImplResponse, error) {
	// TODO - update PostAccessURL with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, AccessUrl{}) or use other options such as http.Ok ...
	// return Response(200, AccessUrl{}), nil

	// TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	// return Response(202, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostAccessURL method not implemented")
}

// GetBulkAccessURL - Get URLs for fetching bytes from multiple objects with an optional Passport(s).
func (s *ObjectsAPIService) GetBulkAccessURL(ctx context.Context, bulkObjectAccessId BulkObjectAccessId) (ImplResponse, error) {
	// TODO - update GetBulkAccessURL with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetBulkAccessUrl200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetBulkAccessUrl200Response{}), nil

	// TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	// return Response(202, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(413, Error{}) or use other options such as http.Ok ...
	// return Response(413, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetBulkAccessURL method not implemented")
}

// UpdateObjectAccessMethods - Update access methods for a DRS object
func (s *ObjectsAPIService) UpdateObjectAccessMethods(ctx context.Context, objectId string, accessMethodUpdateRequest AccessMethodUpdateRequest) (ImplResponse, error) {
	// TODO - update UpdateObjectAccessMethods with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DrsObject{}) or use other options such as http.Ok ...
	// return Response(200, DrsObject{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateObjectAccessMethods method not implemented")
}

// BulkUpdateAccessMethods - Bulk update access methods for multiple DRS objects
func (s *ObjectsAPIService) BulkUpdateAccessMethods(ctx context.Context, bulkAccessMethodUpdateRequest BulkAccessMethodUpdateRequest) (ImplResponse, error) {
	// TODO - update BulkUpdateAccessMethods with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, BulkUpdateAccessMethods200Response{}) or use other options such as http.Ok ...
	// return Response(200, BulkUpdateAccessMethods200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(413, Error{}) or use other options such as http.Ok ...
	// return Response(413, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BulkUpdateAccessMethods method not implemented")
}

// AddChecksums - Add additional checksums for a DRS object
func (s *ObjectsAPIService) AddChecksums(ctx context.Context, objectId string, checksumAdditionRequest ChecksumAdditionRequest) (ImplResponse, error) {
	// TODO - update AddChecksums with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DrsObject{}) or use other options such as http.Ok ...
	// return Response(200, DrsObject{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(413, Error{}) or use other options such as http.Ok ...
	// return Response(413, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddChecksums method not implemented")
}

// GetObjectsByChecksum - Get DRS objects that are a match for the checksum.
func (s *ObjectsAPIService) GetObjectsByChecksum(ctx context.Context, accessId string) (ImplResponse, error) {
	// TODO - update GetObjectsByChecksum with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetBulkObjects200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetBulkObjects200Response{}), nil

	// TODO: Uncomment the next line to return response Response(202, {}) or use other options such as http.Ok ...
	// return Response(202, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetObjectsByChecksum method not implemented")
}

// BulkAddChecksums - Add additional checksums for multiple DRS objects
func (s *ObjectsAPIService) BulkAddChecksums(ctx context.Context, bulkChecksumAdditionRequest BulkChecksumAdditionRequest) (ImplResponse, error) {
	// TODO - update BulkAddChecksums with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, BulkUpdateAccessMethods200Response{}) or use other options such as http.Ok ...
	// return Response(200, BulkUpdateAccessMethods200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(413, Error{}) or use other options such as http.Ok ...
	// return Response(413, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BulkAddChecksums method not implemented")
}

// DeleteObject - Delete a DRS object (optional endpoint)
func (s *ObjectsAPIService) DeleteObject(ctx context.Context, objectId string, body DeleteRequest) (ImplResponse, error) {
	// TODO - update DeleteObject with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteObject method not implemented")
}

// BulkDeleteObjects - Delete multiple DRS objects
func (s *ObjectsAPIService) BulkDeleteObjects(ctx context.Context, body BulkDeleteRequest) (ImplResponse, error) {
	// TODO - update BulkDeleteObjects with the required logic for this service method.
	// Add api_objects_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	// TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	// return Response(403, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(413, Error{}) or use other options such as http.Ok ...
	// return Response(413, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BulkDeleteObjects method not implemented")
}
