// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs

type AccessMethodUpdateRequest struct {

	// New access methods for the DRS object
	AccessMethods []AccessMethod `json:"access_methods"`

	// Optional GA4GH Passport JWTs for authorization
	Passports []string `json:"passports,omitempty"`
}

// AssertAccessMethodUpdateRequestRequired checks if the required fields are not zero-ed
func AssertAccessMethodUpdateRequestRequired(obj AccessMethodUpdateRequest) error {
	elements := map[string]interface{}{
		"access_methods": obj.AccessMethods,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.AccessMethods {
		if err := AssertAccessMethodRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAccessMethodUpdateRequestConstraints checks if the values respects the defined constraints
func AssertAccessMethodUpdateRequestConstraints(obj AccessMethodUpdateRequest) error {
	for _, el := range obj.AccessMethods {
		if err := AssertAccessMethodConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
