// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs




type PostAccessUrlRequest struct {

	// the encoded JWT GA4GH Passport that contains embedded Visas.  The overall JWT is signed as are the individual Passport Visas.
	Passports []string `json:"passports,omitempty"`
}

// AssertPostAccessUrlRequestRequired checks if the required fields are not zero-ed
func AssertPostAccessUrlRequestRequired(obj PostAccessUrlRequest) error {
	return nil
}

// AssertPostAccessUrlRequestConstraints checks if the values respects the defined constraints
func AssertPostAccessUrlRequestConstraints(obj PostAccessUrlRequest) error {
	return nil
}
