// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs




type UploadResponseObject struct {

	// The name of the file
	Name string `json:"name"`

	// Size of the file in bytes
	Size int64 `json:"size"`

	// MIME type of the file
	MimeType string `json:"mime_type"`

	// Array of checksums for file integrity verification
	Checksums []Checksum `json:"checksums"`

	// Optional description of the file
	Description string `json:"description,omitempty"`

	// Optional array of alternative names
	Aliases []string `json:"aliases,omitempty"`

	// Available methods for uploading this file
	UploadMethods []UploadMethod `json:"upload_methods,omitempty"`
}

// AssertUploadResponseObjectRequired checks if the required fields are not zero-ed
func AssertUploadResponseObjectRequired(obj UploadResponseObject) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"size": obj.Size,
		"mime_type": obj.MimeType,
		"checksums": obj.Checksums,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Checksums {
		if err := AssertChecksumRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.UploadMethods {
		if err := AssertUploadMethodRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertUploadResponseObjectConstraints checks if the values respects the defined constraints
func AssertUploadResponseObjectConstraints(obj UploadResponseObject) error {
	for _, el := range obj.Checksums {
		if err := AssertChecksumConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.UploadMethods {
		if err := AssertUploadMethodConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
