// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs




type RegisterObjectsRequest struct {

	// Array of DRS object candidates to register (server will mint IDs and timestamps)
	Candidates []DrsObjectCandidate `json:"candidates"`

	// Optional array of GA4GH Passport JWTs for authorization
	Passports []string `json:"passports,omitempty"`
}

// AssertRegisterObjectsRequestRequired checks if the required fields are not zero-ed
func AssertRegisterObjectsRequestRequired(obj RegisterObjectsRequest) error {
	elements := map[string]interface{}{
		"candidates": obj.Candidates,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Candidates {
		if err := AssertDrsObjectCandidateRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRegisterObjectsRequestConstraints checks if the values respects the defined constraints
func AssertRegisterObjectsRequestConstraints(obj RegisterObjectsRequest) error {
	for _, el := range obj.Candidates {
		if err := AssertDrsObjectCandidateConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
