// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs




type OptionsBulkObject200Response struct {

	Summary Summary `json:"summary,omitempty"`

	// Error codes for each unresolved drs objects.
	UnresolvedDrsObjects []UnresolvedInner `json:"unresolved_drs_objects,omitempty"`

	ResolvedDrsObject []Authorizations `json:"resolved_drs_object,omitempty"`
}

// AssertOptionsBulkObject200ResponseRequired checks if the required fields are not zero-ed
func AssertOptionsBulkObject200ResponseRequired(obj OptionsBulkObject200Response) error {
	if err := AssertSummaryRequired(obj.Summary); err != nil {
		return err
	}
	for _, el := range obj.UnresolvedDrsObjects {
		if err := AssertUnresolvedInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.ResolvedDrsObject {
		if err := AssertAuthorizationsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertOptionsBulkObject200ResponseConstraints checks if the values respects the defined constraints
func AssertOptionsBulkObject200ResponseConstraints(obj OptionsBulkObject200Response) error {
	if err := AssertSummaryConstraints(obj.Summary); err != nil {
		return err
	}
	for _, el := range obj.UnresolvedDrsObjects {
		if err := AssertUnresolvedInnerConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.ResolvedDrsObject {
		if err := AssertAuthorizationsConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
