// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs

// AccessMethodAuthorizations - When `access_id` is provided, `authorizations` provides information about how to authorize the `/access` method.
type AccessMethodAuthorizations struct {
	DrsObjectId string `json:"drs_object_id,omitempty"`

	SupportedTypes []string `json:"supported_types,omitempty"`

	PassportAuthIssuers []string `json:"passport_auth_issuers,omitempty"`

	BearerAuthIssuers []string `json:"bearer_auth_issuers,omitempty"`
}

// AssertAccessMethodAuthorizationsRequired checks if the required fields are not zero-ed
func AssertAccessMethodAuthorizationsRequired(obj AccessMethodAuthorizations) error {
	return nil
}

// AssertAccessMethodAuthorizationsConstraints checks if the values respects the defined constraints
func AssertAccessMethodAuthorizationsConstraints(obj AccessMethodAuthorizations) error {
	return nil
}
