// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs




type BulkChecksumAdditionRequestUpdatesInner struct {

	// DRS object ID to add checksum for
	ObjectId string `json:"object_id"`

	// New checksums for this object
	Checksums []Checksum `json:"checksums"`
}

// AssertBulkChecksumAdditionRequestUpdatesInnerRequired checks if the required fields are not zero-ed
func AssertBulkChecksumAdditionRequestUpdatesInnerRequired(obj BulkChecksumAdditionRequestUpdatesInner) error {
	elements := map[string]interface{}{
		"object_id": obj.ObjectId,
		"checksums": obj.Checksums,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Checksums {
		if err := AssertChecksumRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertBulkChecksumAdditionRequestUpdatesInnerConstraints checks if the values respects the defined constraints
func AssertBulkChecksumAdditionRequestUpdatesInnerConstraints(obj BulkChecksumAdditionRequestUpdatesInner) error {
	for _, el := range obj.Checksums {
		if err := AssertChecksumConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
