// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs




type DrsPage struct {

	DrsObjects []DrsObject `json:"drs_objects"`
}

// AssertDrsPageRequired checks if the required fields are not zero-ed
func AssertDrsPageRequired(obj DrsPage) error {
	elements := map[string]interface{}{
		"drs_objects": obj.DrsObjects,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.DrsObjects {
		if err := AssertDrsObjectRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertDrsPageConstraints checks if the values respects the defined constraints
func AssertDrsPageConstraints(obj DrsPage) error {
	for _, el := range obj.DrsObjects {
		if err := AssertDrsObjectConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
