// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs




type BulkUpdateAccessMethods200Response struct {

	// Array of updated DRS objects
	Objects []DrsObject `json:"objects"`
}

// AssertBulkUpdateAccessMethods200ResponseRequired checks if the required fields are not zero-ed
func AssertBulkUpdateAccessMethods200ResponseRequired(obj BulkUpdateAccessMethods200Response) error {
	elements := map[string]interface{}{
		"objects": obj.Objects,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Objects {
		if err := AssertDrsObjectRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertBulkUpdateAccessMethods200ResponseConstraints checks if the values respects the defined constraints
func AssertBulkUpdateAccessMethods200ResponseConstraints(obj BulkUpdateAccessMethods200Response) error {
	for _, el := range obj.Objects {
		if err := AssertDrsObjectConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
