// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs

// BulkObjectIdNoPassport - The object that contains the DRS object IDs array
type BulkObjectIdNoPassport struct {

	// An array of ObjectIDs.
	BulkObjectIds []string `json:"bulk_object_ids,omitempty"`
}

// AssertBulkObjectIdNoPassportRequired checks if the required fields are not zero-ed
func AssertBulkObjectIdNoPassportRequired(obj BulkObjectIdNoPassport) error {
	return nil
}

// AssertBulkObjectIdNoPassportConstraints checks if the values respects the defined constraints
func AssertBulkObjectIdNoPassportConstraints(obj BulkObjectIdNoPassport) error {
	return nil
}
