// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.5.0
 * Contact: ga4gh-cloud@ga4gh.org
 */

package drs




type AccessMethodAccessUrl struct {

	// A fully resolvable URL that can be used to fetch the actual object bytes.
	Url string `json:"url"`

	// An optional list of headers to include in the HTTP request to `url`. These headers can be used to provide auth tokens required to fetch the object bytes.
	Headers []string `json:"headers,omitempty"`
}

// AssertAccessMethodAccessUrlRequired checks if the required fields are not zero-ed
func AssertAccessMethodAccessUrlRequired(obj AccessMethodAccessUrl) error {
	elements := map[string]interface{}{
		"url": obj.Url,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAccessMethodAccessUrlConstraints checks if the values respects the defined constraints
func AssertAccessMethodAccessUrlConstraints(obj AccessMethodAccessUrl) error {
	return nil
}
