/*
Bucket Credential API (DRS Server)

Bucket credential and scope management API used by drs-server compatible clients. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bucketapi

import (
	"encoding/json"
)

// checks if the BucketMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BucketMetadata{}

// BucketMetadata struct for BucketMetadata
type BucketMetadata struct {
	EndpointUrl *string `json:"endpoint_url,omitempty"`
	Region *string `json:"region,omitempty"`
	Programs []string `json:"programs,omitempty"`
}

// NewBucketMetadata instantiates a new BucketMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBucketMetadata() *BucketMetadata {
	this := BucketMetadata{}
	return &this
}

// NewBucketMetadataWithDefaults instantiates a new BucketMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBucketMetadataWithDefaults() *BucketMetadata {
	this := BucketMetadata{}
	return &this
}

// GetEndpointUrl returns the EndpointUrl field value if set, zero value otherwise.
func (o *BucketMetadata) GetEndpointUrl() string {
	if o == nil || IsNil(o.EndpointUrl) {
		var ret string
		return ret
	}
	return *o.EndpointUrl
}

// GetEndpointUrlOk returns a tuple with the EndpointUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketMetadata) GetEndpointUrlOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointUrl) {
		return nil, false
	}
	return o.EndpointUrl, true
}

// HasEndpointUrl returns a boolean if a field has been set.
func (o *BucketMetadata) HasEndpointUrl() bool {
	if o != nil && !IsNil(o.EndpointUrl) {
		return true
	}

	return false
}

// SetEndpointUrl gets a reference to the given string and assigns it to the EndpointUrl field.
func (o *BucketMetadata) SetEndpointUrl(v string) {
	o.EndpointUrl = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *BucketMetadata) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketMetadata) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *BucketMetadata) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *BucketMetadata) SetRegion(v string) {
	o.Region = &v
}

// GetPrograms returns the Programs field value if set, zero value otherwise.
func (o *BucketMetadata) GetPrograms() []string {
	if o == nil || IsNil(o.Programs) {
		var ret []string
		return ret
	}
	return o.Programs
}

// GetProgramsOk returns a tuple with the Programs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketMetadata) GetProgramsOk() ([]string, bool) {
	if o == nil || IsNil(o.Programs) {
		return nil, false
	}
	return o.Programs, true
}

// HasPrograms returns a boolean if a field has been set.
func (o *BucketMetadata) HasPrograms() bool {
	if o != nil && !IsNil(o.Programs) {
		return true
	}

	return false
}

// SetPrograms gets a reference to the given []string and assigns it to the Programs field.
func (o *BucketMetadata) SetPrograms(v []string) {
	o.Programs = v
}

func (o BucketMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BucketMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndpointUrl) {
		toSerialize["endpoint_url"] = o.EndpointUrl
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Programs) {
		toSerialize["programs"] = o.Programs
	}
	return toSerialize, nil
}

type NullableBucketMetadata struct {
	value *BucketMetadata
	isSet bool
}

func (v NullableBucketMetadata) Get() *BucketMetadata {
	return v.value
}

func (v *NullableBucketMetadata) Set(val *BucketMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableBucketMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableBucketMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBucketMetadata(val *BucketMetadata) *NullableBucketMetadata {
	return &NullableBucketMetadata{value: val, isSet: true}
}

func (v NullableBucketMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBucketMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


