/*
Bucket Credential API (DRS Server)

Bucket credential and scope management API used by drs-server compatible clients. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bucketapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddBucketScopeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddBucketScopeRequest{}

// AddBucketScopeRequest struct for AddBucketScopeRequest
type AddBucketScopeRequest struct {
	Organization string `json:"organization"`
	ProjectId string `json:"project_id"`
	// Optional s3://bucket/prefix path override
	Path *string `json:"path,omitempty"`
}

type _AddBucketScopeRequest AddBucketScopeRequest

// NewAddBucketScopeRequest instantiates a new AddBucketScopeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddBucketScopeRequest(organization string, projectId string) *AddBucketScopeRequest {
	this := AddBucketScopeRequest{}
	this.Organization = organization
	this.ProjectId = projectId
	return &this
}

// NewAddBucketScopeRequestWithDefaults instantiates a new AddBucketScopeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddBucketScopeRequestWithDefaults() *AddBucketScopeRequest {
	this := AddBucketScopeRequest{}
	return &this
}

// GetOrganization returns the Organization field value
func (o *AddBucketScopeRequest) GetOrganization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *AddBucketScopeRequest) GetOrganizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *AddBucketScopeRequest) SetOrganization(v string) {
	o.Organization = v
}

// GetProjectId returns the ProjectId field value
func (o *AddBucketScopeRequest) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *AddBucketScopeRequest) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *AddBucketScopeRequest) SetProjectId(v string) {
	o.ProjectId = v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *AddBucketScopeRequest) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddBucketScopeRequest) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *AddBucketScopeRequest) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *AddBucketScopeRequest) SetPath(v string) {
	o.Path = &v
}

func (o AddBucketScopeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddBucketScopeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization"] = o.Organization
	toSerialize["project_id"] = o.ProjectId
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	return toSerialize, nil
}

func (o *AddBucketScopeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organization",
		"project_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddBucketScopeRequest := _AddBucketScopeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddBucketScopeRequest)

	if err != nil {
		return err
	}

	*o = AddBucketScopeRequest(varAddBucketScopeRequest)

	return err
}

type NullableAddBucketScopeRequest struct {
	value *AddBucketScopeRequest
	isSet bool
}

func (v NullableAddBucketScopeRequest) Get() *AddBucketScopeRequest {
	return v.value
}

func (v *NullableAddBucketScopeRequest) Set(val *AddBucketScopeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddBucketScopeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddBucketScopeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddBucketScopeRequest(val *AddBucketScopeRequest) *NullableAddBucketScopeRequest {
	return &NullableAddBucketScopeRequest{value: val, isSet: true}
}

func (v NullableAddBucketScopeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddBucketScopeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


