/*
Bucket Credential API (DRS Server)

Bucket credential and scope management API used by drs-server compatible clients.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bucketapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BucketsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BucketsResponse{}

// BucketsResponse struct for BucketsResponse
type BucketsResponse struct {
	S3BUCKETS map[string]BucketMetadata `json:"S3_BUCKETS"`
}

type _BucketsResponse BucketsResponse

// NewBucketsResponse instantiates a new BucketsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBucketsResponse(s3BUCKETS map[string]BucketMetadata) *BucketsResponse {
	this := BucketsResponse{}
	this.S3BUCKETS = s3BUCKETS
	return &this
}

// NewBucketsResponseWithDefaults instantiates a new BucketsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBucketsResponseWithDefaults() *BucketsResponse {
	this := BucketsResponse{}
	return &this
}

// GetS3BUCKETS returns the S3BUCKETS field value
func (o *BucketsResponse) GetS3BUCKETS() map[string]BucketMetadata {
	if o == nil {
		var ret map[string]BucketMetadata
		return ret
	}

	return o.S3BUCKETS
}

// GetS3BUCKETSOk returns a tuple with the S3BUCKETS field value
// and a boolean to check if the value has been set.
func (o *BucketsResponse) GetS3BUCKETSOk() (*map[string]BucketMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.S3BUCKETS, true
}

// SetS3BUCKETS sets field value
func (o *BucketsResponse) SetS3BUCKETS(v map[string]BucketMetadata) {
	o.S3BUCKETS = v
}

func (o BucketsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BucketsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["S3_BUCKETS"] = o.S3BUCKETS
	return toSerialize, nil
}

func (o *BucketsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"S3_BUCKETS",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBucketsResponse := _BucketsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBucketsResponse)

	if err != nil {
		return err
	}

	*o = BucketsResponse(varBucketsResponse)

	return err
}

type NullableBucketsResponse struct {
	value *BucketsResponse
	isSet bool
}

func (v NullableBucketsResponse) Get() *BucketsResponse {
	return v.value
}

func (v *NullableBucketsResponse) Set(val *BucketsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBucketsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBucketsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBucketsResponse(val *BucketsResponse) *NullableBucketsResponse {
	return &NullableBucketsResponse{value: val, isSet: true}
}

func (v NullableBucketsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBucketsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
