/*
Git LFS API (DRS Server)

OpenAPI model spec for Git LFS-compatible endpoints implemented by drs-server. This includes standard Batch and Verify payload models plus drs-server extensions used for upload proxy and metadata staging.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lfsapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchResponse{}

// BatchResponse struct for BatchResponse
type BatchResponse struct {
	Transfer *string               `json:"transfer,omitempty"`
	Objects  []BatchResponseObject `json:"objects"`
	HashAlgo *string               `json:"hash_algo,omitempty"`
}

type _BatchResponse BatchResponse

// NewBatchResponse instantiates a new BatchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchResponse(objects []BatchResponseObject) *BatchResponse {
	this := BatchResponse{}
	this.Objects = objects
	var hashAlgo string = "sha256"
	this.HashAlgo = &hashAlgo
	return &this
}

// NewBatchResponseWithDefaults instantiates a new BatchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchResponseWithDefaults() *BatchResponse {
	this := BatchResponse{}
	var hashAlgo string = "sha256"
	this.HashAlgo = &hashAlgo
	return &this
}

// GetTransfer returns the Transfer field value if set, zero value otherwise.
func (o *BatchResponse) GetTransfer() string {
	if o == nil || IsNil(o.Transfer) {
		var ret string
		return ret
	}
	return *o.Transfer
}

// GetTransferOk returns a tuple with the Transfer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchResponse) GetTransferOk() (*string, bool) {
	if o == nil || IsNil(o.Transfer) {
		return nil, false
	}
	return o.Transfer, true
}

// HasTransfer returns a boolean if a field has been set.
func (o *BatchResponse) HasTransfer() bool {
	if o != nil && !IsNil(o.Transfer) {
		return true
	}

	return false
}

// SetTransfer gets a reference to the given string and assigns it to the Transfer field.
func (o *BatchResponse) SetTransfer(v string) {
	o.Transfer = &v
}

// GetObjects returns the Objects field value
func (o *BatchResponse) GetObjects() []BatchResponseObject {
	if o == nil {
		var ret []BatchResponseObject
		return ret
	}

	return o.Objects
}

// GetObjectsOk returns a tuple with the Objects field value
// and a boolean to check if the value has been set.
func (o *BatchResponse) GetObjectsOk() ([]BatchResponseObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Objects, true
}

// SetObjects sets field value
func (o *BatchResponse) SetObjects(v []BatchResponseObject) {
	o.Objects = v
}

// GetHashAlgo returns the HashAlgo field value if set, zero value otherwise.
func (o *BatchResponse) GetHashAlgo() string {
	if o == nil || IsNil(o.HashAlgo) {
		var ret string
		return ret
	}
	return *o.HashAlgo
}

// GetHashAlgoOk returns a tuple with the HashAlgo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchResponse) GetHashAlgoOk() (*string, bool) {
	if o == nil || IsNil(o.HashAlgo) {
		return nil, false
	}
	return o.HashAlgo, true
}

// HasHashAlgo returns a boolean if a field has been set.
func (o *BatchResponse) HasHashAlgo() bool {
	if o != nil && !IsNil(o.HashAlgo) {
		return true
	}

	return false
}

// SetHashAlgo gets a reference to the given string and assigns it to the HashAlgo field.
func (o *BatchResponse) SetHashAlgo(v string) {
	o.HashAlgo = &v
}

func (o BatchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Transfer) {
		toSerialize["transfer"] = o.Transfer
	}
	toSerialize["objects"] = o.Objects
	if !IsNil(o.HashAlgo) {
		toSerialize["hash_algo"] = o.HashAlgo
	}
	return toSerialize, nil
}

func (o *BatchResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objects",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchResponse := _BatchResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchResponse)

	if err != nil {
		return err
	}

	*o = BatchResponse(varBatchResponse)

	return err
}

type NullableBatchResponse struct {
	value *BatchResponse
	isSet bool
}

func (v NullableBatchResponse) Get() *BatchResponse {
	return v.value
}

func (v *NullableBatchResponse) Set(val *BatchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchResponse(val *BatchResponse) *NullableBatchResponse {
	return &NullableBatchResponse{value: val, isSet: true}
}

func (v NullableBatchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
