/*
Git LFS API (DRS Server)

OpenAPI model spec for Git LFS-compatible endpoints implemented by drs-server. This includes standard Batch and Verify payload models plus drs-server extensions used for upload proxy and metadata staging.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lfsapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyRequest{}

// VerifyRequest struct for VerifyRequest
type VerifyRequest struct {
	Oid  string `json:"oid"`
	Size int64  `json:"size"`
}

type _VerifyRequest VerifyRequest

// NewVerifyRequest instantiates a new VerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyRequest(oid string, size int64) *VerifyRequest {
	this := VerifyRequest{}
	this.Oid = oid
	this.Size = size
	return &this
}

// NewVerifyRequestWithDefaults instantiates a new VerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyRequestWithDefaults() *VerifyRequest {
	this := VerifyRequest{}
	return &this
}

// GetOid returns the Oid field value
func (o *VerifyRequest) GetOid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Oid
}

// GetOidOk returns a tuple with the Oid field value
// and a boolean to check if the value has been set.
func (o *VerifyRequest) GetOidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Oid, true
}

// SetOid sets field value
func (o *VerifyRequest) SetOid(v string) {
	o.Oid = v
}

// GetSize returns the Size field value
func (o *VerifyRequest) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *VerifyRequest) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *VerifyRequest) SetSize(v int64) {
	o.Size = v
}

func (o VerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["oid"] = o.Oid
	toSerialize["size"] = o.Size
	return toSerialize, nil
}

func (o *VerifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"oid",
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyRequest := _VerifyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyRequest)

	if err != nil {
		return err
	}

	*o = VerifyRequest(varVerifyRequest)

	return err
}

type NullableVerifyRequest struct {
	value *VerifyRequest
	isSet bool
}

func (v NullableVerifyRequest) Get() *VerifyRequest {
	return v.value
}

func (v *NullableVerifyRequest) Set(val *VerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyRequest(val *VerifyRequest) *NullableVerifyRequest {
	return &NullableVerifyRequest{value: val, isSet: true}
}

func (v NullableVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
