/*
Git LFS API (DRS Server)

OpenAPI model spec for Git LFS-compatible endpoints implemented by drs-server. This includes standard Batch and Verify payload models plus drs-server extensions used for upload proxy and metadata staging. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lfsapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LFSErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LFSErrorResponse{}

// LFSErrorResponse struct for LFSErrorResponse
type LFSErrorResponse struct {
	Message string `json:"message"`
	RequestId *string `json:"request_id,omitempty"`
	DocumentationUrl *string `json:"documentation_url,omitempty"`
}

type _LFSErrorResponse LFSErrorResponse

// NewLFSErrorResponse instantiates a new LFSErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLFSErrorResponse(message string) *LFSErrorResponse {
	this := LFSErrorResponse{}
	this.Message = message
	return &this
}

// NewLFSErrorResponseWithDefaults instantiates a new LFSErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLFSErrorResponseWithDefaults() *LFSErrorResponse {
	this := LFSErrorResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *LFSErrorResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *LFSErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *LFSErrorResponse) SetMessage(v string) {
	o.Message = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *LFSErrorResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LFSErrorResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *LFSErrorResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *LFSErrorResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetDocumentationUrl returns the DocumentationUrl field value if set, zero value otherwise.
func (o *LFSErrorResponse) GetDocumentationUrl() string {
	if o == nil || IsNil(o.DocumentationUrl) {
		var ret string
		return ret
	}
	return *o.DocumentationUrl
}

// GetDocumentationUrlOk returns a tuple with the DocumentationUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LFSErrorResponse) GetDocumentationUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentationUrl) {
		return nil, false
	}
	return o.DocumentationUrl, true
}

// HasDocumentationUrl returns a boolean if a field has been set.
func (o *LFSErrorResponse) HasDocumentationUrl() bool {
	if o != nil && !IsNil(o.DocumentationUrl) {
		return true
	}

	return false
}

// SetDocumentationUrl gets a reference to the given string and assigns it to the DocumentationUrl field.
func (o *LFSErrorResponse) SetDocumentationUrl(v string) {
	o.DocumentationUrl = &v
}

func (o LFSErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LFSErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	if !IsNil(o.DocumentationUrl) {
		toSerialize["documentation_url"] = o.DocumentationUrl
	}
	return toSerialize, nil
}

func (o *LFSErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLFSErrorResponse := _LFSErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLFSErrorResponse)

	if err != nil {
		return err
	}

	*o = LFSErrorResponse(varLFSErrorResponse)

	return err
}

type NullableLFSErrorResponse struct {
	value *LFSErrorResponse
	isSet bool
}

func (v NullableLFSErrorResponse) Get() *LFSErrorResponse {
	return v.value
}

func (v *NullableLFSErrorResponse) Set(val *LFSErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLFSErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLFSErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLFSErrorResponse(val *LFSErrorResponse) *NullableLFSErrorResponse {
	return &NullableLFSErrorResponse{value: val, isSet: true}
}

func (v NullableLFSErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLFSErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


