/*
Git LFS API (DRS Server)

OpenAPI model spec for Git LFS-compatible endpoints implemented by drs-server. This includes standard Batch and Verify payload models plus drs-server extensions used for upload proxy and metadata staging. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lfsapi

import (
	"encoding/json"
)

// checks if the AccessMethodAccessUrl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessMethodAccessUrl{}

// AccessMethodAccessUrl struct for AccessMethodAccessUrl
type AccessMethodAccessUrl struct {
	Url *string `json:"url,omitempty"`
}

// NewAccessMethodAccessUrl instantiates a new AccessMethodAccessUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessMethodAccessUrl() *AccessMethodAccessUrl {
	this := AccessMethodAccessUrl{}
	return &this
}

// NewAccessMethodAccessUrlWithDefaults instantiates a new AccessMethodAccessUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessMethodAccessUrlWithDefaults() *AccessMethodAccessUrl {
	this := AccessMethodAccessUrl{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AccessMethodAccessUrl) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessMethodAccessUrl) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AccessMethodAccessUrl) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AccessMethodAccessUrl) SetUrl(v string) {
	o.Url = &v
}

func (o AccessMethodAccessUrl) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessMethodAccessUrl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableAccessMethodAccessUrl struct {
	value *AccessMethodAccessUrl
	isSet bool
}

func (v NullableAccessMethodAccessUrl) Get() *AccessMethodAccessUrl {
	return v.value
}

func (v *NullableAccessMethodAccessUrl) Set(val *AccessMethodAccessUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessMethodAccessUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessMethodAccessUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessMethodAccessUrl(val *AccessMethodAccessUrl) *NullableAccessMethodAccessUrl {
	return &NullableAccessMethodAccessUrl{value: val, isSet: true}
}

func (v NullableAccessMethodAccessUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessMethodAccessUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


