/*
Git LFS API (DRS Server)

OpenAPI model spec for Git LFS-compatible endpoints implemented by drs-server. This includes standard Batch and Verify payload models plus drs-server extensions used for upload proxy and metadata staging. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lfsapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Checksum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Checksum{}

// Checksum struct for Checksum
type Checksum struct {
	Type string `json:"type"`
	Checksum string `json:"checksum"`
}

type _Checksum Checksum

// NewChecksum instantiates a new Checksum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChecksum(type_ string, checksum string) *Checksum {
	this := Checksum{}
	this.Type = type_
	this.Checksum = checksum
	return &this
}

// NewChecksumWithDefaults instantiates a new Checksum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChecksumWithDefaults() *Checksum {
	this := Checksum{}
	return &this
}

// GetType returns the Type field value
func (o *Checksum) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Checksum) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Checksum) SetType(v string) {
	o.Type = v
}

// GetChecksum returns the Checksum field value
func (o *Checksum) GetChecksum() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Checksum
}

// GetChecksumOk returns a tuple with the Checksum field value
// and a boolean to check if the value has been set.
func (o *Checksum) GetChecksumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Checksum, true
}

// SetChecksum sets field value
func (o *Checksum) SetChecksum(v string) {
	o.Checksum = v
}

func (o Checksum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Checksum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["checksum"] = o.Checksum
	return toSerialize, nil
}

func (o *Checksum) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"checksum",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChecksum := _Checksum{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChecksum)

	if err != nil {
		return err
	}

	*o = Checksum(varChecksum)

	return err
}

type NullableChecksum struct {
	value *Checksum
	isSet bool
}

func (v NullableChecksum) Get() *Checksum {
	return v.value
}

func (v *NullableChecksum) Set(val *Checksum) {
	v.value = val
	v.isSet = true
}

func (v NullableChecksum) IsSet() bool {
	return v.isSet
}

func (v *NullableChecksum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChecksum(val *Checksum) *NullableChecksum {
	return &NullableChecksum{value: val, isSet: true}
}

func (v NullableChecksum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChecksum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


