package drs

// Compatibility aliases for generator-emitted service-info field names.
type N200ServiceInfoDrsControlledAccessClaimFormat = DrsServiceDrsControlledAccessClaimFormat
type N200ServiceInfoDrsControlledAccessDefault = DrsServiceDrsControlledAccessDefault
type N200ServiceInfoDrsSupportedUploadMethodTypes = DrsServiceDrsSupportedUploadMethodTypes
type N200ServiceInfoTypeArtifact = DrsServiceTypeArtifact
