// Package lfsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package lfsapi

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BatchRequestOperation.
const (
	Download BatchRequestOperation = "download"
	Upload   BatchRequestOperation = "upload"
)

// AccessMethod defines model for AccessMethod.
type AccessMethod struct {
	AccessId       *string                     `json:"access_id,omitempty"`
	AccessUrl      *AccessMethodAccessUrl      `json:"access_url,omitempty"`
	Authorizations *AccessMethodAuthorizations `json:"authorizations,omitempty"`
	Region         *string                     `json:"region,omitempty"`
	Type           *string                     `json:"type,omitempty"`
}

// AccessMethodAccessUrl defines model for AccessMethodAccessUrl.
type AccessMethodAccessUrl struct {
	Url *string `json:"url,omitempty"`
}

// AccessMethodAuthorizations defines model for AccessMethodAuthorizations.
type AccessMethodAuthorizations struct {
	BearerAuthIssuers *[]string `json:"bearer_auth_issuers,omitempty"`
}

// Action defines model for Action.
type Action struct {
	// ExpiresAt RFC3339 timestamp
	ExpiresAt *time.Time         `json:"expires_at,omitempty"`
	ExpiresIn *int32             `json:"expires_in,omitempty"`
	Header    *map[string]string `json:"header,omitempty"`
	Href      string             `json:"href"`
}

// BatchActions defines model for BatchActions.
type BatchActions struct {
	Download *Action `json:"download,omitempty"`
	Upload   *Action `json:"upload,omitempty"`
	Verify   *Action `json:"verify,omitempty"`
}

// BatchRequest defines model for BatchRequest.
type BatchRequest struct {
	HashAlgo  *string               `json:"hash_algo,omitempty"`
	Objects   []BatchRequestObject  `json:"objects"`
	Operation BatchRequestOperation `json:"operation"`
	Ref       *RefSpec              `json:"ref,omitempty"`
	Transfers *[]string             `json:"transfers,omitempty"`
}

// BatchRequestOperation defines model for BatchRequest.Operation.
type BatchRequestOperation string

// BatchRequestObject defines model for BatchRequestObject.
type BatchRequestObject struct {
	Oid  string `json:"oid"`
	Size int64  `json:"size"`
}

// BatchResponse defines model for BatchResponse.
type BatchResponse struct {
	HashAlgo *string               `json:"hash_algo,omitempty"`
	Objects  []BatchResponseObject `json:"objects"`
	Transfer *string               `json:"transfer,omitempty"`
}

// BatchResponseObject defines model for BatchResponseObject.
type BatchResponseObject struct {
	Actions       *BatchActions `json:"actions,omitempty"`
	Authenticated *bool         `json:"authenticated,omitempty"`
	Error         *ObjectError  `json:"error,omitempty"`
	Oid           string        `json:"oid"`
	Size          int64         `json:"size"`
}

// Checksum defines model for Checksum.
type Checksum struct {
	Checksum string `json:"checksum"`
	Type     string `json:"type"`
}

// DrsObjectCandidate defines model for DrsObjectCandidate.
type DrsObjectCandidate struct {
	AccessMethods *[]AccessMethod `json:"access_methods,omitempty"`
	Aliases       *[]string       `json:"aliases,omitempty"`
	Checksums     *[]Checksum     `json:"checksums,omitempty"`
	Description   *string         `json:"description,omitempty"`
	Id            *string         `json:"id,omitempty"`
	MimeType      *string         `json:"mime_type,omitempty"`
	Name          *string         `json:"name,omitempty"`
	Size          *int64          `json:"size,omitempty"`
}

// LFSErrorResponse defines model for LFSErrorResponse.
type LFSErrorResponse struct {
	DocumentationUrl *string `json:"documentation_url,omitempty"`
	Message          string  `json:"message"`
	RequestId        *string `json:"request_id,omitempty"`
}

// MetadataSubmitRequest defines model for MetadataSubmitRequest.
type MetadataSubmitRequest struct {
	Candidates []DrsObjectCandidate `json:"candidates"`
	TtlSeconds *int64               `json:"ttl_seconds,omitempty"`
}

// MetadataSubmitResponse defines model for MetadataSubmitResponse.
type MetadataSubmitResponse struct {
	Staged int32 `json:"staged"`
}

// ObjectError defines model for ObjectError.
type ObjectError struct {
	// Code Object-level error code (commonly HTTP-like status code)
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// RefSpec defines model for RefSpec.
type RefSpec struct {
	// Name Fully-qualified server refspec
	Name *string `json:"name,omitempty"`
}

// VerifyRequest defines model for VerifyRequest.
type VerifyRequest struct {
	Oid  string `json:"oid"`
	Size int64  `json:"size"`
}

// LfsBatchApplicationVndGitLfsPlusJSONRequestBody defines body for LfsBatch for application/vnd.git-lfs+json ContentType.
type LfsBatchApplicationVndGitLfsPlusJSONRequestBody = BatchRequest

// LfsStageMetadataJSONRequestBody defines body for LfsStageMetadata for application/json ContentType.
type LfsStageMetadataJSONRequestBody = MetadataSubmitRequest

// LfsStageMetadataApplicationVndGitLfsPlusJSONRequestBody defines body for LfsStageMetadata for application/vnd.git-lfs+json ContentType.
type LfsStageMetadataApplicationVndGitLfsPlusJSONRequestBody = MetadataSubmitRequest

// LfsVerifyApplicationVndGitLfsPlusJSONRequestBody defines body for LfsVerify for application/vnd.git-lfs+json ContentType.
type LfsVerifyApplicationVndGitLfsPlusJSONRequestBody = VerifyRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Git LFS Batch API
	// (POST /info/lfs/objects/batch)
	LfsBatch(c fiber.Ctx) error
	// Stage metadata for deferred object registration (drs-server extension)
	// (POST /info/lfs/objects/metadata)
	LfsStageMetadata(c fiber.Ctx) error
	// Upload object bytes via drs-server upload proxy (drs-server extension)
	// (PUT /info/lfs/objects/{oid})
	LfsUploadProxy(c fiber.Ctx, oid string) error
	// Git LFS Verify API
	// (POST /info/lfs/verify)
	LfsVerify(c fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// LfsBatch operation middleware
func (siw *ServerInterfaceWrapper) LfsBatch(c fiber.Ctx) error {

	return siw.Handler.LfsBatch(c)
}

// LfsStageMetadata operation middleware
func (siw *ServerInterfaceWrapper) LfsStageMetadata(c fiber.Ctx) error {

	return siw.Handler.LfsStageMetadata(c)
}

// LfsUploadProxy operation middleware
func (siw *ServerInterfaceWrapper) LfsUploadProxy(c fiber.Ctx) error {
	var err error

	// ------------- Path parameter "oid" -------------
	var oid string

	err = runtime.BindStyledParameterWithOptions("simple", "oid", c.Params("oid"), &oid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter oid: %w", err).Error())
	}

	return siw.Handler.LfsUploadProxy(c, oid)
}

// LfsVerify operation middleware
func (siw *ServerInterfaceWrapper) LfsVerify(c fiber.Ctx) error {

	return siw.Handler.LfsVerify(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/info/lfs/objects/batch", wrapper.LfsBatch)

	router.Post(options.BaseURL+"/info/lfs/objects/metadata", wrapper.LfsStageMetadata)

	router.Put(options.BaseURL+"/info/lfs/objects/:oid", wrapper.LfsUploadProxy)

	router.Post(options.BaseURL+"/info/lfs/verify", wrapper.LfsVerify)

}

type LfsBatchRequestObject struct {
	Body *LfsBatchApplicationVndGitLfsPlusJSONRequestBody
}

type LfsBatchResponseObject interface {
	VisitLfsBatchResponse(ctx fiber.Ctx) error
}

type LfsBatch200ApplicationVndGitLfsPlusJSONResponse BatchResponse

func (response LfsBatch200ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LfsBatch401ResponseHeaders struct {
	LFSAuthenticate string
}

type LfsBatch401ApplicationVndGitLfsPlusJSONResponse struct {
	Body    LFSErrorResponse
	Headers LfsBatch401ResponseHeaders
}

func (response LfsBatch401ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("LFS-Authenticate", fmt.Sprint(response.Headers.LFSAuthenticate))
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(401)

	return ctx.JSON(&response.Body)
}

type LfsBatch403ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch403ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type LfsBatch404ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch404ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type LfsBatch406ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch406ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(406)

	return ctx.JSON(&response)
}

type LfsBatch413ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch413ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(413)

	return ctx.JSON(&response)
}

type LfsBatch422ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch422ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type LfsBatch429ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch429ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(429)

	return ctx.JSON(&response)
}

type LfsBatch500ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch500ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type LfsBatch502ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch502ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type LfsBatch503ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch503ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(503)

	return ctx.JSON(&response)
}

type LfsBatch504ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch504ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(504)

	return ctx.JSON(&response)
}

type LfsBatch507ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch507ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(507)

	return ctx.JSON(&response)
}

type LfsBatch509ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsBatch509ApplicationVndGitLfsPlusJSONResponse) VisitLfsBatchResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(509)

	return ctx.JSON(&response)
}

type LfsStageMetadataRequestObject struct {
	JSONBody                         *LfsStageMetadataJSONRequestBody
	ApplicationVndGitLfsPlusJSONBody *LfsStageMetadataApplicationVndGitLfsPlusJSONRequestBody
}

type LfsStageMetadataResponseObject interface {
	VisitLfsStageMetadataResponse(ctx fiber.Ctx) error
}

type LfsStageMetadata200JSONResponse MetadataSubmitResponse

func (response LfsStageMetadata200JSONResponse) VisitLfsStageMetadataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LfsStageMetadata200ApplicationVndGitLfsPlusJSONResponse MetadataSubmitResponse

func (response LfsStageMetadata200ApplicationVndGitLfsPlusJSONResponse) VisitLfsStageMetadataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LfsStageMetadata400JSONResponse LFSErrorResponse

func (response LfsStageMetadata400JSONResponse) VisitLfsStageMetadataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type LfsStageMetadata401ResponseHeaders struct {
	LFSAuthenticate string
}

type LfsStageMetadata401JSONResponse struct {
	Body    LFSErrorResponse
	Headers LfsStageMetadata401ResponseHeaders
}

func (response LfsStageMetadata401JSONResponse) VisitLfsStageMetadataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("LFS-Authenticate", fmt.Sprint(response.Headers.LFSAuthenticate))
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response.Body)
}

type LfsStageMetadata403JSONResponse LFSErrorResponse

func (response LfsStageMetadata403JSONResponse) VisitLfsStageMetadataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type LfsStageMetadata500JSONResponse LFSErrorResponse

func (response LfsStageMetadata500JSONResponse) VisitLfsStageMetadataResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type LfsUploadProxyRequestObject struct {
	Oid  string `json:"oid"`
	Body io.Reader
}

type LfsUploadProxyResponseObject interface {
	VisitLfsUploadProxyResponse(ctx fiber.Ctx) error
}

type LfsUploadProxy200Response struct {
}

func (response LfsUploadProxy200Response) VisitLfsUploadProxyResponse(ctx fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type LfsUploadProxy400TextResponse string

func (response LfsUploadProxy400TextResponse) VisitLfsUploadProxyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/plain")
	ctx.Status(400)

	_, err := ctx.WriteString(string(response))
	return err
}

type LfsUploadProxy401TextResponse string

func (response LfsUploadProxy401TextResponse) VisitLfsUploadProxyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/plain")
	ctx.Status(401)

	_, err := ctx.WriteString(string(response))
	return err
}

type LfsUploadProxy403TextResponse string

func (response LfsUploadProxy403TextResponse) VisitLfsUploadProxyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/plain")
	ctx.Status(403)

	_, err := ctx.WriteString(string(response))
	return err
}

type LfsUploadProxy500TextResponse string

func (response LfsUploadProxy500TextResponse) VisitLfsUploadProxyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/plain")
	ctx.Status(500)

	_, err := ctx.WriteString(string(response))
	return err
}

type LfsUploadProxy502TextResponse string

func (response LfsUploadProxy502TextResponse) VisitLfsUploadProxyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/plain")
	ctx.Status(502)

	_, err := ctx.WriteString(string(response))
	return err
}

type LfsUploadProxy507TextResponse string

func (response LfsUploadProxy507TextResponse) VisitLfsUploadProxyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "text/plain")
	ctx.Status(507)

	_, err := ctx.WriteString(string(response))
	return err
}

type LfsVerifyRequestObject struct {
	Body *LfsVerifyApplicationVndGitLfsPlusJSONRequestBody
}

type LfsVerifyResponseObject interface {
	VisitLfsVerifyResponse(ctx fiber.Ctx) error
}

type LfsVerify200Response struct {
}

func (response LfsVerify200Response) VisitLfsVerifyResponse(ctx fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type LfsVerify400ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsVerify400ApplicationVndGitLfsPlusJSONResponse) VisitLfsVerifyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type LfsVerify401ResponseHeaders struct {
	LFSAuthenticate string
}

type LfsVerify401ApplicationVndGitLfsPlusJSONResponse struct {
	Body    LFSErrorResponse
	Headers LfsVerify401ResponseHeaders
}

func (response LfsVerify401ApplicationVndGitLfsPlusJSONResponse) VisitLfsVerifyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("LFS-Authenticate", fmt.Sprint(response.Headers.LFSAuthenticate))
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(401)

	return ctx.JSON(&response.Body)
}

type LfsVerify403ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsVerify403ApplicationVndGitLfsPlusJSONResponse) VisitLfsVerifyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type LfsVerify404ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsVerify404ApplicationVndGitLfsPlusJSONResponse) VisitLfsVerifyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type LfsVerify500ApplicationVndGitLfsPlusJSONResponse LFSErrorResponse

func (response LfsVerify500ApplicationVndGitLfsPlusJSONResponse) VisitLfsVerifyResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/vnd.git-lfs+json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Git LFS Batch API
	// (POST /info/lfs/objects/batch)
	LfsBatch(ctx context.Context, request LfsBatchRequestObject) (LfsBatchResponseObject, error)
	// Stage metadata for deferred object registration (drs-server extension)
	// (POST /info/lfs/objects/metadata)
	LfsStageMetadata(ctx context.Context, request LfsStageMetadataRequestObject) (LfsStageMetadataResponseObject, error)
	// Upload object bytes via drs-server upload proxy (drs-server extension)
	// (PUT /info/lfs/objects/{oid})
	LfsUploadProxy(ctx context.Context, request LfsUploadProxyRequestObject) (LfsUploadProxyResponseObject, error)
	// Git LFS Verify API
	// (POST /info/lfs/verify)
	LfsVerify(ctx context.Context, request LfsVerifyRequestObject) (LfsVerifyResponseObject, error)
}

type StrictHandlerFunc func(ctx fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// LfsBatch operation middleware
func (sh *strictHandler) LfsBatch(ctx fiber.Ctx) error {
	var request LfsBatchRequestObject

	var body LfsBatchApplicationVndGitLfsPlusJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.LfsBatch(ctx.Context(), request.(LfsBatchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LfsBatch")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LfsBatchResponseObject); ok {
		if err := validResponse.VisitLfsBatchResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LfsStageMetadata operation middleware
func (sh *strictHandler) LfsStageMetadata(ctx fiber.Ctx) error {
	var request LfsStageMetadataRequestObject

	if strings.HasPrefix(string(ctx.Request().Header.ContentType()), "application/json") {

		var body LfsStageMetadataJSONRequestBody
		if err := ctx.Bind().Body(&body); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
		request.JSONBody = &body

	}
	if strings.HasPrefix(string(ctx.Request().Header.ContentType()), "application/vnd.git-lfs+json") {

		var body LfsStageMetadataApplicationVndGitLfsPlusJSONRequestBody
		if err := ctx.Bind().Body(&body); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
		request.ApplicationVndGitLfsPlusJSONBody = &body

	}

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.LfsStageMetadata(ctx.Context(), request.(LfsStageMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LfsStageMetadata")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LfsStageMetadataResponseObject); ok {
		if err := validResponse.VisitLfsStageMetadataResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LfsUploadProxy operation middleware
func (sh *strictHandler) LfsUploadProxy(ctx fiber.Ctx, oid string) error {
	var request LfsUploadProxyRequestObject

	request.Oid = oid

	request.Body = bytes.NewReader(ctx.Request().Body())

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.LfsUploadProxy(ctx.Context(), request.(LfsUploadProxyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LfsUploadProxy")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LfsUploadProxyResponseObject); ok {
		if err := validResponse.VisitLfsUploadProxyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LfsVerify operation middleware
func (sh *strictHandler) LfsVerify(ctx fiber.Ctx) error {
	var request LfsVerifyRequestObject

	var body LfsVerifyApplicationVndGitLfsPlusJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.LfsVerify(ctx.Context(), request.(LfsVerifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LfsVerify")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LfsVerifyResponseObject); ok {
		if err := validResponse.VisitLfsVerifyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
