/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
)

// checks if the ListRecordsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRecordsResponse{}

// ListRecordsResponse struct for ListRecordsResponse
type ListRecordsResponse struct {
	Records []IndexdRecordResponse `json:"records,omitempty"`
}

// NewListRecordsResponse instantiates a new ListRecordsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRecordsResponse() *ListRecordsResponse {
	this := ListRecordsResponse{}
	return &this
}

// NewListRecordsResponseWithDefaults instantiates a new ListRecordsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRecordsResponseWithDefaults() *ListRecordsResponse {
	this := ListRecordsResponse{}
	return &this
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *ListRecordsResponse) GetRecords() []IndexdRecordResponse {
	if o == nil || IsNil(o.Records) {
		var ret []IndexdRecordResponse
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRecordsResponse) GetRecordsOk() ([]IndexdRecordResponse, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *ListRecordsResponse) HasRecords() bool {
	if o != nil && !IsNil(o.Records) {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []IndexdRecordResponse and assigns it to the Records field.
func (o *ListRecordsResponse) SetRecords(v []IndexdRecordResponse) {
	o.Records = v
}

func (o ListRecordsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRecordsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Records) {
		toSerialize["records"] = o.Records
	}
	return toSerialize, nil
}

type NullableListRecordsResponse struct {
	value *ListRecordsResponse
	isSet bool
}

func (v NullableListRecordsResponse) Get() *ListRecordsResponse {
	return v.value
}

func (v *NullableListRecordsResponse) Set(val *ListRecordsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListRecordsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListRecordsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRecordsResponse(val *ListRecordsResponse) *NullableListRecordsResponse {
	return &NullableListRecordsResponse{value: val, isSet: true}
}

func (v NullableListRecordsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRecordsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


