/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FenceMultipartPart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FenceMultipartPart{}

// FenceMultipartPart struct for FenceMultipartPart
type FenceMultipartPart struct {
	PartNumber int32 `json:"PartNumber"`
	ETag string `json:"ETag"`
}

type _FenceMultipartPart FenceMultipartPart

// NewFenceMultipartPart instantiates a new FenceMultipartPart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFenceMultipartPart(partNumber int32, eTag string) *FenceMultipartPart {
	this := FenceMultipartPart{}
	this.PartNumber = partNumber
	this.ETag = eTag
	return &this
}

// NewFenceMultipartPartWithDefaults instantiates a new FenceMultipartPart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFenceMultipartPartWithDefaults() *FenceMultipartPart {
	this := FenceMultipartPart{}
	return &this
}

// GetPartNumber returns the PartNumber field value
func (o *FenceMultipartPart) GetPartNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value
// and a boolean to check if the value has been set.
func (o *FenceMultipartPart) GetPartNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartNumber, true
}

// SetPartNumber sets field value
func (o *FenceMultipartPart) SetPartNumber(v int32) {
	o.PartNumber = v
}

// GetETag returns the ETag field value
func (o *FenceMultipartPart) GetETag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ETag
}

// GetETagOk returns a tuple with the ETag field value
// and a boolean to check if the value has been set.
func (o *FenceMultipartPart) GetETagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ETag, true
}

// SetETag sets field value
func (o *FenceMultipartPart) SetETag(v string) {
	o.ETag = v
}

func (o FenceMultipartPart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FenceMultipartPart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["PartNumber"] = o.PartNumber
	toSerialize["ETag"] = o.ETag
	return toSerialize, nil
}

func (o *FenceMultipartPart) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"PartNumber",
		"ETag",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFenceMultipartPart := _FenceMultipartPart{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFenceMultipartPart)

	if err != nil {
		return err
	}

	*o = FenceMultipartPart(varFenceMultipartPart)

	return err
}

type NullableFenceMultipartPart struct {
	value *FenceMultipartPart
	isSet bool
}

func (v NullableFenceMultipartPart) Get() *FenceMultipartPart {
	return v.value
}

func (v *NullableFenceMultipartPart) Set(val *FenceMultipartPart) {
	v.value = val
	v.isSet = true
}

func (v NullableFenceMultipartPart) IsSet() bool {
	return v.isSet
}

func (v *NullableFenceMultipartPart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFenceMultipartPart(val *FenceMultipartPart) *NullableFenceMultipartPart {
	return &NullableFenceMultipartPart{value: val, isSet: true}
}

func (v NullableFenceMultipartPart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFenceMultipartPart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


