/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
)

// checks if the InternalMultipartUploadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalMultipartUploadResponse{}

// InternalMultipartUploadResponse struct for InternalMultipartUploadResponse
type InternalMultipartUploadResponse struct {
	PresignedUrl *string `json:"presigned_url,omitempty"`
}

// NewInternalMultipartUploadResponse instantiates a new InternalMultipartUploadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalMultipartUploadResponse() *InternalMultipartUploadResponse {
	this := InternalMultipartUploadResponse{}
	return &this
}

// NewInternalMultipartUploadResponseWithDefaults instantiates a new InternalMultipartUploadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalMultipartUploadResponseWithDefaults() *InternalMultipartUploadResponse {
	this := InternalMultipartUploadResponse{}
	return &this
}

// GetPresignedUrl returns the PresignedUrl field value if set, zero value otherwise.
func (o *InternalMultipartUploadResponse) GetPresignedUrl() string {
	if o == nil || IsNil(o.PresignedUrl) {
		var ret string
		return ret
	}
	return *o.PresignedUrl
}

// GetPresignedUrlOk returns a tuple with the PresignedUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalMultipartUploadResponse) GetPresignedUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PresignedUrl) {
		return nil, false
	}
	return o.PresignedUrl, true
}

// HasPresignedUrl returns a boolean if a field has been set.
func (o *InternalMultipartUploadResponse) HasPresignedUrl() bool {
	if o != nil && !IsNil(o.PresignedUrl) {
		return true
	}

	return false
}

// SetPresignedUrl gets a reference to the given string and assigns it to the PresignedUrl field.
func (o *InternalMultipartUploadResponse) SetPresignedUrl(v string) {
	o.PresignedUrl = &v
}

func (o InternalMultipartUploadResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalMultipartUploadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PresignedUrl) {
		toSerialize["presigned_url"] = o.PresignedUrl
	}
	return toSerialize, nil
}

type NullableInternalMultipartUploadResponse struct {
	value *InternalMultipartUploadResponse
	isSet bool
}

func (v NullableInternalMultipartUploadResponse) Get() *InternalMultipartUploadResponse {
	return v.value
}

func (v *NullableInternalMultipartUploadResponse) Set(val *InternalMultipartUploadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalMultipartUploadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalMultipartUploadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalMultipartUploadResponse(val *InternalMultipartUploadResponse) *NullableInternalMultipartUploadResponse {
	return &NullableInternalMultipartUploadResponse{value: val, isSet: true}
}

func (v NullableInternalMultipartUploadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalMultipartUploadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
