/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FenceMultipartUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FenceMultipartUploadRequest{}

// FenceMultipartUploadRequest struct for FenceMultipartUploadRequest
type FenceMultipartUploadRequest struct {
	Key string `json:"key"`
	Bucket *string `json:"bucket,omitempty"`
	UploadId string `json:"uploadId"`
	PartNumber int32 `json:"partNumber"`
}

type _FenceMultipartUploadRequest FenceMultipartUploadRequest

// NewFenceMultipartUploadRequest instantiates a new FenceMultipartUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFenceMultipartUploadRequest(key string, uploadId string, partNumber int32) *FenceMultipartUploadRequest {
	this := FenceMultipartUploadRequest{}
	this.Key = key
	this.UploadId = uploadId
	this.PartNumber = partNumber
	return &this
}

// NewFenceMultipartUploadRequestWithDefaults instantiates a new FenceMultipartUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFenceMultipartUploadRequestWithDefaults() *FenceMultipartUploadRequest {
	this := FenceMultipartUploadRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *FenceMultipartUploadRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *FenceMultipartUploadRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *FenceMultipartUploadRequest) SetKey(v string) {
	o.Key = v
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *FenceMultipartUploadRequest) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FenceMultipartUploadRequest) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *FenceMultipartUploadRequest) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *FenceMultipartUploadRequest) SetBucket(v string) {
	o.Bucket = &v
}

// GetUploadId returns the UploadId field value
func (o *FenceMultipartUploadRequest) GetUploadId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadId
}

// GetUploadIdOk returns a tuple with the UploadId field value
// and a boolean to check if the value has been set.
func (o *FenceMultipartUploadRequest) GetUploadIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadId, true
}

// SetUploadId sets field value
func (o *FenceMultipartUploadRequest) SetUploadId(v string) {
	o.UploadId = v
}

// GetPartNumber returns the PartNumber field value
func (o *FenceMultipartUploadRequest) GetPartNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value
// and a boolean to check if the value has been set.
func (o *FenceMultipartUploadRequest) GetPartNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartNumber, true
}

// SetPartNumber sets field value
func (o *FenceMultipartUploadRequest) SetPartNumber(v int32) {
	o.PartNumber = v
}

func (o FenceMultipartUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FenceMultipartUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	toSerialize["uploadId"] = o.UploadId
	toSerialize["partNumber"] = o.PartNumber
	return toSerialize, nil
}

func (o *FenceMultipartUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"uploadId",
		"partNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFenceMultipartUploadRequest := _FenceMultipartUploadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFenceMultipartUploadRequest)

	if err != nil {
		return err
	}

	*o = FenceMultipartUploadRequest(varFenceMultipartUploadRequest)

	return err
}

type NullableFenceMultipartUploadRequest struct {
	value *FenceMultipartUploadRequest
	isSet bool
}

func (v NullableFenceMultipartUploadRequest) Get() *FenceMultipartUploadRequest {
	return v.value
}

func (v *NullableFenceMultipartUploadRequest) Set(val *FenceMultipartUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFenceMultipartUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFenceMultipartUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFenceMultipartUploadRequest(val *FenceMultipartUploadRequest) *NullableFenceMultipartUploadRequest {
	return &NullableFenceMultipartUploadRequest{value: val, isSet: true}
}

func (v NullableFenceMultipartUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFenceMultipartUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


