/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
)

// checks if the BulkDocumentsRequestOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkDocumentsRequestOneOf{}

// BulkDocumentsRequestOneOf struct for BulkDocumentsRequestOneOf
type BulkDocumentsRequestOneOf struct {
	Ids []string `json:"ids,omitempty"`
	Dids []string `json:"dids,omitempty"`
}

// NewBulkDocumentsRequestOneOf instantiates a new BulkDocumentsRequestOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkDocumentsRequestOneOf() *BulkDocumentsRequestOneOf {
	this := BulkDocumentsRequestOneOf{}
	return &this
}

// NewBulkDocumentsRequestOneOfWithDefaults instantiates a new BulkDocumentsRequestOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkDocumentsRequestOneOfWithDefaults() *BulkDocumentsRequestOneOf {
	this := BulkDocumentsRequestOneOf{}
	return &this
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *BulkDocumentsRequestOneOf) GetIds() []string {
	if o == nil || IsNil(o.Ids) {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDocumentsRequestOneOf) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *BulkDocumentsRequestOneOf) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *BulkDocumentsRequestOneOf) SetIds(v []string) {
	o.Ids = v
}

// GetDids returns the Dids field value if set, zero value otherwise.
func (o *BulkDocumentsRequestOneOf) GetDids() []string {
	if o == nil || IsNil(o.Dids) {
		var ret []string
		return ret
	}
	return o.Dids
}

// GetDidsOk returns a tuple with the Dids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkDocumentsRequestOneOf) GetDidsOk() ([]string, bool) {
	if o == nil || IsNil(o.Dids) {
		return nil, false
	}
	return o.Dids, true
}

// HasDids returns a boolean if a field has been set.
func (o *BulkDocumentsRequestOneOf) HasDids() bool {
	if o != nil && !IsNil(o.Dids) {
		return true
	}

	return false
}

// SetDids gets a reference to the given []string and assigns it to the Dids field.
func (o *BulkDocumentsRequestOneOf) SetDids(v []string) {
	o.Dids = v
}

func (o BulkDocumentsRequestOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkDocumentsRequestOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	if !IsNil(o.Dids) {
		toSerialize["dids"] = o.Dids
	}
	return toSerialize, nil
}

type NullableBulkDocumentsRequestOneOf struct {
	value *BulkDocumentsRequestOneOf
	isSet bool
}

func (v NullableBulkDocumentsRequestOneOf) Get() *BulkDocumentsRequestOneOf {
	return v.value
}

func (v *NullableBulkDocumentsRequestOneOf) Set(val *BulkDocumentsRequestOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDocumentsRequestOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDocumentsRequestOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDocumentsRequestOneOf(val *BulkDocumentsRequestOneOf) *NullableBulkDocumentsRequestOneOf {
	return &NullableBulkDocumentsRequestOneOf{value: val, isSet: true}
}

func (v NullableBulkDocumentsRequestOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDocumentsRequestOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


