/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
)

// checks if the InternalMultipartInitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalMultipartInitRequest{}

// InternalMultipartInitRequest struct for InternalMultipartInitRequest
type InternalMultipartInitRequest struct {
	Guid *string `json:"guid,omitempty"`
	FileName *string `json:"file_name,omitempty"`
	Bucket *string `json:"bucket,omitempty"`
}

// NewInternalMultipartInitRequest instantiates a new InternalMultipartInitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalMultipartInitRequest() *InternalMultipartInitRequest {
	this := InternalMultipartInitRequest{}
	return &this
}

// NewInternalMultipartInitRequestWithDefaults instantiates a new InternalMultipartInitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalMultipartInitRequestWithDefaults() *InternalMultipartInitRequest {
	this := InternalMultipartInitRequest{}
	return &this
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *InternalMultipartInitRequest) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalMultipartInitRequest) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *InternalMultipartInitRequest) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *InternalMultipartInitRequest) SetGuid(v string) {
	o.Guid = &v
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *InternalMultipartInitRequest) GetFileName() string {
	if o == nil || IsNil(o.FileName) {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalMultipartInitRequest) GetFileNameOk() (*string, bool) {
	if o == nil || IsNil(o.FileName) {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *InternalMultipartInitRequest) HasFileName() bool {
	if o != nil && !IsNil(o.FileName) {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *InternalMultipartInitRequest) SetFileName(v string) {
	o.FileName = &v
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *InternalMultipartInitRequest) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalMultipartInitRequest) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *InternalMultipartInitRequest) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *InternalMultipartInitRequest) SetBucket(v string) {
	o.Bucket = &v
}

func (o InternalMultipartInitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalMultipartInitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.FileName) {
		toSerialize["file_name"] = o.FileName
	}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	return toSerialize, nil
}

type NullableInternalMultipartInitRequest struct {
	value *InternalMultipartInitRequest
	isSet bool
}

func (v NullableInternalMultipartInitRequest) Get() *InternalMultipartInitRequest {
	return v.value
}

func (v *NullableInternalMultipartInitRequest) Set(val *InternalMultipartInitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalMultipartInitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalMultipartInitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalMultipartInitRequest(val *InternalMultipartInitRequest) *NullableInternalMultipartInitRequest {
	return &NullableInternalMultipartInitRequest{value: val, isSet: true}
}

func (v NullableInternalMultipartInitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalMultipartInitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


