/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
)

// checks if the InternalMultipartInitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalMultipartInitResponse{}

// InternalMultipartInitResponse struct for InternalMultipartInitResponse
type InternalMultipartInitResponse struct {
	Guid *string `json:"guid,omitempty"`
	UploadId *string `json:"uploadId,omitempty"`
}

// NewInternalMultipartInitResponse instantiates a new InternalMultipartInitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalMultipartInitResponse() *InternalMultipartInitResponse {
	this := InternalMultipartInitResponse{}
	return &this
}

// NewInternalMultipartInitResponseWithDefaults instantiates a new InternalMultipartInitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalMultipartInitResponseWithDefaults() *InternalMultipartInitResponse {
	this := InternalMultipartInitResponse{}
	return &this
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *InternalMultipartInitResponse) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalMultipartInitResponse) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *InternalMultipartInitResponse) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *InternalMultipartInitResponse) SetGuid(v string) {
	o.Guid = &v
}

// GetUploadId returns the UploadId field value if set, zero value otherwise.
func (o *InternalMultipartInitResponse) GetUploadId() string {
	if o == nil || IsNil(o.UploadId) {
		var ret string
		return ret
	}
	return *o.UploadId
}

// GetUploadIdOk returns a tuple with the UploadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalMultipartInitResponse) GetUploadIdOk() (*string, bool) {
	if o == nil || IsNil(o.UploadId) {
		return nil, false
	}
	return o.UploadId, true
}

// HasUploadId returns a boolean if a field has been set.
func (o *InternalMultipartInitResponse) HasUploadId() bool {
	if o != nil && !IsNil(o.UploadId) {
		return true
	}

	return false
}

// SetUploadId gets a reference to the given string and assigns it to the UploadId field.
func (o *InternalMultipartInitResponse) SetUploadId(v string) {
	o.UploadId = &v
}

func (o InternalMultipartInitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalMultipartInitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.UploadId) {
		toSerialize["uploadId"] = o.UploadId
	}
	return toSerialize, nil
}

type NullableInternalMultipartInitResponse struct {
	value *InternalMultipartInitResponse
	isSet bool
}

func (v NullableInternalMultipartInitResponse) Get() *InternalMultipartInitResponse {
	return v.value
}

func (v *NullableInternalMultipartInitResponse) Set(val *InternalMultipartInitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalMultipartInitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalMultipartInitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalMultipartInitResponse(val *InternalMultipartInitResponse) *NullableInternalMultipartInitResponse {
	return &NullableInternalMultipartInitResponse{value: val, isSet: true}
}

func (v NullableInternalMultipartInitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalMultipartInitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


