/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
)

// checks if the FenceUploadBlankRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FenceUploadBlankRequest{}

// FenceUploadBlankRequest struct for FenceUploadBlankRequest
type FenceUploadBlankRequest struct {
	Guid *string `json:"guid,omitempty"`
	Authz []string `json:"authz,omitempty"`
}

// NewFenceUploadBlankRequest instantiates a new FenceUploadBlankRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFenceUploadBlankRequest() *FenceUploadBlankRequest {
	this := FenceUploadBlankRequest{}
	return &this
}

// NewFenceUploadBlankRequestWithDefaults instantiates a new FenceUploadBlankRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFenceUploadBlankRequestWithDefaults() *FenceUploadBlankRequest {
	this := FenceUploadBlankRequest{}
	return &this
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *FenceUploadBlankRequest) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FenceUploadBlankRequest) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *FenceUploadBlankRequest) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *FenceUploadBlankRequest) SetGuid(v string) {
	o.Guid = &v
}

// GetAuthz returns the Authz field value if set, zero value otherwise.
func (o *FenceUploadBlankRequest) GetAuthz() []string {
	if o == nil || IsNil(o.Authz) {
		var ret []string
		return ret
	}
	return o.Authz
}

// GetAuthzOk returns a tuple with the Authz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FenceUploadBlankRequest) GetAuthzOk() ([]string, bool) {
	if o == nil || IsNil(o.Authz) {
		return nil, false
	}
	return o.Authz, true
}

// HasAuthz returns a boolean if a field has been set.
func (o *FenceUploadBlankRequest) HasAuthz() bool {
	if o != nil && !IsNil(o.Authz) {
		return true
	}

	return false
}

// SetAuthz gets a reference to the given []string and assigns it to the Authz field.
func (o *FenceUploadBlankRequest) SetAuthz(v []string) {
	o.Authz = v
}

func (o FenceUploadBlankRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FenceUploadBlankRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.Authz) {
		toSerialize["authz"] = o.Authz
	}
	return toSerialize, nil
}

type NullableFenceUploadBlankRequest struct {
	value *FenceUploadBlankRequest
	isSet bool
}

func (v NullableFenceUploadBlankRequest) Get() *FenceUploadBlankRequest {
	return v.value
}

func (v *NullableFenceUploadBlankRequest) Set(val *FenceUploadBlankRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFenceUploadBlankRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFenceUploadBlankRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFenceUploadBlankRequest(val *FenceUploadBlankRequest) *NullableFenceUploadBlankRequest {
	return &NullableFenceUploadBlankRequest{value: val, isSet: true}
}

func (v NullableFenceUploadBlankRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFenceUploadBlankRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


