/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
)

// checks if the InternalUploadBulkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalUploadBulkResponse{}

// InternalUploadBulkResponse struct for InternalUploadBulkResponse
type InternalUploadBulkResponse struct {
	Results []InternalUploadBulkResult `json:"results,omitempty"`
}

// NewInternalUploadBulkResponse instantiates a new InternalUploadBulkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalUploadBulkResponse() *InternalUploadBulkResponse {
	this := InternalUploadBulkResponse{}
	return &this
}

// NewInternalUploadBulkResponseWithDefaults instantiates a new InternalUploadBulkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalUploadBulkResponseWithDefaults() *InternalUploadBulkResponse {
	this := InternalUploadBulkResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *InternalUploadBulkResponse) GetResults() []InternalUploadBulkResult {
	if o == nil || IsNil(o.Results) {
		var ret []InternalUploadBulkResult
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalUploadBulkResponse) GetResultsOk() ([]InternalUploadBulkResult, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *InternalUploadBulkResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []InternalUploadBulkResult and assigns it to the Results field.
func (o *InternalUploadBulkResponse) SetResults(v []InternalUploadBulkResult) {
	o.Results = v
}

func (o InternalUploadBulkResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalUploadBulkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableInternalUploadBulkResponse struct {
	value *InternalUploadBulkResponse
	isSet bool
}

func (v NullableInternalUploadBulkResponse) Get() *InternalUploadBulkResponse {
	return v.value
}

func (v *NullableInternalUploadBulkResponse) Set(val *InternalUploadBulkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalUploadBulkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalUploadBulkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalUploadBulkResponse(val *InternalUploadBulkResponse) *NullableInternalUploadBulkResponse {
	return &NullableInternalUploadBulkResponse{value: val, isSet: true}
}

func (v NullableInternalUploadBulkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalUploadBulkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


