/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
)

// checks if the DeleteByQueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteByQueryResponse{}

// DeleteByQueryResponse struct for DeleteByQueryResponse
type DeleteByQueryResponse struct {
	Deleted *int32 `json:"deleted,omitempty"`
}

// NewDeleteByQueryResponse instantiates a new DeleteByQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteByQueryResponse() *DeleteByQueryResponse {
	this := DeleteByQueryResponse{}
	return &this
}

// NewDeleteByQueryResponseWithDefaults instantiates a new DeleteByQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteByQueryResponseWithDefaults() *DeleteByQueryResponse {
	this := DeleteByQueryResponse{}
	return &this
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *DeleteByQueryResponse) GetDeleted() int32 {
	if o == nil || IsNil(o.Deleted) {
		var ret int32
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteByQueryResponse) GetDeletedOk() (*int32, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *DeleteByQueryResponse) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given int32 and assigns it to the Deleted field.
func (o *DeleteByQueryResponse) SetDeleted(v int32) {
	o.Deleted = &v
}

func (o DeleteByQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteByQueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	return toSerialize, nil
}

type NullableDeleteByQueryResponse struct {
	value *DeleteByQueryResponse
	isSet bool
}

func (v NullableDeleteByQueryResponse) Get() *DeleteByQueryResponse {
	return v.value
}

func (v *NullableDeleteByQueryResponse) Set(val *DeleteByQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteByQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteByQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteByQueryResponse(val *DeleteByQueryResponse) *NullableDeleteByQueryResponse {
	return &NullableDeleteByQueryResponse{value: val, isSet: true}
}

func (v NullableDeleteByQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteByQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


