/*
Internal Compatibility API (DRS Server)

Consolidated internal API delta for drs-server. This spec captures non-GA4GH DRS internal/compatibility routes. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package internalapi

import (
	"encoding/json"
)

// checks if the IndexdRecordResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexdRecordResponse{}

// IndexdRecordResponse struct for IndexdRecordResponse
type IndexdRecordResponse struct {
	Did *string `json:"did,omitempty"`
	// Hash map, e.g. {\"sha256\":\"...\"}
	Hashes *map[string]string `json:"hashes,omitempty"`
	Size *int64 `json:"size,omitempty"`
	Urls []string `json:"urls,omitempty"`
	Authz []string `json:"authz,omitempty"`
	FileName *string `json:"file_name,omitempty"`
	Organization *string `json:"organization,omitempty"`
	Project *string `json:"project,omitempty"`
	Baseid *string `json:"baseid,omitempty"`
	Rev *string `json:"rev,omitempty"`
	CreatedDate *string `json:"created_date,omitempty"`
	UpdatedDate *string `json:"updated_date,omitempty"`
	Uploader *string `json:"uploader,omitempty"`
}

// NewIndexdRecordResponse instantiates a new IndexdRecordResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexdRecordResponse() *IndexdRecordResponse {
	this := IndexdRecordResponse{}
	return &this
}

// NewIndexdRecordResponseWithDefaults instantiates a new IndexdRecordResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexdRecordResponseWithDefaults() *IndexdRecordResponse {
	this := IndexdRecordResponse{}
	return &this
}

// GetDid returns the Did field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetDid() string {
	if o == nil || IsNil(o.Did) {
		var ret string
		return ret
	}
	return *o.Did
}

// GetDidOk returns a tuple with the Did field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetDidOk() (*string, bool) {
	if o == nil || IsNil(o.Did) {
		return nil, false
	}
	return o.Did, true
}

// HasDid returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasDid() bool {
	if o != nil && !IsNil(o.Did) {
		return true
	}

	return false
}

// SetDid gets a reference to the given string and assigns it to the Did field.
func (o *IndexdRecordResponse) SetDid(v string) {
	o.Did = &v
}

// GetHashes returns the Hashes field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetHashes() map[string]string {
	if o == nil || IsNil(o.Hashes) {
		var ret map[string]string
		return ret
	}
	return *o.Hashes
}

// GetHashesOk returns a tuple with the Hashes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetHashesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Hashes) {
		return nil, false
	}
	return o.Hashes, true
}

// HasHashes returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasHashes() bool {
	if o != nil && !IsNil(o.Hashes) {
		return true
	}

	return false
}

// SetHashes gets a reference to the given map[string]string and assigns it to the Hashes field.
func (o *IndexdRecordResponse) SetHashes(v map[string]string) {
	o.Hashes = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *IndexdRecordResponse) SetSize(v int64) {
	o.Size = &v
}

// GetUrls returns the Urls field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetUrls() []string {
	if o == nil || IsNil(o.Urls) {
		var ret []string
		return ret
	}
	return o.Urls
}

// GetUrlsOk returns a tuple with the Urls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetUrlsOk() ([]string, bool) {
	if o == nil || IsNil(o.Urls) {
		return nil, false
	}
	return o.Urls, true
}

// HasUrls returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasUrls() bool {
	if o != nil && !IsNil(o.Urls) {
		return true
	}

	return false
}

// SetUrls gets a reference to the given []string and assigns it to the Urls field.
func (o *IndexdRecordResponse) SetUrls(v []string) {
	o.Urls = v
}

// GetAuthz returns the Authz field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetAuthz() []string {
	if o == nil || IsNil(o.Authz) {
		var ret []string
		return ret
	}
	return o.Authz
}

// GetAuthzOk returns a tuple with the Authz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetAuthzOk() ([]string, bool) {
	if o == nil || IsNil(o.Authz) {
		return nil, false
	}
	return o.Authz, true
}

// HasAuthz returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasAuthz() bool {
	if o != nil && !IsNil(o.Authz) {
		return true
	}

	return false
}

// SetAuthz gets a reference to the given []string and assigns it to the Authz field.
func (o *IndexdRecordResponse) SetAuthz(v []string) {
	o.Authz = v
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetFileName() string {
	if o == nil || IsNil(o.FileName) {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetFileNameOk() (*string, bool) {
	if o == nil || IsNil(o.FileName) {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasFileName() bool {
	if o != nil && !IsNil(o.FileName) {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *IndexdRecordResponse) SetFileName(v string) {
	o.FileName = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *IndexdRecordResponse) SetOrganization(v string) {
	o.Organization = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetProject() string {
	if o == nil || IsNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetProjectOk() (*string, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *IndexdRecordResponse) SetProject(v string) {
	o.Project = &v
}

// GetBaseid returns the Baseid field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetBaseid() string {
	if o == nil || IsNil(o.Baseid) {
		var ret string
		return ret
	}
	return *o.Baseid
}

// GetBaseidOk returns a tuple with the Baseid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetBaseidOk() (*string, bool) {
	if o == nil || IsNil(o.Baseid) {
		return nil, false
	}
	return o.Baseid, true
}

// HasBaseid returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasBaseid() bool {
	if o != nil && !IsNil(o.Baseid) {
		return true
	}

	return false
}

// SetBaseid gets a reference to the given string and assigns it to the Baseid field.
func (o *IndexdRecordResponse) SetBaseid(v string) {
	o.Baseid = &v
}

// GetRev returns the Rev field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetRev() string {
	if o == nil || IsNil(o.Rev) {
		var ret string
		return ret
	}
	return *o.Rev
}

// GetRevOk returns a tuple with the Rev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetRevOk() (*string, bool) {
	if o == nil || IsNil(o.Rev) {
		return nil, false
	}
	return o.Rev, true
}

// HasRev returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasRev() bool {
	if o != nil && !IsNil(o.Rev) {
		return true
	}

	return false
}

// SetRev gets a reference to the given string and assigns it to the Rev field.
func (o *IndexdRecordResponse) SetRev(v string) {
	o.Rev = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetCreatedDate() string {
	if o == nil || IsNil(o.CreatedDate) {
		var ret string
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetCreatedDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given string and assigns it to the CreatedDate field.
func (o *IndexdRecordResponse) SetCreatedDate(v string) {
	o.CreatedDate = &v
}

// GetUpdatedDate returns the UpdatedDate field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetUpdatedDate() string {
	if o == nil || IsNil(o.UpdatedDate) {
		var ret string
		return ret
	}
	return *o.UpdatedDate
}

// GetUpdatedDateOk returns a tuple with the UpdatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetUpdatedDateOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedDate) {
		return nil, false
	}
	return o.UpdatedDate, true
}

// HasUpdatedDate returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasUpdatedDate() bool {
	if o != nil && !IsNil(o.UpdatedDate) {
		return true
	}

	return false
}

// SetUpdatedDate gets a reference to the given string and assigns it to the UpdatedDate field.
func (o *IndexdRecordResponse) SetUpdatedDate(v string) {
	o.UpdatedDate = &v
}

// GetUploader returns the Uploader field value if set, zero value otherwise.
func (o *IndexdRecordResponse) GetUploader() string {
	if o == nil || IsNil(o.Uploader) {
		var ret string
		return ret
	}
	return *o.Uploader
}

// GetUploaderOk returns a tuple with the Uploader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexdRecordResponse) GetUploaderOk() (*string, bool) {
	if o == nil || IsNil(o.Uploader) {
		return nil, false
	}
	return o.Uploader, true
}

// HasUploader returns a boolean if a field has been set.
func (o *IndexdRecordResponse) HasUploader() bool {
	if o != nil && !IsNil(o.Uploader) {
		return true
	}

	return false
}

// SetUploader gets a reference to the given string and assigns it to the Uploader field.
func (o *IndexdRecordResponse) SetUploader(v string) {
	o.Uploader = &v
}

func (o IndexdRecordResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexdRecordResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Did) {
		toSerialize["did"] = o.Did
	}
	if !IsNil(o.Hashes) {
		toSerialize["hashes"] = o.Hashes
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Urls) {
		toSerialize["urls"] = o.Urls
	}
	if !IsNil(o.Authz) {
		toSerialize["authz"] = o.Authz
	}
	if !IsNil(o.FileName) {
		toSerialize["file_name"] = o.FileName
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.Baseid) {
		toSerialize["baseid"] = o.Baseid
	}
	if !IsNil(o.Rev) {
		toSerialize["rev"] = o.Rev
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["created_date"] = o.CreatedDate
	}
	if !IsNil(o.UpdatedDate) {
		toSerialize["updated_date"] = o.UpdatedDate
	}
	if !IsNil(o.Uploader) {
		toSerialize["uploader"] = o.Uploader
	}
	return toSerialize, nil
}

type NullableIndexdRecordResponse struct {
	value *IndexdRecordResponse
	isSet bool
}

func (v NullableIndexdRecordResponse) Get() *IndexdRecordResponse {
	return v.value
}

func (v *NullableIndexdRecordResponse) Set(val *IndexdRecordResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexdRecordResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexdRecordResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexdRecordResponse(val *IndexdRecordResponse) *NullableIndexdRecordResponse {
	return &NullableIndexdRecordResponse{value: val, isSet: true}
}

func (v NullableIndexdRecordResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexdRecordResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


