// Package metricsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package metricsapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ProviderTransferDirection.
const (
	Download ProviderTransferDirection = "download"
	Upload   ProviderTransferDirection = "upload"
)

// Defines values for ProviderTransferReconciliationStatus.
const (
	All       ProviderTransferReconciliationStatus = "all"
	Ambiguous ProviderTransferReconciliationStatus = "ambiguous"
	Matched   ProviderTransferReconciliationStatus = "matched"
	Unmatched ProviderTransferReconciliationStatus = "unmatched"
)

// Defines values for TransferBreakdownResponseGroupBy.
const (
	TransferBreakdownResponseGroupByObject   TransferBreakdownResponseGroupBy = "object"
	TransferBreakdownResponseGroupByProvider TransferBreakdownResponseGroupBy = "provider"
	TransferBreakdownResponseGroupByScope    TransferBreakdownResponseGroupBy = "scope"
	TransferBreakdownResponseGroupByUser     TransferBreakdownResponseGroupBy = "user"
)

// Defines values for GetTransferBreakdownParamsGroupBy.
const (
	GetTransferBreakdownParamsGroupByObject   GetTransferBreakdownParamsGroupBy = "object"
	GetTransferBreakdownParamsGroupByProvider GetTransferBreakdownParamsGroupBy = "provider"
	GetTransferBreakdownParamsGroupByScope    GetTransferBreakdownParamsGroupBy = "scope"
	GetTransferBreakdownParamsGroupByUser     GetTransferBreakdownParamsGroupBy = "user"
)

// FileUsage defines model for FileUsage.
type FileUsage struct {
	DownloadCount    *int64     `json:"download_count,omitempty"`
	LastAccessTime   *time.Time `json:"last_access_time"`
	LastDownloadTime *time.Time `json:"last_download_time"`
	LastUploadTime   *time.Time `json:"last_upload_time"`
	Name             *string    `json:"name,omitempty"`
	ObjectId         *string    `json:"object_id,omitempty"`
	Size             *int64     `json:"size,omitempty"`
	UploadCount      *int64     `json:"upload_count,omitempty"`
}

// FileUsageSummary defines model for FileUsageSummary.
type FileUsageSummary struct {
	InactiveFileCount *int64 `json:"inactive_file_count,omitempty"`
	TotalDownloads    *int64 `json:"total_downloads,omitempty"`
	TotalFiles        *int64 `json:"total_files,omitempty"`
	TotalUploads      *int64 `json:"total_uploads,omitempty"`
}

// MetricsListResponse defines model for MetricsListResponse.
type MetricsListResponse struct {
	Data   *[]FileUsage `json:"data,omitempty"`
	Limit  *int         `json:"limit,omitempty"`
	Offset *int         `json:"offset,omitempty"`
}

// ProviderTransferDirection defines model for ProviderTransferDirection.
type ProviderTransferDirection string

// ProviderTransferEvent defines model for ProviderTransferEvent.
type ProviderTransferEvent struct {
	AccessGrantId    *string                   `json:"access_grant_id,omitempty"`
	AccessId         *string                   `json:"access_id,omitempty"`
	ActorEmail       *string                   `json:"actor_email,omitempty"`
	ActorSubject     *string                   `json:"actor_subject,omitempty"`
	AuthMode         *string                   `json:"auth_mode,omitempty"`
	Bucket           string                    `json:"bucket"`
	BytesTransferred int64                     `json:"bytes_transferred"`
	Direction        ProviderTransferDirection `json:"direction"`
	EventTime        *time.Time                `json:"event_time,omitempty"`
	HttpMethod       *string                   `json:"http_method,omitempty"`
	HttpStatus       *int                      `json:"http_status,omitempty"`

	// ObjectId DRS object DID when known.
	ObjectId     *string `json:"object_id,omitempty"`
	ObjectKey    *string `json:"object_key,omitempty"`
	ObjectSize   *int64  `json:"object_size,omitempty"`
	Organization *string `json:"organization,omitempty"`
	Project      *string `json:"project,omitempty"`
	Provider     string  `json:"provider"`

	// ProviderEventId Provider/importer idempotency key.
	ProviderEventId      string                                `json:"provider_event_id"`
	ProviderRequestId    *string                               `json:"provider_request_id,omitempty"`
	RangeEnd             *int64                                `json:"range_end"`
	RangeStart           *int64                                `json:"range_start"`
	RawEventRef          *string                               `json:"raw_event_ref,omitempty"`
	ReconciliationStatus *ProviderTransferReconciliationStatus `json:"reconciliation_status,omitempty"`
	RequestId            *string                               `json:"request_id,omitempty"`
	RequesterPrincipal   *string                               `json:"requester_principal,omitempty"`
	Sha256               *string                               `json:"sha256,omitempty"`
	SourceIp             *string                               `json:"source_ip,omitempty"`
	StorageUrl           *string                               `json:"storage_url,omitempty"`
	UserAgent            *string                               `json:"user_agent,omitempty"`
}

// ProviderTransferEventsRequest defines model for ProviderTransferEventsRequest.
type ProviderTransferEventsRequest struct {
	Events []ProviderTransferEvent `json:"events"`
}

// ProviderTransferReconciliationStatus defines model for ProviderTransferReconciliationStatus.
type ProviderTransferReconciliationStatus string

// TransferAttributionBreakdown defines model for TransferAttributionBreakdown.
type TransferAttributionBreakdown struct {
	ActorEmail       *string    `json:"actor_email,omitempty"`
	ActorSubject     *string    `json:"actor_subject,omitempty"`
	Bucket           *string    `json:"bucket,omitempty"`
	BytesDownloaded  *int64     `json:"bytes_downloaded,omitempty"`
	BytesRequested   *int64     `json:"bytes_requested,omitempty"`
	BytesUploaded    *int64     `json:"bytes_uploaded,omitempty"`
	EventCount       *int64     `json:"event_count,omitempty"`
	Key              *string    `json:"key,omitempty"`
	LastTransferTime *time.Time `json:"last_transfer_time"`
	Organization     *string    `json:"organization,omitempty"`
	Project          *string    `json:"project,omitempty"`
	Provider         *string    `json:"provider,omitempty"`
	Sha256           *string    `json:"sha256,omitempty"`
}

// TransferAttributionSummary defines model for TransferAttributionSummary.
type TransferAttributionSummary struct {
	AccessIssuedCount  *int64                    `json:"access_issued_count,omitempty"`
	BytesDownloaded    *int64                    `json:"bytes_downloaded,omitempty"`
	BytesRequested     *int64                    `json:"bytes_requested,omitempty"`
	BytesUploaded      *int64                    `json:"bytes_uploaded,omitempty"`
	DownloadEventCount *int64                    `json:"download_event_count,omitempty"`
	EventCount         *int64                    `json:"event_count,omitempty"`
	Freshness          *TransferMetricsFreshness `json:"freshness,omitempty"`
	UploadEventCount   *int64                    `json:"upload_event_count,omitempty"`
}

// TransferBreakdownResponse defines model for TransferBreakdownResponse.
type TransferBreakdownResponse struct {
	Data      *[]TransferAttributionBreakdown   `json:"data,omitempty"`
	Freshness *TransferMetricsFreshness         `json:"freshness,omitempty"`
	GroupBy   *TransferBreakdownResponseGroupBy `json:"group_by,omitempty"`
}

// TransferBreakdownResponseGroupBy defines model for TransferBreakdownResponse.GroupBy.
type TransferBreakdownResponseGroupBy string

// TransferEventsRecordedResponse defines model for TransferEventsRecordedResponse.
type TransferEventsRecordedResponse struct {
	Recorded *int `json:"recorded,omitempty"`
}

// TransferMetricsFreshness defines model for TransferMetricsFreshness.
type TransferMetricsFreshness struct {
	IsStale             *bool      `json:"is_stale,omitempty"`
	LatestCompletedSync *time.Time `json:"latest_completed_sync"`
	MissingBuckets      *[]string  `json:"missing_buckets,omitempty"`
	RequiredFrom        *time.Time `json:"required_from"`
	RequiredTo          *time.Time `json:"required_to"`
}

// AllowStale defines model for AllowStale.
type AllowStale = bool

// Bucket defines model for Bucket.
type Bucket = string

// Direction defines model for Direction.
type Direction = ProviderTransferDirection

// From defines model for From.
type From = time.Time

// Organization defines model for Organization.
type Organization = string

// Project defines model for Project.
type Project = string

// Provider defines model for Provider.
type Provider = string

// ReconciliationStatus defines model for ReconciliationStatus.
type ReconciliationStatus = ProviderTransferReconciliationStatus

// SHA256 defines model for SHA256.
type SHA256 = string

// To defines model for To.
type To = time.Time

// User defines model for User.
type User = string

// ListMetricsFilesParams defines parameters for ListMetricsFiles.
type ListMetricsFilesParams struct {
	Limit        *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset       *int `form:"offset,omitempty" json:"offset,omitempty"`
	InactiveDays *int `form:"inactive_days,omitempty" json:"inactive_days,omitempty"`

	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project *Project `form:"project,omitempty" json:"project,omitempty"`
}

// GetMetricsFileParams defines parameters for GetMetricsFile.
type GetMetricsFileParams struct {
	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project *Project `form:"project,omitempty" json:"project,omitempty"`
}

// RecordProviderTransferEventsParams defines parameters for RecordProviderTransferEvents.
type RecordProviderTransferEventsParams struct {
	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project *Project `form:"project,omitempty" json:"project,omitempty"`
}

// GetMetricsSummaryParams defines parameters for GetMetricsSummary.
type GetMetricsSummaryParams struct {
	InactiveDays *int `form:"inactive_days,omitempty" json:"inactive_days,omitempty"`

	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project *Project `form:"project,omitempty" json:"project,omitempty"`
}

// GetTransferBreakdownParams defines parameters for GetTransferBreakdown.
type GetTransferBreakdownParams struct {
	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project              *Project              `form:"project,omitempty" json:"project,omitempty"`
	Direction            *Direction            `form:"direction,omitempty" json:"direction,omitempty"`
	ReconciliationStatus *ReconciliationStatus `form:"reconciliation_status,omitempty" json:"reconciliation_status,omitempty"`
	From                 *From                 `form:"from,omitempty" json:"from,omitempty"`
	To                   *To                   `form:"to,omitempty" json:"to,omitempty"`
	Provider             *Provider             `form:"provider,omitempty" json:"provider,omitempty"`
	Bucket               *Bucket               `form:"bucket,omitempty" json:"bucket,omitempty"`
	Sha256               *SHA256               `form:"sha256,omitempty" json:"sha256,omitempty"`

	// User Actor email or subject filter.
	User *User `form:"user,omitempty" json:"user,omitempty"`

	// AllowStale Deprecated. Transfer metrics always return persisted provider events with freshness metadata, including missing sync windows and latest completed sync time.
	AllowStale *AllowStale                        `form:"allow_stale,omitempty" json:"allow_stale,omitempty"`
	GroupBy    *GetTransferBreakdownParamsGroupBy `form:"group_by,omitempty" json:"group_by,omitempty"`
}

// GetTransferBreakdownParamsGroupBy defines parameters for GetTransferBreakdown.
type GetTransferBreakdownParamsGroupBy string

// GetTransferSummaryParams defines parameters for GetTransferSummary.
type GetTransferSummaryParams struct {
	// Organization Organization/program scope filter.
	Organization *Organization `form:"organization,omitempty" json:"organization,omitempty"`

	// Project Project scope filter. Requires organization when set.
	Project              *Project              `form:"project,omitempty" json:"project,omitempty"`
	Direction            *Direction            `form:"direction,omitempty" json:"direction,omitempty"`
	ReconciliationStatus *ReconciliationStatus `form:"reconciliation_status,omitempty" json:"reconciliation_status,omitempty"`
	From                 *From                 `form:"from,omitempty" json:"from,omitempty"`
	To                   *To                   `form:"to,omitempty" json:"to,omitempty"`
	Provider             *Provider             `form:"provider,omitempty" json:"provider,omitempty"`
	Bucket               *Bucket               `form:"bucket,omitempty" json:"bucket,omitempty"`
	Sha256               *SHA256               `form:"sha256,omitempty" json:"sha256,omitempty"`

	// User Actor email or subject filter.
	User *User `form:"user,omitempty" json:"user,omitempty"`

	// AllowStale Deprecated. Transfer metrics always return persisted provider events with freshness metadata, including missing sync windows and latest completed sync time.
	AllowStale *AllowStale `form:"allow_stale,omitempty" json:"allow_stale,omitempty"`
}

// RecordProviderTransferEventsJSONRequestBody defines body for RecordProviderTransferEvents for application/json ContentType.
type RecordProviderTransferEventsJSONRequestBody = ProviderTransferEventsRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListMetricsFiles request
	ListMetricsFiles(ctx context.Context, params *ListMetricsFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMetricsFile request
	GetMetricsFile(ctx context.Context, objectId string, params *GetMetricsFileParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RecordProviderTransferEventsWithBody request with any body
	RecordProviderTransferEventsWithBody(ctx context.Context, params *RecordProviderTransferEventsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RecordProviderTransferEvents(ctx context.Context, params *RecordProviderTransferEventsParams, body RecordProviderTransferEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMetricsSummary request
	GetMetricsSummary(ctx context.Context, params *GetMetricsSummaryParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTransferBreakdown request
	GetTransferBreakdown(ctx context.Context, params *GetTransferBreakdownParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTransferSummary request
	GetTransferSummary(ctx context.Context, params *GetTransferSummaryParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListMetricsFiles(ctx context.Context, params *ListMetricsFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListMetricsFilesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMetricsFile(ctx context.Context, objectId string, params *GetMetricsFileParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMetricsFileRequest(c.Server, objectId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecordProviderTransferEventsWithBody(ctx context.Context, params *RecordProviderTransferEventsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecordProviderTransferEventsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecordProviderTransferEvents(ctx context.Context, params *RecordProviderTransferEventsParams, body RecordProviderTransferEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecordProviderTransferEventsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMetricsSummary(ctx context.Context, params *GetMetricsSummaryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMetricsSummaryRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTransferBreakdown(ctx context.Context, params *GetTransferBreakdownParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTransferBreakdownRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTransferSummary(ctx context.Context, params *GetTransferSummaryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTransferSummaryRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListMetricsFilesRequest generates requests for ListMetricsFiles
func NewListMetricsFilesRequest(server string, params *ListMetricsFilesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/index/v1/metrics/files")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.InactiveDays != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "inactive_days", runtime.ParamLocationQuery, *params.InactiveDays); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Organization != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organization", runtime.ParamLocationQuery, *params.Organization); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Project != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project", runtime.ParamLocationQuery, *params.Project); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMetricsFileRequest generates requests for GetMetricsFile
func NewGetMetricsFileRequest(server string, objectId string, params *GetMetricsFileParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "object_id", runtime.ParamLocationPath, objectId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/index/v1/metrics/files/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Organization != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organization", runtime.ParamLocationQuery, *params.Organization); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Project != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project", runtime.ParamLocationQuery, *params.Project); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRecordProviderTransferEventsRequest calls the generic RecordProviderTransferEvents builder with application/json body
func NewRecordProviderTransferEventsRequest(server string, params *RecordProviderTransferEventsParams, body RecordProviderTransferEventsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRecordProviderTransferEventsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewRecordProviderTransferEventsRequestWithBody generates requests for RecordProviderTransferEvents with any type of body
func NewRecordProviderTransferEventsRequestWithBody(server string, params *RecordProviderTransferEventsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/index/v1/metrics/provider-transfer-events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Organization != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organization", runtime.ParamLocationQuery, *params.Organization); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Project != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project", runtime.ParamLocationQuery, *params.Project); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetMetricsSummaryRequest generates requests for GetMetricsSummary
func NewGetMetricsSummaryRequest(server string, params *GetMetricsSummaryParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/index/v1/metrics/summary")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.InactiveDays != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "inactive_days", runtime.ParamLocationQuery, *params.InactiveDays); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Organization != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organization", runtime.ParamLocationQuery, *params.Organization); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Project != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project", runtime.ParamLocationQuery, *params.Project); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTransferBreakdownRequest generates requests for GetTransferBreakdown
func NewGetTransferBreakdownRequest(server string, params *GetTransferBreakdownParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/index/v1/metrics/transfers/breakdown")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Organization != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organization", runtime.ParamLocationQuery, *params.Organization); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Project != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project", runtime.ParamLocationQuery, *params.Project); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Direction != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "direction", runtime.ParamLocationQuery, *params.Direction); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ReconciliationStatus != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "reconciliation_status", runtime.ParamLocationQuery, *params.ReconciliationStatus); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.From != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "from", runtime.ParamLocationQuery, *params.From); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.To != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "to", runtime.ParamLocationQuery, *params.To); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Provider != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "provider", runtime.ParamLocationQuery, *params.Provider); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Bucket != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "bucket", runtime.ParamLocationQuery, *params.Bucket); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sha256 != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sha256", runtime.ParamLocationQuery, *params.Sha256); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.User != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user", runtime.ParamLocationQuery, *params.User); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AllowStale != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "allow_stale", runtime.ParamLocationQuery, *params.AllowStale); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.GroupBy != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "group_by", runtime.ParamLocationQuery, *params.GroupBy); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTransferSummaryRequest generates requests for GetTransferSummary
func NewGetTransferSummaryRequest(server string, params *GetTransferSummaryParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/index/v1/metrics/transfers/summary")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Organization != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organization", runtime.ParamLocationQuery, *params.Organization); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Project != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project", runtime.ParamLocationQuery, *params.Project); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Direction != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "direction", runtime.ParamLocationQuery, *params.Direction); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ReconciliationStatus != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "reconciliation_status", runtime.ParamLocationQuery, *params.ReconciliationStatus); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.From != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "from", runtime.ParamLocationQuery, *params.From); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.To != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "to", runtime.ParamLocationQuery, *params.To); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Provider != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "provider", runtime.ParamLocationQuery, *params.Provider); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Bucket != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "bucket", runtime.ParamLocationQuery, *params.Bucket); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sha256 != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sha256", runtime.ParamLocationQuery, *params.Sha256); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.User != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user", runtime.ParamLocationQuery, *params.User); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AllowStale != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "allow_stale", runtime.ParamLocationQuery, *params.AllowStale); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListMetricsFilesWithResponse request
	ListMetricsFilesWithResponse(ctx context.Context, params *ListMetricsFilesParams, reqEditors ...RequestEditorFn) (*ListMetricsFilesResponse, error)

	// GetMetricsFileWithResponse request
	GetMetricsFileWithResponse(ctx context.Context, objectId string, params *GetMetricsFileParams, reqEditors ...RequestEditorFn) (*GetMetricsFileResponse, error)

	// RecordProviderTransferEventsWithBodyWithResponse request with any body
	RecordProviderTransferEventsWithBodyWithResponse(ctx context.Context, params *RecordProviderTransferEventsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecordProviderTransferEventsResponse, error)

	RecordProviderTransferEventsWithResponse(ctx context.Context, params *RecordProviderTransferEventsParams, body RecordProviderTransferEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*RecordProviderTransferEventsResponse, error)

	// GetMetricsSummaryWithResponse request
	GetMetricsSummaryWithResponse(ctx context.Context, params *GetMetricsSummaryParams, reqEditors ...RequestEditorFn) (*GetMetricsSummaryResponse, error)

	// GetTransferBreakdownWithResponse request
	GetTransferBreakdownWithResponse(ctx context.Context, params *GetTransferBreakdownParams, reqEditors ...RequestEditorFn) (*GetTransferBreakdownResponse, error)

	// GetTransferSummaryWithResponse request
	GetTransferSummaryWithResponse(ctx context.Context, params *GetTransferSummaryParams, reqEditors ...RequestEditorFn) (*GetTransferSummaryResponse, error)
}

type ListMetricsFilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MetricsListResponse
}

// Status returns HTTPResponse.Status
func (r ListMetricsFilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListMetricsFilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMetricsFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FileUsage
}

// Status returns HTTPResponse.Status
func (r GetMetricsFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMetricsFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RecordProviderTransferEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *TransferEventsRecordedResponse
}

// Status returns HTTPResponse.Status
func (r RecordProviderTransferEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RecordProviderTransferEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMetricsSummaryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FileUsageSummary
}

// Status returns HTTPResponse.Status
func (r GetMetricsSummaryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMetricsSummaryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTransferBreakdownResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransferBreakdownResponse
}

// Status returns HTTPResponse.Status
func (r GetTransferBreakdownResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTransferBreakdownResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTransferSummaryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TransferAttributionSummary
}

// Status returns HTTPResponse.Status
func (r GetTransferSummaryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTransferSummaryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListMetricsFilesWithResponse request returning *ListMetricsFilesResponse
func (c *ClientWithResponses) ListMetricsFilesWithResponse(ctx context.Context, params *ListMetricsFilesParams, reqEditors ...RequestEditorFn) (*ListMetricsFilesResponse, error) {
	rsp, err := c.ListMetricsFiles(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListMetricsFilesResponse(rsp)
}

// GetMetricsFileWithResponse request returning *GetMetricsFileResponse
func (c *ClientWithResponses) GetMetricsFileWithResponse(ctx context.Context, objectId string, params *GetMetricsFileParams, reqEditors ...RequestEditorFn) (*GetMetricsFileResponse, error) {
	rsp, err := c.GetMetricsFile(ctx, objectId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMetricsFileResponse(rsp)
}

// RecordProviderTransferEventsWithBodyWithResponse request with arbitrary body returning *RecordProviderTransferEventsResponse
func (c *ClientWithResponses) RecordProviderTransferEventsWithBodyWithResponse(ctx context.Context, params *RecordProviderTransferEventsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecordProviderTransferEventsResponse, error) {
	rsp, err := c.RecordProviderTransferEventsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecordProviderTransferEventsResponse(rsp)
}

func (c *ClientWithResponses) RecordProviderTransferEventsWithResponse(ctx context.Context, params *RecordProviderTransferEventsParams, body RecordProviderTransferEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*RecordProviderTransferEventsResponse, error) {
	rsp, err := c.RecordProviderTransferEvents(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecordProviderTransferEventsResponse(rsp)
}

// GetMetricsSummaryWithResponse request returning *GetMetricsSummaryResponse
func (c *ClientWithResponses) GetMetricsSummaryWithResponse(ctx context.Context, params *GetMetricsSummaryParams, reqEditors ...RequestEditorFn) (*GetMetricsSummaryResponse, error) {
	rsp, err := c.GetMetricsSummary(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMetricsSummaryResponse(rsp)
}

// GetTransferBreakdownWithResponse request returning *GetTransferBreakdownResponse
func (c *ClientWithResponses) GetTransferBreakdownWithResponse(ctx context.Context, params *GetTransferBreakdownParams, reqEditors ...RequestEditorFn) (*GetTransferBreakdownResponse, error) {
	rsp, err := c.GetTransferBreakdown(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTransferBreakdownResponse(rsp)
}

// GetTransferSummaryWithResponse request returning *GetTransferSummaryResponse
func (c *ClientWithResponses) GetTransferSummaryWithResponse(ctx context.Context, params *GetTransferSummaryParams, reqEditors ...RequestEditorFn) (*GetTransferSummaryResponse, error) {
	rsp, err := c.GetTransferSummary(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTransferSummaryResponse(rsp)
}

// ParseListMetricsFilesResponse parses an HTTP response from a ListMetricsFilesWithResponse call
func ParseListMetricsFilesResponse(rsp *http.Response) (*ListMetricsFilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListMetricsFilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MetricsListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetMetricsFileResponse parses an HTTP response from a GetMetricsFileWithResponse call
func ParseGetMetricsFileResponse(rsp *http.Response) (*GetMetricsFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMetricsFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FileUsage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRecordProviderTransferEventsResponse parses an HTTP response from a RecordProviderTransferEventsWithResponse call
func ParseRecordProviderTransferEventsResponse(rsp *http.Response) (*RecordProviderTransferEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RecordProviderTransferEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest TransferEventsRecordedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetMetricsSummaryResponse parses an HTTP response from a GetMetricsSummaryWithResponse call
func ParseGetMetricsSummaryResponse(rsp *http.Response) (*GetMetricsSummaryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMetricsSummaryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FileUsageSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetTransferBreakdownResponse parses an HTTP response from a GetTransferBreakdownWithResponse call
func ParseGetTransferBreakdownResponse(rsp *http.Response) (*GetTransferBreakdownResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTransferBreakdownResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransferBreakdownResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetTransferSummaryResponse parses an HTTP response from a GetTransferSummaryWithResponse call
func ParseGetTransferSummaryResponse(rsp *http.Response) (*GetTransferSummaryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTransferSummaryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TransferAttributionSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
