/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadRequest{}

// UploadRequest struct for UploadRequest
type UploadRequest struct {
	// Array of upload requests for files
	Requests []UploadRequestObject `json:"requests"`
	// Optional array of GA4GH Passport JWTs for authorization
	Passports []string `json:"passports,omitempty"`
}

type _UploadRequest UploadRequest

// NewUploadRequest instantiates a new UploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadRequest(requests []UploadRequestObject) *UploadRequest {
	this := UploadRequest{}
	this.Requests = requests
	return &this
}

// NewUploadRequestWithDefaults instantiates a new UploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadRequestWithDefaults() *UploadRequest {
	this := UploadRequest{}
	return &this
}

// GetRequests returns the Requests field value
func (o *UploadRequest) GetRequests() []UploadRequestObject {
	if o == nil {
		var ret []UploadRequestObject
		return ret
	}

	return o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value
// and a boolean to check if the value has been set.
func (o *UploadRequest) GetRequestsOk() ([]UploadRequestObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Requests, true
}

// SetRequests sets field value
func (o *UploadRequest) SetRequests(v []UploadRequestObject) {
	o.Requests = v
}

// GetPassports returns the Passports field value if set, zero value otherwise.
func (o *UploadRequest) GetPassports() []string {
	if o == nil || IsNil(o.Passports) {
		var ret []string
		return ret
	}
	return o.Passports
}

// GetPassportsOk returns a tuple with the Passports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadRequest) GetPassportsOk() ([]string, bool) {
	if o == nil || IsNil(o.Passports) {
		return nil, false
	}
	return o.Passports, true
}

// HasPassports returns a boolean if a field has been set.
func (o *UploadRequest) HasPassports() bool {
	if o != nil && !IsNil(o.Passports) {
		return true
	}

	return false
}

// SetPassports gets a reference to the given []string and assigns it to the Passports field.
func (o *UploadRequest) SetPassports(v []string) {
	o.Passports = v
}

func (o UploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requests"] = o.Requests
	if !IsNil(o.Passports) {
		toSerialize["passports"] = o.Passports
	}
	return toSerialize, nil
}

func (o *UploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requests",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadRequest := _UploadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadRequest)

	if err != nil {
		return err
	}

	*o = UploadRequest(varUploadRequest)

	return err
}

type NullableUploadRequest struct {
	value *UploadRequest
	isSet bool
}

func (v NullableUploadRequest) Get() *UploadRequest {
	return v.value
}

func (v *NullableUploadRequest) Set(val *UploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadRequest(val *UploadRequest) *NullableUploadRequest {
	return &NullableUploadRequest{value: val, isSet: true}
}

func (v NullableUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


