/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccessMethodAccessUrl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessMethodAccessUrl{}

// AccessMethodAccessUrl struct for AccessMethodAccessUrl
type AccessMethodAccessUrl struct {
	// A fully resolvable URL that can be used to fetch the actual object bytes.
	Url string `json:"url"`
	// An optional list of headers to include in the HTTP request to `url`. These headers can be used to provide auth tokens required to fetch the object bytes.
	Headers []string `json:"headers,omitempty"`
}

type _AccessMethodAccessUrl AccessMethodAccessUrl

// NewAccessMethodAccessUrl instantiates a new AccessMethodAccessUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessMethodAccessUrl(url string) *AccessMethodAccessUrl {
	this := AccessMethodAccessUrl{}
	this.Url = url
	return &this
}

// NewAccessMethodAccessUrlWithDefaults instantiates a new AccessMethodAccessUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessMethodAccessUrlWithDefaults() *AccessMethodAccessUrl {
	this := AccessMethodAccessUrl{}
	return &this
}

// GetUrl returns the Url field value
func (o *AccessMethodAccessUrl) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *AccessMethodAccessUrl) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *AccessMethodAccessUrl) SetUrl(v string) {
	o.Url = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *AccessMethodAccessUrl) GetHeaders() []string {
	if o == nil || IsNil(o.Headers) {
		var ret []string
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessMethodAccessUrl) GetHeadersOk() ([]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *AccessMethodAccessUrl) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []string and assigns it to the Headers field.
func (o *AccessMethodAccessUrl) SetHeaders(v []string) {
	o.Headers = v
}

func (o AccessMethodAccessUrl) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessMethodAccessUrl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	return toSerialize, nil
}

func (o *AccessMethodAccessUrl) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessMethodAccessUrl := _AccessMethodAccessUrl{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccessMethodAccessUrl)

	if err != nil {
		return err
	}

	*o = AccessMethodAccessUrl(varAccessMethodAccessUrl)

	return err
}

type NullableAccessMethodAccessUrl struct {
	value *AccessMethodAccessUrl
	isSet bool
}

func (v NullableAccessMethodAccessUrl) Get() *AccessMethodAccessUrl {
	return v.value
}

func (v *NullableAccessMethodAccessUrl) Set(val *AccessMethodAccessUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessMethodAccessUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessMethodAccessUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessMethodAccessUrl(val *AccessMethodAccessUrl) *NullableAccessMethodAccessUrl {
	return &NullableAccessMethodAccessUrl{value: val, isSet: true}
}

func (v NullableAccessMethodAccessUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessMethodAccessUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


