/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DrsObjectCandidate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DrsObjectCandidate{}

// DrsObjectCandidate struct for DrsObjectCandidate
type DrsObjectCandidate struct {
	// A string that can be used to name a `DrsObject`. This string is made up of uppercase and lowercase letters, decimal digits, hyphen, period, and underscore [A-Za-z0-9.-_]. See http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282[portable filenames].
	Name *string `json:"name,omitempty"`
	// For blobs, the blob size in bytes. For bundles, the cumulative size, in bytes, of items in the `contents` field.
	Size int64 `json:"size"`
	// A string representing a version. (Some systems may use checksum, a RFC3339 timestamp, or an incrementing version number.)
	Version *string `json:"version,omitempty"`
	// A string providing the mime-type of the `DrsObject`.
	MimeType *string `json:"mime_type,omitempty"`
	// The checksum of the `DrsObject`. At least one checksum must be provided. For blobs, the checksum is computed over the bytes in the blob. For bundles, the checksum is computed over a sorted concatenation of the checksums of its top-level contained objects (not recursive, names not included). The list of checksums is sorted alphabetically (hex-code) before concatenation and a further checksum is performed on the concatenated checksum value. For example, if a bundle contains blobs with the following checksums: md5(blob1) = 72794b6d md5(blob2) = 5e089d29 Then the checksum of the bundle is: md5( concat( sort( md5(blob1), md5(blob2) ) ) ) = md5( concat( sort( 72794b6d, 5e089d29 ) ) ) = md5( concat( 5e089d29, 72794b6d ) ) = md5( 5e089d2972794b6d ) = f7a29a04
	Checksums []Checksum `json:"checksums"`
	// The list of access methods that can be used to fetch the `DrsObject`. Required for single blobs; optional for bundles.
	AccessMethods []AccessMethod `json:"access_methods,omitempty"`
	// If not set, this `DrsObject` is a single blob. If set, this `DrsObject` is a bundle containing the listed `ContentsObject` s (some of which may be further nested).
	Contents []ContentsObject `json:"contents,omitempty"`
	// A human readable description of the `DrsObject`.
	Description *string `json:"description,omitempty"`
	// A list of strings that can be used to find other metadata about this `DrsObject` from external metadata sources. These aliases can be used to represent secondary accession numbers or external GUIDs.
	Aliases []string `json:"aliases,omitempty"`
}

type _DrsObjectCandidate DrsObjectCandidate

// NewDrsObjectCandidate instantiates a new DrsObjectCandidate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDrsObjectCandidate(size int64, checksums []Checksum) *DrsObjectCandidate {
	this := DrsObjectCandidate{}
	this.Size = size
	this.Checksums = checksums
	return &this
}

// NewDrsObjectCandidateWithDefaults instantiates a new DrsObjectCandidate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDrsObjectCandidateWithDefaults() *DrsObjectCandidate {
	this := DrsObjectCandidate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DrsObjectCandidate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsObjectCandidate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DrsObjectCandidate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DrsObjectCandidate) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value
func (o *DrsObjectCandidate) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *DrsObjectCandidate) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *DrsObjectCandidate) SetSize(v int64) {
	o.Size = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *DrsObjectCandidate) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsObjectCandidate) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *DrsObjectCandidate) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *DrsObjectCandidate) SetVersion(v string) {
	o.Version = &v
}

// GetMimeType returns the MimeType field value if set, zero value otherwise.
func (o *DrsObjectCandidate) GetMimeType() string {
	if o == nil || IsNil(o.MimeType) {
		var ret string
		return ret
	}
	return *o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsObjectCandidate) GetMimeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MimeType) {
		return nil, false
	}
	return o.MimeType, true
}

// HasMimeType returns a boolean if a field has been set.
func (o *DrsObjectCandidate) HasMimeType() bool {
	if o != nil && !IsNil(o.MimeType) {
		return true
	}

	return false
}

// SetMimeType gets a reference to the given string and assigns it to the MimeType field.
func (o *DrsObjectCandidate) SetMimeType(v string) {
	o.MimeType = &v
}

// GetChecksums returns the Checksums field value
func (o *DrsObjectCandidate) GetChecksums() []Checksum {
	if o == nil {
		var ret []Checksum
		return ret
	}

	return o.Checksums
}

// GetChecksumsOk returns a tuple with the Checksums field value
// and a boolean to check if the value has been set.
func (o *DrsObjectCandidate) GetChecksumsOk() ([]Checksum, bool) {
	if o == nil {
		return nil, false
	}
	return o.Checksums, true
}

// SetChecksums sets field value
func (o *DrsObjectCandidate) SetChecksums(v []Checksum) {
	o.Checksums = v
}

// GetAccessMethods returns the AccessMethods field value if set, zero value otherwise.
func (o *DrsObjectCandidate) GetAccessMethods() []AccessMethod {
	if o == nil || IsNil(o.AccessMethods) {
		var ret []AccessMethod
		return ret
	}
	return o.AccessMethods
}

// GetAccessMethodsOk returns a tuple with the AccessMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsObjectCandidate) GetAccessMethodsOk() ([]AccessMethod, bool) {
	if o == nil || IsNil(o.AccessMethods) {
		return nil, false
	}
	return o.AccessMethods, true
}

// HasAccessMethods returns a boolean if a field has been set.
func (o *DrsObjectCandidate) HasAccessMethods() bool {
	if o != nil && !IsNil(o.AccessMethods) {
		return true
	}

	return false
}

// SetAccessMethods gets a reference to the given []AccessMethod and assigns it to the AccessMethods field.
func (o *DrsObjectCandidate) SetAccessMethods(v []AccessMethod) {
	o.AccessMethods = v
}

// GetContents returns the Contents field value if set, zero value otherwise.
func (o *DrsObjectCandidate) GetContents() []ContentsObject {
	if o == nil || IsNil(o.Contents) {
		var ret []ContentsObject
		return ret
	}
	return o.Contents
}

// GetContentsOk returns a tuple with the Contents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsObjectCandidate) GetContentsOk() ([]ContentsObject, bool) {
	if o == nil || IsNil(o.Contents) {
		return nil, false
	}
	return o.Contents, true
}

// HasContents returns a boolean if a field has been set.
func (o *DrsObjectCandidate) HasContents() bool {
	if o != nil && !IsNil(o.Contents) {
		return true
	}

	return false
}

// SetContents gets a reference to the given []ContentsObject and assigns it to the Contents field.
func (o *DrsObjectCandidate) SetContents(v []ContentsObject) {
	o.Contents = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DrsObjectCandidate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsObjectCandidate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DrsObjectCandidate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DrsObjectCandidate) SetDescription(v string) {
	o.Description = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *DrsObjectCandidate) GetAliases() []string {
	if o == nil || IsNil(o.Aliases) {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsObjectCandidate) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *DrsObjectCandidate) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *DrsObjectCandidate) SetAliases(v []string) {
	o.Aliases = v
}

func (o DrsObjectCandidate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DrsObjectCandidate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["size"] = o.Size
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.MimeType) {
		toSerialize["mime_type"] = o.MimeType
	}
	toSerialize["checksums"] = o.Checksums
	if !IsNil(o.AccessMethods) {
		toSerialize["access_methods"] = o.AccessMethods
	}
	if !IsNil(o.Contents) {
		toSerialize["contents"] = o.Contents
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	return toSerialize, nil
}

func (o *DrsObjectCandidate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"size",
		"checksums",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDrsObjectCandidate := _DrsObjectCandidate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDrsObjectCandidate)

	if err != nil {
		return err
	}

	*o = DrsObjectCandidate(varDrsObjectCandidate)

	return err
}

type NullableDrsObjectCandidate struct {
	value *DrsObjectCandidate
	isSet bool
}

func (v NullableDrsObjectCandidate) Get() *DrsObjectCandidate {
	return v.value
}

func (v *NullableDrsObjectCandidate) Set(val *DrsObjectCandidate) {
	v.value = val
	v.isSet = true
}

func (v NullableDrsObjectCandidate) IsSet() bool {
	return v.isSet
}

func (v *NullableDrsObjectCandidate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDrsObjectCandidate(val *DrsObjectCandidate) *NullableDrsObjectCandidate {
	return &NullableDrsObjectCandidate{value: val, isSet: true}
}

func (v NullableDrsObjectCandidate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDrsObjectCandidate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


