/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
)

// checks if the AccessMethodAuthorizations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessMethodAuthorizations{}

// AccessMethodAuthorizations struct for AccessMethodAuthorizations
type AccessMethodAuthorizations struct {
	DrsObjectId *string `json:"drs_object_id,omitempty"`
	// An Optional list of support authorization types. More than one can be supported and tried in sequence. Defaults to `None` if empty or missing.
	SupportedTypes []string `json:"supported_types,omitempty"`
	// If authorizations contain `PassportAuth` this is a required list of visa issuers (as found in a visa's `iss` claim) that may authorize access to this object. The caller must only provide passports that contain visas from this list. It is strongly recommended that the caller validate that it is appropriate to send the requested passport/visa to the DRS server to mitigate attacks by malicious DRS servers requesting credentials they should not have.
	PassportAuthIssuers []string `json:"passport_auth_issuers,omitempty"`
	// If authorizations contain `BearerAuth` this is an optional list of issuers that may authorize access to this object. The caller must provide a token from one of these issuers. If this is empty or missing it assumed the caller knows which token to send via other means. It is strongly recommended that the caller validate that it is appropriate to send the requested token to the DRS server to mitigate attacks by malicious DRS servers requesting credentials they should not have.
	BearerAuthIssuers []string `json:"bearer_auth_issuers,omitempty"`
}

// NewAccessMethodAuthorizations instantiates a new AccessMethodAuthorizations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessMethodAuthorizations() *AccessMethodAuthorizations {
	this := AccessMethodAuthorizations{}
	return &this
}

// NewAccessMethodAuthorizationsWithDefaults instantiates a new AccessMethodAuthorizations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessMethodAuthorizationsWithDefaults() *AccessMethodAuthorizations {
	this := AccessMethodAuthorizations{}
	return &this
}

// GetDrsObjectId returns the DrsObjectId field value if set, zero value otherwise.
func (o *AccessMethodAuthorizations) GetDrsObjectId() string {
	if o == nil || IsNil(o.DrsObjectId) {
		var ret string
		return ret
	}
	return *o.DrsObjectId
}

// GetDrsObjectIdOk returns a tuple with the DrsObjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessMethodAuthorizations) GetDrsObjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.DrsObjectId) {
		return nil, false
	}
	return o.DrsObjectId, true
}

// HasDrsObjectId returns a boolean if a field has been set.
func (o *AccessMethodAuthorizations) HasDrsObjectId() bool {
	if o != nil && !IsNil(o.DrsObjectId) {
		return true
	}

	return false
}

// SetDrsObjectId gets a reference to the given string and assigns it to the DrsObjectId field.
func (o *AccessMethodAuthorizations) SetDrsObjectId(v string) {
	o.DrsObjectId = &v
}

// GetSupportedTypes returns the SupportedTypes field value if set, zero value otherwise.
func (o *AccessMethodAuthorizations) GetSupportedTypes() []string {
	if o == nil || IsNil(o.SupportedTypes) {
		var ret []string
		return ret
	}
	return o.SupportedTypes
}

// GetSupportedTypesOk returns a tuple with the SupportedTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessMethodAuthorizations) GetSupportedTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.SupportedTypes) {
		return nil, false
	}
	return o.SupportedTypes, true
}

// HasSupportedTypes returns a boolean if a field has been set.
func (o *AccessMethodAuthorizations) HasSupportedTypes() bool {
	if o != nil && !IsNil(o.SupportedTypes) {
		return true
	}

	return false
}

// SetSupportedTypes gets a reference to the given []string and assigns it to the SupportedTypes field.
func (o *AccessMethodAuthorizations) SetSupportedTypes(v []string) {
	o.SupportedTypes = v
}

// GetPassportAuthIssuers returns the PassportAuthIssuers field value if set, zero value otherwise.
func (o *AccessMethodAuthorizations) GetPassportAuthIssuers() []string {
	if o == nil || IsNil(o.PassportAuthIssuers) {
		var ret []string
		return ret
	}
	return o.PassportAuthIssuers
}

// GetPassportAuthIssuersOk returns a tuple with the PassportAuthIssuers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessMethodAuthorizations) GetPassportAuthIssuersOk() ([]string, bool) {
	if o == nil || IsNil(o.PassportAuthIssuers) {
		return nil, false
	}
	return o.PassportAuthIssuers, true
}

// HasPassportAuthIssuers returns a boolean if a field has been set.
func (o *AccessMethodAuthorizations) HasPassportAuthIssuers() bool {
	if o != nil && !IsNil(o.PassportAuthIssuers) {
		return true
	}

	return false
}

// SetPassportAuthIssuers gets a reference to the given []string and assigns it to the PassportAuthIssuers field.
func (o *AccessMethodAuthorizations) SetPassportAuthIssuers(v []string) {
	o.PassportAuthIssuers = v
}

// GetBearerAuthIssuers returns the BearerAuthIssuers field value if set, zero value otherwise.
func (o *AccessMethodAuthorizations) GetBearerAuthIssuers() []string {
	if o == nil || IsNil(o.BearerAuthIssuers) {
		var ret []string
		return ret
	}
	return o.BearerAuthIssuers
}

// GetBearerAuthIssuersOk returns a tuple with the BearerAuthIssuers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessMethodAuthorizations) GetBearerAuthIssuersOk() ([]string, bool) {
	if o == nil || IsNil(o.BearerAuthIssuers) {
		return nil, false
	}
	return o.BearerAuthIssuers, true
}

// HasBearerAuthIssuers returns a boolean if a field has been set.
func (o *AccessMethodAuthorizations) HasBearerAuthIssuers() bool {
	if o != nil && !IsNil(o.BearerAuthIssuers) {
		return true
	}

	return false
}

// SetBearerAuthIssuers gets a reference to the given []string and assigns it to the BearerAuthIssuers field.
func (o *AccessMethodAuthorizations) SetBearerAuthIssuers(v []string) {
	o.BearerAuthIssuers = v
}

func (o AccessMethodAuthorizations) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessMethodAuthorizations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DrsObjectId) {
		toSerialize["drs_object_id"] = o.DrsObjectId
	}
	if !IsNil(o.SupportedTypes) {
		toSerialize["supported_types"] = o.SupportedTypes
	}
	if !IsNil(o.PassportAuthIssuers) {
		toSerialize["passport_auth_issuers"] = o.PassportAuthIssuers
	}
	if !IsNil(o.BearerAuthIssuers) {
		toSerialize["bearer_auth_issuers"] = o.BearerAuthIssuers
	}
	return toSerialize, nil
}

type NullableAccessMethodAuthorizations struct {
	value *AccessMethodAuthorizations
	isSet bool
}

func (v NullableAccessMethodAuthorizations) Get() *AccessMethodAuthorizations {
	return v.value
}

func (v *NullableAccessMethodAuthorizations) Set(val *AccessMethodAuthorizations) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessMethodAuthorizations) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessMethodAuthorizations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessMethodAuthorizations(val *AccessMethodAuthorizations) *NullableAccessMethodAuthorizations {
	return &NullableAccessMethodAuthorizations{value: val, isSet: true}
}

func (v NullableAccessMethodAuthorizations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessMethodAuthorizations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


