/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
)

// checks if the Summary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Summary{}

// Summary A summary of what was resolved.
type Summary struct {
	// Number of items requested.
	Requested *int32 `json:"requested,omitempty"`
	// Number of objects resolved.
	Resolved *int32 `json:"resolved,omitempty"`
	// Number of objects not resolved.
	Unresolved *int32 `json:"unresolved,omitempty"`
}

// NewSummary instantiates a new Summary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummary() *Summary {
	this := Summary{}
	return &this
}

// NewSummaryWithDefaults instantiates a new Summary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryWithDefaults() *Summary {
	this := Summary{}
	return &this
}

// GetRequested returns the Requested field value if set, zero value otherwise.
func (o *Summary) GetRequested() int32 {
	if o == nil || IsNil(o.Requested) {
		var ret int32
		return ret
	}
	return *o.Requested
}

// GetRequestedOk returns a tuple with the Requested field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Summary) GetRequestedOk() (*int32, bool) {
	if o == nil || IsNil(o.Requested) {
		return nil, false
	}
	return o.Requested, true
}

// HasRequested returns a boolean if a field has been set.
func (o *Summary) HasRequested() bool {
	if o != nil && !IsNil(o.Requested) {
		return true
	}

	return false
}

// SetRequested gets a reference to the given int32 and assigns it to the Requested field.
func (o *Summary) SetRequested(v int32) {
	o.Requested = &v
}

// GetResolved returns the Resolved field value if set, zero value otherwise.
func (o *Summary) GetResolved() int32 {
	if o == nil || IsNil(o.Resolved) {
		var ret int32
		return ret
	}
	return *o.Resolved
}

// GetResolvedOk returns a tuple with the Resolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Summary) GetResolvedOk() (*int32, bool) {
	if o == nil || IsNil(o.Resolved) {
		return nil, false
	}
	return o.Resolved, true
}

// HasResolved returns a boolean if a field has been set.
func (o *Summary) HasResolved() bool {
	if o != nil && !IsNil(o.Resolved) {
		return true
	}

	return false
}

// SetResolved gets a reference to the given int32 and assigns it to the Resolved field.
func (o *Summary) SetResolved(v int32) {
	o.Resolved = &v
}

// GetUnresolved returns the Unresolved field value if set, zero value otherwise.
func (o *Summary) GetUnresolved() int32 {
	if o == nil || IsNil(o.Unresolved) {
		var ret int32
		return ret
	}
	return *o.Unresolved
}

// GetUnresolvedOk returns a tuple with the Unresolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Summary) GetUnresolvedOk() (*int32, bool) {
	if o == nil || IsNil(o.Unresolved) {
		return nil, false
	}
	return o.Unresolved, true
}

// HasUnresolved returns a boolean if a field has been set.
func (o *Summary) HasUnresolved() bool {
	if o != nil && !IsNil(o.Unresolved) {
		return true
	}

	return false
}

// SetUnresolved gets a reference to the given int32 and assigns it to the Unresolved field.
func (o *Summary) SetUnresolved(v int32) {
	o.Unresolved = &v
}

func (o Summary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Summary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requested) {
		toSerialize["requested"] = o.Requested
	}
	if !IsNil(o.Resolved) {
		toSerialize["resolved"] = o.Resolved
	}
	if !IsNil(o.Unresolved) {
		toSerialize["unresolved"] = o.Unresolved
	}
	return toSerialize, nil
}

type NullableSummary struct {
	value *Summary
	isSet bool
}

func (v NullableSummary) Get() *Summary {
	return v.value
}

func (v *NullableSummary) Set(val *Summary) {
	v.value = val
	v.isSet = true
}

func (v NullableSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummary(val *Summary) *NullableSummary {
	return &NullableSummary{value: val, isSet: true}
}

func (v NullableSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


