/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
)

// checks if the BulkObjectAccessId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkObjectAccessId{}

// BulkObjectAccessId The object that contains object_id/access_id tuples
type BulkObjectAccessId struct {
	Passports []string `json:"passports,omitempty"`
	BulkObjectAccessIds []BulkObjectAccessIdBulkObjectAccessIdsInner `json:"bulk_object_access_ids,omitempty"`
}

// NewBulkObjectAccessId instantiates a new BulkObjectAccessId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkObjectAccessId() *BulkObjectAccessId {
	this := BulkObjectAccessId{}
	return &this
}

// NewBulkObjectAccessIdWithDefaults instantiates a new BulkObjectAccessId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkObjectAccessIdWithDefaults() *BulkObjectAccessId {
	this := BulkObjectAccessId{}
	return &this
}

// GetPassports returns the Passports field value if set, zero value otherwise.
func (o *BulkObjectAccessId) GetPassports() []string {
	if o == nil || IsNil(o.Passports) {
		var ret []string
		return ret
	}
	return o.Passports
}

// GetPassportsOk returns a tuple with the Passports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkObjectAccessId) GetPassportsOk() ([]string, bool) {
	if o == nil || IsNil(o.Passports) {
		return nil, false
	}
	return o.Passports, true
}

// HasPassports returns a boolean if a field has been set.
func (o *BulkObjectAccessId) HasPassports() bool {
	if o != nil && !IsNil(o.Passports) {
		return true
	}

	return false
}

// SetPassports gets a reference to the given []string and assigns it to the Passports field.
func (o *BulkObjectAccessId) SetPassports(v []string) {
	o.Passports = v
}

// GetBulkObjectAccessIds returns the BulkObjectAccessIds field value if set, zero value otherwise.
func (o *BulkObjectAccessId) GetBulkObjectAccessIds() []BulkObjectAccessIdBulkObjectAccessIdsInner {
	if o == nil || IsNil(o.BulkObjectAccessIds) {
		var ret []BulkObjectAccessIdBulkObjectAccessIdsInner
		return ret
	}
	return o.BulkObjectAccessIds
}

// GetBulkObjectAccessIdsOk returns a tuple with the BulkObjectAccessIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkObjectAccessId) GetBulkObjectAccessIdsOk() ([]BulkObjectAccessIdBulkObjectAccessIdsInner, bool) {
	if o == nil || IsNil(o.BulkObjectAccessIds) {
		return nil, false
	}
	return o.BulkObjectAccessIds, true
}

// HasBulkObjectAccessIds returns a boolean if a field has been set.
func (o *BulkObjectAccessId) HasBulkObjectAccessIds() bool {
	if o != nil && !IsNil(o.BulkObjectAccessIds) {
		return true
	}

	return false
}

// SetBulkObjectAccessIds gets a reference to the given []BulkObjectAccessIdBulkObjectAccessIdsInner and assigns it to the BulkObjectAccessIds field.
func (o *BulkObjectAccessId) SetBulkObjectAccessIds(v []BulkObjectAccessIdBulkObjectAccessIdsInner) {
	o.BulkObjectAccessIds = v
}

func (o BulkObjectAccessId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkObjectAccessId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Passports) {
		toSerialize["passports"] = o.Passports
	}
	if !IsNil(o.BulkObjectAccessIds) {
		toSerialize["bulk_object_access_ids"] = o.BulkObjectAccessIds
	}
	return toSerialize, nil
}

type NullableBulkObjectAccessId struct {
	value *BulkObjectAccessId
	isSet bool
}

func (v NullableBulkObjectAccessId) Get() *BulkObjectAccessId {
	return v.value
}

func (v *NullableBulkObjectAccessId) Set(val *BulkObjectAccessId) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkObjectAccessId) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkObjectAccessId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkObjectAccessId(val *BulkObjectAccessId) *NullableBulkObjectAccessId {
	return &NullableBulkObjectAccessId{value: val, isSet: true}
}

func (v NullableBulkObjectAccessId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkObjectAccessId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


