/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterObjects201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterObjects201Response{}

// RegisterObjects201Response struct for RegisterObjects201Response
type RegisterObjects201Response struct {
	// Array of registered DRS objects in the same order as the candidates in the request
	Objects []DrsObject `json:"objects"`
}

type _RegisterObjects201Response RegisterObjects201Response

// NewRegisterObjects201Response instantiates a new RegisterObjects201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterObjects201Response(objects []DrsObject) *RegisterObjects201Response {
	this := RegisterObjects201Response{}
	this.Objects = objects
	return &this
}

// NewRegisterObjects201ResponseWithDefaults instantiates a new RegisterObjects201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterObjects201ResponseWithDefaults() *RegisterObjects201Response {
	this := RegisterObjects201Response{}
	return &this
}

// GetObjects returns the Objects field value
func (o *RegisterObjects201Response) GetObjects() []DrsObject {
	if o == nil {
		var ret []DrsObject
		return ret
	}

	return o.Objects
}

// GetObjectsOk returns a tuple with the Objects field value
// and a boolean to check if the value has been set.
func (o *RegisterObjects201Response) GetObjectsOk() ([]DrsObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Objects, true
}

// SetObjects sets field value
func (o *RegisterObjects201Response) SetObjects(v []DrsObject) {
	o.Objects = v
}

func (o RegisterObjects201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterObjects201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["objects"] = o.Objects
	return toSerialize, nil
}

func (o *RegisterObjects201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objects",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterObjects201Response := _RegisterObjects201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterObjects201Response)

	if err != nil {
		return err
	}

	*o = RegisterObjects201Response(varRegisterObjects201Response)

	return err
}

type NullableRegisterObjects201Response struct {
	value *RegisterObjects201Response
	isSet bool
}

func (v NullableRegisterObjects201Response) Get() *RegisterObjects201Response {
	return v.value
}

func (v *NullableRegisterObjects201Response) Set(val *RegisterObjects201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterObjects201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterObjects201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterObjects201Response(val *RegisterObjects201Response) *NullableRegisterObjects201Response {
	return &NullableRegisterObjects201Response{value: val, isSet: true}
}

func (v NullableRegisterObjects201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterObjects201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


