/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceOrganization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceOrganization{}

// ServiceOrganization Organization providing the service
type ServiceOrganization struct {
	// Name of the organization responsible for the service
	Name string `json:"name"`
	// URL of the website of the organization (RFC 3986 format)
	Url string `json:"url"`
}

type _ServiceOrganization ServiceOrganization

// NewServiceOrganization instantiates a new ServiceOrganization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceOrganization(name string, url string) *ServiceOrganization {
	this := ServiceOrganization{}
	this.Name = name
	this.Url = url
	return &this
}

// NewServiceOrganizationWithDefaults instantiates a new ServiceOrganization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceOrganizationWithDefaults() *ServiceOrganization {
	this := ServiceOrganization{}
	return &this
}

// GetName returns the Name field value
func (o *ServiceOrganization) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceOrganization) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceOrganization) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *ServiceOrganization) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ServiceOrganization) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ServiceOrganization) SetUrl(v string) {
	o.Url = v
}

func (o ServiceOrganization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceOrganization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ServiceOrganization) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceOrganization := _ServiceOrganization{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceOrganization)

	if err != nil {
		return err
	}

	*o = ServiceOrganization(varServiceOrganization)

	return err
}

type NullableServiceOrganization struct {
	value *ServiceOrganization
	isSet bool
}

func (v NullableServiceOrganization) Get() *ServiceOrganization {
	return v.value
}

func (v *NullableServiceOrganization) Set(val *ServiceOrganization) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceOrganization(val *ServiceOrganization) *NullableServiceOrganization {
	return &NullableServiceOrganization{value: val, isSet: true}
}

func (v NullableServiceOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


