/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DrsServiceDrs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DrsServiceDrs{}

// DrsServiceDrs struct for DrsServiceDrs
type DrsServiceDrs struct {
	// The max length the bulk request endpoints can handle (>= 1) before generating a 413 error e.g. how long can the arrays bulk_object_ids and bulk_object_access_ids be for this server.
	MaxBulkRequestLength int32 `json:"maxBulkRequestLength"`
	// The total number of objects in this DRS service.
	ObjectCount *int32 `json:"objectCount,omitempty"`
	// The total size of all objects in this DRS service in bytes.  As a general best practice, file bytes are counted for each unique file and not cloud mirrors or other redundant copies.
	TotalObjectSize *int32 `json:"totalObjectSize,omitempty"`
	// Indicates whether this DRS server supports upload request operations via the `/upload-request` endpoint. If true, clients can request upload methods and credentials for uploading files. If false or missing, the server does not support upload request coordination.
	UploadRequestSupported *bool `json:"uploadRequestSupported,omitempty"`
	// Indicates whether this DRS server supports object registration operations via the `/objects/register` endpoint. If true, clients can register uploaded files or existing data as DRS objects. If false or missing, the server does not support object registration.
	ObjectRegistrationSupported *bool `json:"objectRegistrationSupported,omitempty"`
	// List of upload methods supported by this DRS server. Only present when uploadRequestSupported is true. Clients can use this information to determine which upload methods are available before making upload requests. - **s3**: Direct S3 upload with temporary AWS credentials - **gs**: Google Cloud Storage upload with access tokens   - **https**: Presigned POST URL for HTTP uploads - **ftp**: File Transfer Protocol uploads - **sftp**: Secure File Transfer Protocol uploads - **gsiftp**: GridFTP secure file transfer - **globus**: Globus transfer service for high-performance data movement
	SupportedUploadMethods []string `json:"supportedUploadMethods,omitempty"`
	// Maximum file size in bytes that can be uploaded via the upload endpoints. Only present when uploadRequestSupported is true. If not specified, there is no explicit size limit.
	MaxUploadSize *int64 `json:"maxUploadSize,omitempty"`
	// Maximum number of files that can be included in a single upload request. Only present when uploadRequestSupported is true. If not specified, defaults to the same value as maxBulkRequestLength.
	MaxUploadRequestLength *int32 `json:"maxUploadRequestLength,omitempty"`
	// Maximum number of candidate objects that can be included in a single registration request. Only present when objectRegistrationSupported is true. If not specified, defaults to the same value as maxBulkRequestLength.
	MaxRegisterRequestLength *int32 `json:"maxRegisterRequestLength,omitempty"`
	// Indicates whether this DRS server validates uploaded file checksums against the provided metadata. If true, the server will verify that uploaded files match their declared checksums and may reject uploads with mismatches. If false or missing, the server does not perform checksum validation and relies on client-provided metadata. Only present when uploadRequestSupported or objectRegistrationSupported is true.
	ValidateUploadChecksums *bool `json:"validateUploadChecksums,omitempty"`
	// Indicates whether this DRS server validates uploaded file sizes against the provided metadata. If true, the server will verify that uploaded files match their declared sizes and may reject uploads with mismatches. If false or missing, the server does not perform file size validation and relies on client-provided metadata. Only present when uploadRequestSupported or objectRegistrationSupported is true.
	ValidateUploadFileSizes *bool `json:"validateUploadFileSizes,omitempty"`
	// Indicates whether this DRS server supports storing files from the same upload request under a common prefix or folder structure. If true, the server will organize related files together in storage, enabling bioinformatics workflows that expect co-located files (e.g., CRAM + CRAI, VCF + TBI). If false or missing, the server may distribute files across different storage locations or prefixes. Only present when uploadRequestSupported is true. This feature is particularly valuable for genomics tools like samtools that expect index files to be co-located with data files.
	RelatedFileStorageSupported *bool `json:"relatedFileStorageSupported,omitempty"`
	// Indicates whether this DRS server supports delete operations via the delete endpoints. If true, clients can delete DRS objects using POST requests to `/objects/{object_id}/delete` and `/objects/delete`. If false or missing, the server does not support delete operations and will return 404 for delete endpoint requests. Like upload functionality, delete support is entirely optional and servers remain DRS compliant without it.
	DeleteSupported *bool `json:"deleteSupported,omitempty"`
	// Maximum number of objects that can be deleted in a single bulk delete request via `/objects/delete`. Only present when deleteSupported is true. If not specified when delete is supported, defaults to the same value as maxBulkRequestLength. Servers may enforce lower limits for delete operations compared to other bulk operations for safety reasons.
	MaxBulkDeleteLength *int32 `json:"maxBulkDeleteLength,omitempty"`
	// Indicates whether this DRS server supports attempting to delete underlying storage data when clients request it. If true, the server will attempt to delete both metadata and storage files when `delete_storage_data: true` is specified in delete requests. If false or missing, the server only supports metadata deletion regardless of client request, preserving underlying storage data. Only present when deleteSupported is true. This is a capability flag indicating what the server can attempt, not a default behavior setting. Note: Storage deletion attempts may fail due to permissions, network issues, or storage service errors.
	DeleteStorageDataSupported *bool `json:"deleteStorageDataSupported,omitempty"`
	// Indicates whether this DRS server supports updating access methods for existing objects. If true, clients can update access methods using `/objects/{object_id}/access-methods` and `/objects/access-methods` endpoints. If false or missing, the server does not support access method updates.
	AccessMethodUpdateSupported *bool `json:"accessMethodUpdateSupported,omitempty"`
	// Maximum number of objects that can be updated in a single bulk access method update request. Only present when accessMethodUpdateSupported is true. If not specified, defaults to maxBulkRequestLength.
	MaxBulkAccessMethodUpdateLength *int32 `json:"maxBulkAccessMethodUpdateLength,omitempty"`
	// Indicates whether this DRS server validates new access methods by verifying they point to the same data. If true, the server will attempt to verify checksums/content before updating access methods. If false or missing, the server trusts client-provided access methods without validation. Only present when accessMethodUpdateSupported is true.
	ValidateAccessMethodUpdates *bool `json:"validateAccessMethodUpdates,omitempty"`
}

type _DrsServiceDrs DrsServiceDrs

// NewDrsServiceDrs instantiates a new DrsServiceDrs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDrsServiceDrs(maxBulkRequestLength int32) *DrsServiceDrs {
	this := DrsServiceDrs{}
	this.MaxBulkRequestLength = maxBulkRequestLength
	var uploadRequestSupported bool = false
	this.UploadRequestSupported = &uploadRequestSupported
	var objectRegistrationSupported bool = false
	this.ObjectRegistrationSupported = &objectRegistrationSupported
	var validateUploadChecksums bool = false
	this.ValidateUploadChecksums = &validateUploadChecksums
	var validateUploadFileSizes bool = false
	this.ValidateUploadFileSizes = &validateUploadFileSizes
	var relatedFileStorageSupported bool = false
	this.RelatedFileStorageSupported = &relatedFileStorageSupported
	var deleteSupported bool = false
	this.DeleteSupported = &deleteSupported
	var deleteStorageDataSupported bool = false
	this.DeleteStorageDataSupported = &deleteStorageDataSupported
	var accessMethodUpdateSupported bool = false
	this.AccessMethodUpdateSupported = &accessMethodUpdateSupported
	var validateAccessMethodUpdates bool = false
	this.ValidateAccessMethodUpdates = &validateAccessMethodUpdates
	return &this
}

// NewDrsServiceDrsWithDefaults instantiates a new DrsServiceDrs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDrsServiceDrsWithDefaults() *DrsServiceDrs {
	this := DrsServiceDrs{}
	var uploadRequestSupported bool = false
	this.UploadRequestSupported = &uploadRequestSupported
	var objectRegistrationSupported bool = false
	this.ObjectRegistrationSupported = &objectRegistrationSupported
	var validateUploadChecksums bool = false
	this.ValidateUploadChecksums = &validateUploadChecksums
	var validateUploadFileSizes bool = false
	this.ValidateUploadFileSizes = &validateUploadFileSizes
	var relatedFileStorageSupported bool = false
	this.RelatedFileStorageSupported = &relatedFileStorageSupported
	var deleteSupported bool = false
	this.DeleteSupported = &deleteSupported
	var deleteStorageDataSupported bool = false
	this.DeleteStorageDataSupported = &deleteStorageDataSupported
	var accessMethodUpdateSupported bool = false
	this.AccessMethodUpdateSupported = &accessMethodUpdateSupported
	var validateAccessMethodUpdates bool = false
	this.ValidateAccessMethodUpdates = &validateAccessMethodUpdates
	return &this
}

// GetMaxBulkRequestLength returns the MaxBulkRequestLength field value
func (o *DrsServiceDrs) GetMaxBulkRequestLength() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxBulkRequestLength
}

// GetMaxBulkRequestLengthOk returns a tuple with the MaxBulkRequestLength field value
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetMaxBulkRequestLengthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxBulkRequestLength, true
}

// SetMaxBulkRequestLength sets field value
func (o *DrsServiceDrs) SetMaxBulkRequestLength(v int32) {
	o.MaxBulkRequestLength = v
}

// GetObjectCount returns the ObjectCount field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetObjectCount() int32 {
	if o == nil || IsNil(o.ObjectCount) {
		var ret int32
		return ret
	}
	return *o.ObjectCount
}

// GetObjectCountOk returns a tuple with the ObjectCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetObjectCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ObjectCount) {
		return nil, false
	}
	return o.ObjectCount, true
}

// HasObjectCount returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasObjectCount() bool {
	if o != nil && !IsNil(o.ObjectCount) {
		return true
	}

	return false
}

// SetObjectCount gets a reference to the given int32 and assigns it to the ObjectCount field.
func (o *DrsServiceDrs) SetObjectCount(v int32) {
	o.ObjectCount = &v
}

// GetTotalObjectSize returns the TotalObjectSize field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetTotalObjectSize() int32 {
	if o == nil || IsNil(o.TotalObjectSize) {
		var ret int32
		return ret
	}
	return *o.TotalObjectSize
}

// GetTotalObjectSizeOk returns a tuple with the TotalObjectSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetTotalObjectSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalObjectSize) {
		return nil, false
	}
	return o.TotalObjectSize, true
}

// HasTotalObjectSize returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasTotalObjectSize() bool {
	if o != nil && !IsNil(o.TotalObjectSize) {
		return true
	}

	return false
}

// SetTotalObjectSize gets a reference to the given int32 and assigns it to the TotalObjectSize field.
func (o *DrsServiceDrs) SetTotalObjectSize(v int32) {
	o.TotalObjectSize = &v
}

// GetUploadRequestSupported returns the UploadRequestSupported field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetUploadRequestSupported() bool {
	if o == nil || IsNil(o.UploadRequestSupported) {
		var ret bool
		return ret
	}
	return *o.UploadRequestSupported
}

// GetUploadRequestSupportedOk returns a tuple with the UploadRequestSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetUploadRequestSupportedOk() (*bool, bool) {
	if o == nil || IsNil(o.UploadRequestSupported) {
		return nil, false
	}
	return o.UploadRequestSupported, true
}

// HasUploadRequestSupported returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasUploadRequestSupported() bool {
	if o != nil && !IsNil(o.UploadRequestSupported) {
		return true
	}

	return false
}

// SetUploadRequestSupported gets a reference to the given bool and assigns it to the UploadRequestSupported field.
func (o *DrsServiceDrs) SetUploadRequestSupported(v bool) {
	o.UploadRequestSupported = &v
}

// GetObjectRegistrationSupported returns the ObjectRegistrationSupported field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetObjectRegistrationSupported() bool {
	if o == nil || IsNil(o.ObjectRegistrationSupported) {
		var ret bool
		return ret
	}
	return *o.ObjectRegistrationSupported
}

// GetObjectRegistrationSupportedOk returns a tuple with the ObjectRegistrationSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetObjectRegistrationSupportedOk() (*bool, bool) {
	if o == nil || IsNil(o.ObjectRegistrationSupported) {
		return nil, false
	}
	return o.ObjectRegistrationSupported, true
}

// HasObjectRegistrationSupported returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasObjectRegistrationSupported() bool {
	if o != nil && !IsNil(o.ObjectRegistrationSupported) {
		return true
	}

	return false
}

// SetObjectRegistrationSupported gets a reference to the given bool and assigns it to the ObjectRegistrationSupported field.
func (o *DrsServiceDrs) SetObjectRegistrationSupported(v bool) {
	o.ObjectRegistrationSupported = &v
}

// GetSupportedUploadMethods returns the SupportedUploadMethods field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetSupportedUploadMethods() []string {
	if o == nil || IsNil(o.SupportedUploadMethods) {
		var ret []string
		return ret
	}
	return o.SupportedUploadMethods
}

// GetSupportedUploadMethodsOk returns a tuple with the SupportedUploadMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetSupportedUploadMethodsOk() ([]string, bool) {
	if o == nil || IsNil(o.SupportedUploadMethods) {
		return nil, false
	}
	return o.SupportedUploadMethods, true
}

// HasSupportedUploadMethods returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasSupportedUploadMethods() bool {
	if o != nil && !IsNil(o.SupportedUploadMethods) {
		return true
	}

	return false
}

// SetSupportedUploadMethods gets a reference to the given []string and assigns it to the SupportedUploadMethods field.
func (o *DrsServiceDrs) SetSupportedUploadMethods(v []string) {
	o.SupportedUploadMethods = v
}

// GetMaxUploadSize returns the MaxUploadSize field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetMaxUploadSize() int64 {
	if o == nil || IsNil(o.MaxUploadSize) {
		var ret int64
		return ret
	}
	return *o.MaxUploadSize
}

// GetMaxUploadSizeOk returns a tuple with the MaxUploadSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetMaxUploadSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxUploadSize) {
		return nil, false
	}
	return o.MaxUploadSize, true
}

// HasMaxUploadSize returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasMaxUploadSize() bool {
	if o != nil && !IsNil(o.MaxUploadSize) {
		return true
	}

	return false
}

// SetMaxUploadSize gets a reference to the given int64 and assigns it to the MaxUploadSize field.
func (o *DrsServiceDrs) SetMaxUploadSize(v int64) {
	o.MaxUploadSize = &v
}

// GetMaxUploadRequestLength returns the MaxUploadRequestLength field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetMaxUploadRequestLength() int32 {
	if o == nil || IsNil(o.MaxUploadRequestLength) {
		var ret int32
		return ret
	}
	return *o.MaxUploadRequestLength
}

// GetMaxUploadRequestLengthOk returns a tuple with the MaxUploadRequestLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetMaxUploadRequestLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxUploadRequestLength) {
		return nil, false
	}
	return o.MaxUploadRequestLength, true
}

// HasMaxUploadRequestLength returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasMaxUploadRequestLength() bool {
	if o != nil && !IsNil(o.MaxUploadRequestLength) {
		return true
	}

	return false
}

// SetMaxUploadRequestLength gets a reference to the given int32 and assigns it to the MaxUploadRequestLength field.
func (o *DrsServiceDrs) SetMaxUploadRequestLength(v int32) {
	o.MaxUploadRequestLength = &v
}

// GetMaxRegisterRequestLength returns the MaxRegisterRequestLength field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetMaxRegisterRequestLength() int32 {
	if o == nil || IsNil(o.MaxRegisterRequestLength) {
		var ret int32
		return ret
	}
	return *o.MaxRegisterRequestLength
}

// GetMaxRegisterRequestLengthOk returns a tuple with the MaxRegisterRequestLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetMaxRegisterRequestLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxRegisterRequestLength) {
		return nil, false
	}
	return o.MaxRegisterRequestLength, true
}

// HasMaxRegisterRequestLength returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasMaxRegisterRequestLength() bool {
	if o != nil && !IsNil(o.MaxRegisterRequestLength) {
		return true
	}

	return false
}

// SetMaxRegisterRequestLength gets a reference to the given int32 and assigns it to the MaxRegisterRequestLength field.
func (o *DrsServiceDrs) SetMaxRegisterRequestLength(v int32) {
	o.MaxRegisterRequestLength = &v
}

// GetValidateUploadChecksums returns the ValidateUploadChecksums field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetValidateUploadChecksums() bool {
	if o == nil || IsNil(o.ValidateUploadChecksums) {
		var ret bool
		return ret
	}
	return *o.ValidateUploadChecksums
}

// GetValidateUploadChecksumsOk returns a tuple with the ValidateUploadChecksums field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetValidateUploadChecksumsOk() (*bool, bool) {
	if o == nil || IsNil(o.ValidateUploadChecksums) {
		return nil, false
	}
	return o.ValidateUploadChecksums, true
}

// HasValidateUploadChecksums returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasValidateUploadChecksums() bool {
	if o != nil && !IsNil(o.ValidateUploadChecksums) {
		return true
	}

	return false
}

// SetValidateUploadChecksums gets a reference to the given bool and assigns it to the ValidateUploadChecksums field.
func (o *DrsServiceDrs) SetValidateUploadChecksums(v bool) {
	o.ValidateUploadChecksums = &v
}

// GetValidateUploadFileSizes returns the ValidateUploadFileSizes field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetValidateUploadFileSizes() bool {
	if o == nil || IsNil(o.ValidateUploadFileSizes) {
		var ret bool
		return ret
	}
	return *o.ValidateUploadFileSizes
}

// GetValidateUploadFileSizesOk returns a tuple with the ValidateUploadFileSizes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetValidateUploadFileSizesOk() (*bool, bool) {
	if o == nil || IsNil(o.ValidateUploadFileSizes) {
		return nil, false
	}
	return o.ValidateUploadFileSizes, true
}

// HasValidateUploadFileSizes returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasValidateUploadFileSizes() bool {
	if o != nil && !IsNil(o.ValidateUploadFileSizes) {
		return true
	}

	return false
}

// SetValidateUploadFileSizes gets a reference to the given bool and assigns it to the ValidateUploadFileSizes field.
func (o *DrsServiceDrs) SetValidateUploadFileSizes(v bool) {
	o.ValidateUploadFileSizes = &v
}

// GetRelatedFileStorageSupported returns the RelatedFileStorageSupported field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetRelatedFileStorageSupported() bool {
	if o == nil || IsNil(o.RelatedFileStorageSupported) {
		var ret bool
		return ret
	}
	return *o.RelatedFileStorageSupported
}

// GetRelatedFileStorageSupportedOk returns a tuple with the RelatedFileStorageSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetRelatedFileStorageSupportedOk() (*bool, bool) {
	if o == nil || IsNil(o.RelatedFileStorageSupported) {
		return nil, false
	}
	return o.RelatedFileStorageSupported, true
}

// HasRelatedFileStorageSupported returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasRelatedFileStorageSupported() bool {
	if o != nil && !IsNil(o.RelatedFileStorageSupported) {
		return true
	}

	return false
}

// SetRelatedFileStorageSupported gets a reference to the given bool and assigns it to the RelatedFileStorageSupported field.
func (o *DrsServiceDrs) SetRelatedFileStorageSupported(v bool) {
	o.RelatedFileStorageSupported = &v
}

// GetDeleteSupported returns the DeleteSupported field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetDeleteSupported() bool {
	if o == nil || IsNil(o.DeleteSupported) {
		var ret bool
		return ret
	}
	return *o.DeleteSupported
}

// GetDeleteSupportedOk returns a tuple with the DeleteSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetDeleteSupportedOk() (*bool, bool) {
	if o == nil || IsNil(o.DeleteSupported) {
		return nil, false
	}
	return o.DeleteSupported, true
}

// HasDeleteSupported returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasDeleteSupported() bool {
	if o != nil && !IsNil(o.DeleteSupported) {
		return true
	}

	return false
}

// SetDeleteSupported gets a reference to the given bool and assigns it to the DeleteSupported field.
func (o *DrsServiceDrs) SetDeleteSupported(v bool) {
	o.DeleteSupported = &v
}

// GetMaxBulkDeleteLength returns the MaxBulkDeleteLength field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetMaxBulkDeleteLength() int32 {
	if o == nil || IsNil(o.MaxBulkDeleteLength) {
		var ret int32
		return ret
	}
	return *o.MaxBulkDeleteLength
}

// GetMaxBulkDeleteLengthOk returns a tuple with the MaxBulkDeleteLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetMaxBulkDeleteLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxBulkDeleteLength) {
		return nil, false
	}
	return o.MaxBulkDeleteLength, true
}

// HasMaxBulkDeleteLength returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasMaxBulkDeleteLength() bool {
	if o != nil && !IsNil(o.MaxBulkDeleteLength) {
		return true
	}

	return false
}

// SetMaxBulkDeleteLength gets a reference to the given int32 and assigns it to the MaxBulkDeleteLength field.
func (o *DrsServiceDrs) SetMaxBulkDeleteLength(v int32) {
	o.MaxBulkDeleteLength = &v
}

// GetDeleteStorageDataSupported returns the DeleteStorageDataSupported field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetDeleteStorageDataSupported() bool {
	if o == nil || IsNil(o.DeleteStorageDataSupported) {
		var ret bool
		return ret
	}
	return *o.DeleteStorageDataSupported
}

// GetDeleteStorageDataSupportedOk returns a tuple with the DeleteStorageDataSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetDeleteStorageDataSupportedOk() (*bool, bool) {
	if o == nil || IsNil(o.DeleteStorageDataSupported) {
		return nil, false
	}
	return o.DeleteStorageDataSupported, true
}

// HasDeleteStorageDataSupported returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasDeleteStorageDataSupported() bool {
	if o != nil && !IsNil(o.DeleteStorageDataSupported) {
		return true
	}

	return false
}

// SetDeleteStorageDataSupported gets a reference to the given bool and assigns it to the DeleteStorageDataSupported field.
func (o *DrsServiceDrs) SetDeleteStorageDataSupported(v bool) {
	o.DeleteStorageDataSupported = &v
}

// GetAccessMethodUpdateSupported returns the AccessMethodUpdateSupported field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetAccessMethodUpdateSupported() bool {
	if o == nil || IsNil(o.AccessMethodUpdateSupported) {
		var ret bool
		return ret
	}
	return *o.AccessMethodUpdateSupported
}

// GetAccessMethodUpdateSupportedOk returns a tuple with the AccessMethodUpdateSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetAccessMethodUpdateSupportedOk() (*bool, bool) {
	if o == nil || IsNil(o.AccessMethodUpdateSupported) {
		return nil, false
	}
	return o.AccessMethodUpdateSupported, true
}

// HasAccessMethodUpdateSupported returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasAccessMethodUpdateSupported() bool {
	if o != nil && !IsNil(o.AccessMethodUpdateSupported) {
		return true
	}

	return false
}

// SetAccessMethodUpdateSupported gets a reference to the given bool and assigns it to the AccessMethodUpdateSupported field.
func (o *DrsServiceDrs) SetAccessMethodUpdateSupported(v bool) {
	o.AccessMethodUpdateSupported = &v
}

// GetMaxBulkAccessMethodUpdateLength returns the MaxBulkAccessMethodUpdateLength field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetMaxBulkAccessMethodUpdateLength() int32 {
	if o == nil || IsNil(o.MaxBulkAccessMethodUpdateLength) {
		var ret int32
		return ret
	}
	return *o.MaxBulkAccessMethodUpdateLength
}

// GetMaxBulkAccessMethodUpdateLengthOk returns a tuple with the MaxBulkAccessMethodUpdateLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetMaxBulkAccessMethodUpdateLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxBulkAccessMethodUpdateLength) {
		return nil, false
	}
	return o.MaxBulkAccessMethodUpdateLength, true
}

// HasMaxBulkAccessMethodUpdateLength returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasMaxBulkAccessMethodUpdateLength() bool {
	if o != nil && !IsNil(o.MaxBulkAccessMethodUpdateLength) {
		return true
	}

	return false
}

// SetMaxBulkAccessMethodUpdateLength gets a reference to the given int32 and assigns it to the MaxBulkAccessMethodUpdateLength field.
func (o *DrsServiceDrs) SetMaxBulkAccessMethodUpdateLength(v int32) {
	o.MaxBulkAccessMethodUpdateLength = &v
}

// GetValidateAccessMethodUpdates returns the ValidateAccessMethodUpdates field value if set, zero value otherwise.
func (o *DrsServiceDrs) GetValidateAccessMethodUpdates() bool {
	if o == nil || IsNil(o.ValidateAccessMethodUpdates) {
		var ret bool
		return ret
	}
	return *o.ValidateAccessMethodUpdates
}

// GetValidateAccessMethodUpdatesOk returns a tuple with the ValidateAccessMethodUpdates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrsServiceDrs) GetValidateAccessMethodUpdatesOk() (*bool, bool) {
	if o == nil || IsNil(o.ValidateAccessMethodUpdates) {
		return nil, false
	}
	return o.ValidateAccessMethodUpdates, true
}

// HasValidateAccessMethodUpdates returns a boolean if a field has been set.
func (o *DrsServiceDrs) HasValidateAccessMethodUpdates() bool {
	if o != nil && !IsNil(o.ValidateAccessMethodUpdates) {
		return true
	}

	return false
}

// SetValidateAccessMethodUpdates gets a reference to the given bool and assigns it to the ValidateAccessMethodUpdates field.
func (o *DrsServiceDrs) SetValidateAccessMethodUpdates(v bool) {
	o.ValidateAccessMethodUpdates = &v
}

func (o DrsServiceDrs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DrsServiceDrs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["maxBulkRequestLength"] = o.MaxBulkRequestLength
	if !IsNil(o.ObjectCount) {
		toSerialize["objectCount"] = o.ObjectCount
	}
	if !IsNil(o.TotalObjectSize) {
		toSerialize["totalObjectSize"] = o.TotalObjectSize
	}
	if !IsNil(o.UploadRequestSupported) {
		toSerialize["uploadRequestSupported"] = o.UploadRequestSupported
	}
	if !IsNil(o.ObjectRegistrationSupported) {
		toSerialize["objectRegistrationSupported"] = o.ObjectRegistrationSupported
	}
	if !IsNil(o.SupportedUploadMethods) {
		toSerialize["supportedUploadMethods"] = o.SupportedUploadMethods
	}
	if !IsNil(o.MaxUploadSize) {
		toSerialize["maxUploadSize"] = o.MaxUploadSize
	}
	if !IsNil(o.MaxUploadRequestLength) {
		toSerialize["maxUploadRequestLength"] = o.MaxUploadRequestLength
	}
	if !IsNil(o.MaxRegisterRequestLength) {
		toSerialize["maxRegisterRequestLength"] = o.MaxRegisterRequestLength
	}
	if !IsNil(o.ValidateUploadChecksums) {
		toSerialize["validateUploadChecksums"] = o.ValidateUploadChecksums
	}
	if !IsNil(o.ValidateUploadFileSizes) {
		toSerialize["validateUploadFileSizes"] = o.ValidateUploadFileSizes
	}
	if !IsNil(o.RelatedFileStorageSupported) {
		toSerialize["relatedFileStorageSupported"] = o.RelatedFileStorageSupported
	}
	if !IsNil(o.DeleteSupported) {
		toSerialize["deleteSupported"] = o.DeleteSupported
	}
	if !IsNil(o.MaxBulkDeleteLength) {
		toSerialize["maxBulkDeleteLength"] = o.MaxBulkDeleteLength
	}
	if !IsNil(o.DeleteStorageDataSupported) {
		toSerialize["deleteStorageDataSupported"] = o.DeleteStorageDataSupported
	}
	if !IsNil(o.AccessMethodUpdateSupported) {
		toSerialize["accessMethodUpdateSupported"] = o.AccessMethodUpdateSupported
	}
	if !IsNil(o.MaxBulkAccessMethodUpdateLength) {
		toSerialize["maxBulkAccessMethodUpdateLength"] = o.MaxBulkAccessMethodUpdateLength
	}
	if !IsNil(o.ValidateAccessMethodUpdates) {
		toSerialize["validateAccessMethodUpdates"] = o.ValidateAccessMethodUpdates
	}
	return toSerialize, nil
}

func (o *DrsServiceDrs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maxBulkRequestLength",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDrsServiceDrs := _DrsServiceDrs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDrsServiceDrs)

	if err != nil {
		return err
	}

	*o = DrsServiceDrs(varDrsServiceDrs)

	return err
}

type NullableDrsServiceDrs struct {
	value *DrsServiceDrs
	isSet bool
}

func (v NullableDrsServiceDrs) Get() *DrsServiceDrs {
	return v.value
}

func (v *NullableDrsServiceDrs) Set(val *DrsServiceDrs) {
	v.value = val
	v.isSet = true
}

func (v NullableDrsServiceDrs) IsSet() bool {
	return v.isSet
}

func (v *NullableDrsServiceDrs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDrsServiceDrs(val *DrsServiceDrs) *NullableDrsServiceDrs {
	return &NullableDrsServiceDrs{value: val, isSet: true}
}

func (v NullableDrsServiceDrs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDrsServiceDrs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


