/*
Data Repository Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.5.0
Contact: ga4gh-cloud@ga4gh.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drsclient

import (
	"encoding/json"
)

// checks if the PostObjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostObjectRequest{}

// PostObjectRequest struct for PostObjectRequest
type PostObjectRequest struct {
	// If false and the object_id refers to a bundle, then the ContentsObject array contains only those objects directly contained in the bundle. That is, if the bundle contains other bundles, those other bundles are not recursively included in the result. If true and the object_id refers to a bundle, then the entire set of objects in the bundle is expanded. That is, if the bundle contains other bundles, then those other bundles are recursively expanded and included in the result. Recursion continues through the entire sub-tree of the bundle. If the object_id refers to a blob, then the query parameter is ignored.
	Expand *bool `json:"expand,omitempty"`
	// the encoded JWT GA4GH Passport that contains embedded Visas.  The overall JWT is signed as are the individual Passport Visas.
	Passports []string `json:"passports,omitempty"`
}

// NewPostObjectRequest instantiates a new PostObjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostObjectRequest() *PostObjectRequest {
	this := PostObjectRequest{}
	return &this
}

// NewPostObjectRequestWithDefaults instantiates a new PostObjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostObjectRequestWithDefaults() *PostObjectRequest {
	this := PostObjectRequest{}
	return &this
}

// GetExpand returns the Expand field value if set, zero value otherwise.
func (o *PostObjectRequest) GetExpand() bool {
	if o == nil || IsNil(o.Expand) {
		var ret bool
		return ret
	}
	return *o.Expand
}

// GetExpandOk returns a tuple with the Expand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostObjectRequest) GetExpandOk() (*bool, bool) {
	if o == nil || IsNil(o.Expand) {
		return nil, false
	}
	return o.Expand, true
}

// HasExpand returns a boolean if a field has been set.
func (o *PostObjectRequest) HasExpand() bool {
	if o != nil && !IsNil(o.Expand) {
		return true
	}

	return false
}

// SetExpand gets a reference to the given bool and assigns it to the Expand field.
func (o *PostObjectRequest) SetExpand(v bool) {
	o.Expand = &v
}

// GetPassports returns the Passports field value if set, zero value otherwise.
func (o *PostObjectRequest) GetPassports() []string {
	if o == nil || IsNil(o.Passports) {
		var ret []string
		return ret
	}
	return o.Passports
}

// GetPassportsOk returns a tuple with the Passports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostObjectRequest) GetPassportsOk() ([]string, bool) {
	if o == nil || IsNil(o.Passports) {
		return nil, false
	}
	return o.Passports, true
}

// HasPassports returns a boolean if a field has been set.
func (o *PostObjectRequest) HasPassports() bool {
	if o != nil && !IsNil(o.Passports) {
		return true
	}

	return false
}

// SetPassports gets a reference to the given []string and assigns it to the Passports field.
func (o *PostObjectRequest) SetPassports(v []string) {
	o.Passports = v
}

func (o PostObjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostObjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Expand) {
		toSerialize["expand"] = o.Expand
	}
	if !IsNil(o.Passports) {
		toSerialize["passports"] = o.Passports
	}
	return toSerialize, nil
}

type NullablePostObjectRequest struct {
	value *PostObjectRequest
	isSet bool
}

func (v NullablePostObjectRequest) Get() *PostObjectRequest {
	return v.value
}

func (v *NullablePostObjectRequest) Set(val *PostObjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostObjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostObjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostObjectRequest(val *PostObjectRequest) *NullablePostObjectRequest {
	return &NullablePostObjectRequest{value: val, isSet: true}
}

func (v NullablePostObjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostObjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


