package common

const (
	RouteInternalDownload                      = "/data/download/{file_id}"
	RouteInternalDownloadPart                  = "/data/download/{file_id}/part"
	RouteInternalUpload                        = "/data/upload"
	RouteInternalUploadURL                     = "/data/upload/{file_id}"
	RouteInternalUploadBulk                    = "/data/upload/bulk"
	RouteInternalMultipartInit                 = "/data/multipart/init"
	RouteInternalMultipartUpload               = "/data/multipart/upload"
	RouteInternalMultipartComplete             = "/data/multipart/complete"
	RouteInternalInspectObject                 = "/data/inspect"
	RouteInternalInspectObjectBulk             = "/data/inspect/bulk"
	RouteInternalInspectObjectBulkList         = "/data/inspect/bulk-list"
	RouteInternalInspectProjectBucket          = "/data/inspect/project-bucket"
	RouteInternalInspectProjectBucketInventory = "/data/inspect/project-bucket/inventory"
	RouteInternalInspectProjectRecords         = "/data/inspect/project-records"
	RouteInternalInspectProjectScopes          = "/data/inspect/project-scopes"
	RouteInternalDeleteProjectBucketObjects    = "/data/inspect/project-bucket/delete"
	RouteInternalBuckets                       = "/data/buckets"
	RouteInternalBucketDetail                  = "/data/buckets/{bucket}"
	RouteInternalBucketScopes                  = "/data/buckets/{bucket}/scopes"
	RouteInternalProjectCleanup                = "/data/projects/{organization}/{project_id}"
	RouteInternalRepairScopeAudit              = "/data/repair/project-scope/audit"
	RouteInternalRepairScopeApply              = "/data/repair/project-scope/apply"

	RouteInternalIndex                       = "/index"
	RouteInternalIndexDetail                 = "/index/{id}"
	RouteInternalIndexControlledAccessRemove = "/index/{id}/controlled-access/remove"
	RouteInternalBulkHashes                  = "/index/bulk/hashes"
	RouteInternalBulkDeleteHashes            = "/index/bulk/delete"
	RouteInternalBulkSHA256                  = "/index/bulk/sha256/validity"
	RouteInternalBulkSHA256Missing           = "/index/bulk/sha256/missing"
	RouteInternalBulkCreate                  = "/index/bulk"
	RouteInternalBulkDocs                    = "/index/bulk/documents"
)
