/*
Internal Metrics API (DRS Server)

Internal file transfer usage metrics endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metricsapi

import (
	"encoding/json"
)

// checks if the MetricsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricsListResponse{}

// MetricsListResponse struct for MetricsListResponse
type MetricsListResponse struct {
	Data   []FileUsage `json:"data,omitempty"`
	Limit  *int32      `json:"limit,omitempty"`
	Offset *int32      `json:"offset,omitempty"`
}

// NewMetricsListResponse instantiates a new MetricsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricsListResponse() *MetricsListResponse {
	this := MetricsListResponse{}
	return &this
}

// NewMetricsListResponseWithDefaults instantiates a new MetricsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsListResponseWithDefaults() *MetricsListResponse {
	this := MetricsListResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MetricsListResponse) GetData() []FileUsage {
	if o == nil || IsNil(o.Data) {
		var ret []FileUsage
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsListResponse) GetDataOk() ([]FileUsage, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MetricsListResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []FileUsage and assigns it to the Data field.
func (o *MetricsListResponse) SetData(v []FileUsage) {
	o.Data = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *MetricsListResponse) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsListResponse) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *MetricsListResponse) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *MetricsListResponse) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *MetricsListResponse) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *MetricsListResponse) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *MetricsListResponse) SetOffset(v int32) {
	o.Offset = &v
}

func (o MetricsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	return toSerialize, nil
}

type NullableMetricsListResponse struct {
	value *MetricsListResponse
	isSet bool
}

func (v NullableMetricsListResponse) Get() *MetricsListResponse {
	return v.value
}

func (v *NullableMetricsListResponse) Set(val *MetricsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricsListResponse(val *MetricsListResponse) *NullableMetricsListResponse {
	return &NullableMetricsListResponse{value: val, isSet: true}
}

func (v NullableMetricsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
