/*
Internal Metrics API (DRS Server)

Internal file transfer usage metrics endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metricsapi

import (
	"encoding/json"
	"time"
)

// checks if the FileUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileUsage{}

// FileUsage struct for FileUsage
type FileUsage struct {
	ObjectId         *string      `json:"object_id,omitempty"`
	Name             *string      `json:"name,omitempty"`
	Size             *int64       `json:"size,omitempty"`
	UploadCount      *int64       `json:"upload_count,omitempty"`
	DownloadCount    *int64       `json:"download_count,omitempty"`
	LastUploadTime   NullableTime `json:"last_upload_time,omitempty"`
	LastDownloadTime NullableTime `json:"last_download_time,omitempty"`
	LastAccessTime   NullableTime `json:"last_access_time,omitempty"`
}

// NewFileUsage instantiates a new FileUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileUsage() *FileUsage {
	this := FileUsage{}
	return &this
}

// NewFileUsageWithDefaults instantiates a new FileUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileUsageWithDefaults() *FileUsage {
	this := FileUsage{}
	return &this
}

// GetObjectId returns the ObjectId field value if set, zero value otherwise.
func (o *FileUsage) GetObjectId() string {
	if o == nil || IsNil(o.ObjectId) {
		var ret string
		return ret
	}
	return *o.ObjectId
}

// GetObjectIdOk returns a tuple with the ObjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileUsage) GetObjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectId) {
		return nil, false
	}
	return o.ObjectId, true
}

// HasObjectId returns a boolean if a field has been set.
func (o *FileUsage) HasObjectId() bool {
	if o != nil && !IsNil(o.ObjectId) {
		return true
	}

	return false
}

// SetObjectId gets a reference to the given string and assigns it to the ObjectId field.
func (o *FileUsage) SetObjectId(v string) {
	o.ObjectId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FileUsage) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileUsage) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FileUsage) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FileUsage) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *FileUsage) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileUsage) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *FileUsage) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *FileUsage) SetSize(v int64) {
	o.Size = &v
}

// GetUploadCount returns the UploadCount field value if set, zero value otherwise.
func (o *FileUsage) GetUploadCount() int64 {
	if o == nil || IsNil(o.UploadCount) {
		var ret int64
		return ret
	}
	return *o.UploadCount
}

// GetUploadCountOk returns a tuple with the UploadCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileUsage) GetUploadCountOk() (*int64, bool) {
	if o == nil || IsNil(o.UploadCount) {
		return nil, false
	}
	return o.UploadCount, true
}

// HasUploadCount returns a boolean if a field has been set.
func (o *FileUsage) HasUploadCount() bool {
	if o != nil && !IsNil(o.UploadCount) {
		return true
	}

	return false
}

// SetUploadCount gets a reference to the given int64 and assigns it to the UploadCount field.
func (o *FileUsage) SetUploadCount(v int64) {
	o.UploadCount = &v
}

// GetDownloadCount returns the DownloadCount field value if set, zero value otherwise.
func (o *FileUsage) GetDownloadCount() int64 {
	if o == nil || IsNil(o.DownloadCount) {
		var ret int64
		return ret
	}
	return *o.DownloadCount
}

// GetDownloadCountOk returns a tuple with the DownloadCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileUsage) GetDownloadCountOk() (*int64, bool) {
	if o == nil || IsNil(o.DownloadCount) {
		return nil, false
	}
	return o.DownloadCount, true
}

// HasDownloadCount returns a boolean if a field has been set.
func (o *FileUsage) HasDownloadCount() bool {
	if o != nil && !IsNil(o.DownloadCount) {
		return true
	}

	return false
}

// SetDownloadCount gets a reference to the given int64 and assigns it to the DownloadCount field.
func (o *FileUsage) SetDownloadCount(v int64) {
	o.DownloadCount = &v
}

// GetLastUploadTime returns the LastUploadTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileUsage) GetLastUploadTime() time.Time {
	if o == nil || IsNil(o.LastUploadTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUploadTime.Get()
}

// GetLastUploadTimeOk returns a tuple with the LastUploadTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileUsage) GetLastUploadTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUploadTime.Get(), o.LastUploadTime.IsSet()
}

// HasLastUploadTime returns a boolean if a field has been set.
func (o *FileUsage) HasLastUploadTime() bool {
	if o != nil && o.LastUploadTime.IsSet() {
		return true
	}

	return false
}

// SetLastUploadTime gets a reference to the given NullableTime and assigns it to the LastUploadTime field.
func (o *FileUsage) SetLastUploadTime(v time.Time) {
	o.LastUploadTime.Set(&v)
}

// SetLastUploadTimeNil sets the value for LastUploadTime to be an explicit nil
func (o *FileUsage) SetLastUploadTimeNil() {
	o.LastUploadTime.Set(nil)
}

// UnsetLastUploadTime ensures that no value is present for LastUploadTime, not even an explicit nil
func (o *FileUsage) UnsetLastUploadTime() {
	o.LastUploadTime.Unset()
}

// GetLastDownloadTime returns the LastDownloadTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileUsage) GetLastDownloadTime() time.Time {
	if o == nil || IsNil(o.LastDownloadTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastDownloadTime.Get()
}

// GetLastDownloadTimeOk returns a tuple with the LastDownloadTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileUsage) GetLastDownloadTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastDownloadTime.Get(), o.LastDownloadTime.IsSet()
}

// HasLastDownloadTime returns a boolean if a field has been set.
func (o *FileUsage) HasLastDownloadTime() bool {
	if o != nil && o.LastDownloadTime.IsSet() {
		return true
	}

	return false
}

// SetLastDownloadTime gets a reference to the given NullableTime and assigns it to the LastDownloadTime field.
func (o *FileUsage) SetLastDownloadTime(v time.Time) {
	o.LastDownloadTime.Set(&v)
}

// SetLastDownloadTimeNil sets the value for LastDownloadTime to be an explicit nil
func (o *FileUsage) SetLastDownloadTimeNil() {
	o.LastDownloadTime.Set(nil)
}

// UnsetLastDownloadTime ensures that no value is present for LastDownloadTime, not even an explicit nil
func (o *FileUsage) UnsetLastDownloadTime() {
	o.LastDownloadTime.Unset()
}

// GetLastAccessTime returns the LastAccessTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileUsage) GetLastAccessTime() time.Time {
	if o == nil || IsNil(o.LastAccessTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastAccessTime.Get()
}

// GetLastAccessTimeOk returns a tuple with the LastAccessTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileUsage) GetLastAccessTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastAccessTime.Get(), o.LastAccessTime.IsSet()
}

// HasLastAccessTime returns a boolean if a field has been set.
func (o *FileUsage) HasLastAccessTime() bool {
	if o != nil && o.LastAccessTime.IsSet() {
		return true
	}

	return false
}

// SetLastAccessTime gets a reference to the given NullableTime and assigns it to the LastAccessTime field.
func (o *FileUsage) SetLastAccessTime(v time.Time) {
	o.LastAccessTime.Set(&v)
}

// SetLastAccessTimeNil sets the value for LastAccessTime to be an explicit nil
func (o *FileUsage) SetLastAccessTimeNil() {
	o.LastAccessTime.Set(nil)
}

// UnsetLastAccessTime ensures that no value is present for LastAccessTime, not even an explicit nil
func (o *FileUsage) UnsetLastAccessTime() {
	o.LastAccessTime.Unset()
}

func (o FileUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObjectId) {
		toSerialize["object_id"] = o.ObjectId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.UploadCount) {
		toSerialize["upload_count"] = o.UploadCount
	}
	if !IsNil(o.DownloadCount) {
		toSerialize["download_count"] = o.DownloadCount
	}
	if o.LastUploadTime.IsSet() {
		toSerialize["last_upload_time"] = o.LastUploadTime.Get()
	}
	if o.LastDownloadTime.IsSet() {
		toSerialize["last_download_time"] = o.LastDownloadTime.Get()
	}
	if o.LastAccessTime.IsSet() {
		toSerialize["last_access_time"] = o.LastAccessTime.Get()
	}
	return toSerialize, nil
}

type NullableFileUsage struct {
	value *FileUsage
	isSet bool
}

func (v NullableFileUsage) Get() *FileUsage {
	return v.value
}

func (v *NullableFileUsage) Set(val *FileUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableFileUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableFileUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileUsage(val *FileUsage) *NullableFileUsage {
	return &NullableFileUsage{value: val, isSet: true}
}

func (v NullableFileUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
